/**
 * tau_empire - unit index.
 *
 * Each unit is a PURE JSON file next to this one, so the codex tooling can rewrite it from the
 * sheets without touching any TypeScript. This is the only .ts in the folder: it imports them
 * and exports `faction`, `slot_to_units` and `units` exactly as the old per-slot indexes did.
 *
 * Generated by scripts/convert_units_to_json.cjs. To add a unit, add its .json and one line here.
 */

import type { Unit } from '../../../../src/types/data';

import hq_commander from './hq/commander.json';
import hq_ethereal from './hq/ethereal.json';
import hq_ethereal_guard from './hq/ethereal_guard.json';
import hq_kroot_master_shaper from './hq/kroot_master_shaper.json';
import hq_sub_commander from './hq/sub_commander.json';
import troops_breacher_team from './troops/breacher_team.json';
import troops_kroot_carnivores from './troops/kroot_carnivores.json';
import troops_strike_team from './troops/strike_team.json';
import troops_support_turrets from './troops/support_turrets.json';
import elites_crisis_battlesuits from './elites/crisis_battlesuits.json';
import elites_crisis_honor_guard from './elites/crisis_honor_guard.json';
import elites_ghostkeel_battlesuits from './elites/ghostkeel_battlesuits.json';
import elites_kroot_farstalkers from './elites/kroot_farstalkers.json';
import elites_kroot_lone_spear from './elites/kroot_lone_spear.json';
import elites_kroot_shaper from './elites/kroot_shaper.json';
import elites_stealth_battlesuits from './elites/stealth_battlesuits.json';
import fast_attack_firesight_marksman from './fast_attack/firesight_marksman.json';
import fast_attack_great_knarloc from './fast_attack/great_knarloc.json';
import fast_attack_hazard_battlesuits from './fast_attack/hazard_battlesuits.json';
import fast_attack_kroot_hounds from './fast_attack/kroot_hounds.json';
import fast_attack_kroot_trackers from './fast_attack/kroot_trackers.json';
import fast_attack_kroot_vultures from './fast_attack/kroot_vultures.json';
import fast_attack_krootox_rampagers from './fast_attack/krootox_rampagers.json';
import fast_attack_pathfinder_team from './fast_attack/pathfinder_team.json';
import fast_attack_piranha from './fast_attack/piranha.json';
import fast_attack_rvarna_battlesuit from './fast_attack/rvarna_battlesuit.json';
import fast_attack_remora_stealth_drones from './fast_attack/remora_stealth_drones.json';
import fast_attack_tetras from './fast_attack/tetras.json';
import fast_attack_vespid_stingwings from './fast_attack/vespid_stingwings.json';
import fast_attack_yvahra_battlesuit from './fast_attack/yvahra_battlesuit.json';
import heavy_support_broadside_battlesuits from './heavy_support/broadside_battlesuits.json';
import heavy_support_hammerhead_gunship from './heavy_support/hammerhead_gunship.json';
import heavy_support_krootox_riders from './heavy_support/krootox_riders.json';
import heavy_support_riptide_battlesuit from './heavy_support/riptide_battlesuit.json';
import heavy_support_sky_ray_gunship from './heavy_support/sky_ray_gunship.json';
import dedicated_transport_devilfish from './dedicated_transport/devilfish.json';
import fortifications_tidewall_droneport from './fortifications/tidewall_droneport.json';
import fortifications_tidewall_gunrig from './fortifications/tidewall_gunrig.json';
import fortifications_tidewall_shieldline from './fortifications/tidewall_shieldline.json';
import flyers_barracuda_air_superiority_fighter from './flyers/barracuda_air_superiority_fighter.json';
import flyers_razorshark_strike_fighter from './flyers/razorshark_strike_fighter.json';
import flyers_sun_shark_bomber from './flyers/sun_shark_bomber.json';
import lords_of_war_stormsurge from './lords_of_war/stormsurge.json';

export const faction = "Tau Empire";

export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Commander",
    "Ethereal",
    "Ethereal Guard",
    "Kroot Master Shaper",
    "Sub-Commander"
  ],
  "Troops": [
    "Breacher Team",
    "Kroot Carnivores",
    "Strike Team",
    "Support Turrets"
  ],
  "Elites": [
    "Crisis Battlesuits",
    "Crisis Honor Guard",
    "Ghostkeel Battlesuits",
    "Kroot Farstalkers",
    "Kroot Lone-Spear",
    "Kroot Shaper",
    "Stealth Battlesuits"
  ],
  "Fast Attack": [
    "Firesight Marksman",
    "Kroot Great Knarloc",
    "Hazard Battlesuits",
    "Kroot Hounds",
    "Kroot Trackers",
    "Kroot Vultures",
    "Krootox Rampagers",
    "Pathfinder Team",
    "Piranha",
    "R'varna Battlesuit",
    "Remora Stealth Drones",
    "Tetras",
    "Vespid Stingwings",
    "Y'vahra Battlesuit"
  ],
  "Heavy Support": [
    "Broadside Battlesuits",
    "Hammerhead Gunship",
    "Krootox Riders",
    "Riptide Battlesuit",
    "Sky Ray Gunship"
  ],
  "Dedicated Transport": [
    "Devilfish"
  ],
  "Fortifications": [
    "Tidewall Droneport",
    "Tidewall Gunrig",
    "Tidewall Shieldwall"
  ],
  "Flyers": [
    "Barracuda Air Superiority Fighter",
    "Razorshark Strike Fighter",
    "Sun Shark Bomber"
  ],
  "Lords of War": [
    "Stormsurge"
  ]
};

/** All units keyed by name. */
export const units: Record<string, Unit> = {
  "Commander": hq_commander as Unit,
  "Ethereal": hq_ethereal as Unit,
  "Ethereal Guard": hq_ethereal_guard as Unit,
  "Kroot Master Shaper": hq_kroot_master_shaper as Unit,
  "Sub-Commander": hq_sub_commander as Unit,
  "Breacher Team": troops_breacher_team as Unit,
  "Kroot Carnivores": troops_kroot_carnivores as Unit,
  "Strike Team": troops_strike_team as Unit,
  "Support Turrets": troops_support_turrets as Unit,
  "Crisis Battlesuits": elites_crisis_battlesuits as Unit,
  "Crisis Honor Guard": elites_crisis_honor_guard as Unit,
  "Ghostkeel Battlesuits": elites_ghostkeel_battlesuits as Unit,
  "Kroot Farstalkers": elites_kroot_farstalkers as Unit,
  "Kroot Lone-Spear": elites_kroot_lone_spear as Unit,
  "Kroot Shaper": elites_kroot_shaper as Unit,
  "Stealth Battlesuits": elites_stealth_battlesuits as Unit,
  "Firesight Marksman": fast_attack_firesight_marksman as Unit,
  "Kroot Great Knarloc": fast_attack_great_knarloc as Unit,
  "Hazard Battlesuits": fast_attack_hazard_battlesuits as Unit,
  "Kroot Hounds": fast_attack_kroot_hounds as Unit,
  "Kroot Trackers": fast_attack_kroot_trackers as Unit,
  "Kroot Vultures": fast_attack_kroot_vultures as Unit,
  "Krootox Rampagers": fast_attack_krootox_rampagers as Unit,
  "Pathfinder Team": fast_attack_pathfinder_team as Unit,
  "Piranha": fast_attack_piranha as Unit,
  "R'varna Battlesuit": fast_attack_rvarna_battlesuit as Unit,
  "Remora Stealth Drones": fast_attack_remora_stealth_drones as Unit,
  "Tetras": fast_attack_tetras as Unit,
  "Vespid Stingwings": fast_attack_vespid_stingwings as Unit,
  "Y'vahra Battlesuit": fast_attack_yvahra_battlesuit as Unit,
  "Broadside Battlesuits": heavy_support_broadside_battlesuits as Unit,
  "Hammerhead Gunship": heavy_support_hammerhead_gunship as Unit,
  "Krootox Riders": heavy_support_krootox_riders as Unit,
  "Riptide Battlesuit": heavy_support_riptide_battlesuit as Unit,
  "Sky Ray Gunship": heavy_support_sky_ray_gunship as Unit,
  "Devilfish": dedicated_transport_devilfish as Unit,
  "Tidewall Droneport": fortifications_tidewall_droneport as Unit,
  "Tidewall Gunrig": fortifications_tidewall_gunrig as Unit,
  "Tidewall Shieldwall": fortifications_tidewall_shieldline as Unit,
  "Barracuda Air Superiority Fighter": flyers_barracuda_air_superiority_fighter as Unit,
  "Razorshark Strike Fighter": flyers_razorshark_strike_fighter as Unit,
  "Sun Shark Bomber": flyers_sun_shark_bomber as Unit,
  "Stormsurge": lords_of_war_stormsurge as Unit,
};
