/**
 * Tau Empire — unit index
 * Auto-generated by _migrate_units_to_ts.cjs
 * Each unit lives in its own file under units/<slot>/<name>.ts
 * Add SOURCE comments and engine status notes when auditing each unit.
 */

import * as dedicatedTransport from './dedicated_transport/index';
import * as elites from './elites/index';
import * as fastAttack from './fast_attack/index';
import * as flyers from './flyers/index';
import * as fortifications from './fortifications/index';
import * as heavySupport from './heavy_support/index';
import * as hq from './hq/index';
import * as lordsOfWar from './lords_of_war/index';
import * as troops from './troops/index';

/** All units keyed by name — drop-in replacement for units.json "units" field. */
export const units: Record<string, import('../../../../src/types/data').Unit> = {
  "Commander": hq.commander,
  "Ethereal": hq.ethereal,
  "Ethereal Guard": hq.etherealGuard,
  "Kroot Master Shaper": hq.krootMasterShaper,
  "Sub-Commander": hq.subCommander,
  "Breacher Team": troops.breacherTeam,
  "Kroot Carnivores": troops.krootCarnivores,
  "Strike Team": troops.strikeTeam,
  "Support Turrets": troops.supportTurrets,
  "Crisis Battlesuits": elites.crisisBattlesuits,
  "Crisis Honor Guard": elites.crisisHonorGuard,
  "Ghostkeel Battlesuits": elites.ghostkeelBattlesuits,
  "Kroot Farstalkers": elites.krootFarstalkers,
  "Kroot Lone-Spear": elites.krootLoneSpear,
  "Kroot Shaper": elites.krootShaper,
  "Stealth Battlesuits": elites.stealthBattlesuits,
  "Firesight Marksman": fastAttack.firesightMarksman,
  "Great Knarloc": fastAttack.greatKnarloc,
  "Hazard Battlesuits": fastAttack.hazardBattlesuits,
  "Kroot Hounds": fastAttack.krootHounds,
  "Kroot Trackers": fastAttack.krootTrackers,
  "Kroot Vultures": fastAttack.krootVultures,
  "Krootox Rampagers": fastAttack.krootoxRampagers,
  "Pathfinder Team": fastAttack.pathfinderTeam,
  "Piranha": fastAttack.piranha,
  "R'varna Battlesuit": fastAttack.rvarnaBattlesuit,
  "Remora Stealth Drones": fastAttack.remoraStealthDrones,
  "Tetras": fastAttack.tetras,
  "Vespid Stingwings": fastAttack.vespidStingwings,
  "Y'vahra Battlesuit": fastAttack.yvahraBattlesuit,
  "Broadside Battlesuits": heavySupport.broadsideBattlesuits,
  "Hammerhead Gunship": heavySupport.hammerheadGunship,
  "Krootox Riders": heavySupport.krootoxRiders,
  "Riptide Battlesuit": heavySupport.riptideBattlesuit,
  "Sky Ray Gunship": heavySupport.skyRayGunship,
  "Devilfish": dedicatedTransport.devilfish,
  "Tidewall Droneport": fortifications.tidewallDroneport,
  "Tidewall Gunrig": fortifications.tidewallGunrig,
  "Tidewall Shieldline": fortifications.tidewallShieldline,
  "Barracuda Air Superiority Fighter": flyers.barracudaAirSuperiorityFighter,
  "Razorshark Strike Fighter": flyers.razorsharkStrikeFighter,
  "Sun Shark Bomber": flyers.sunSharkBomber,
  "Stormsurge": lordsOfWar.stormsurge,
};

/** Slot → unit names map — same as units.json "slot_to_units" field. */
export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Commander",
    "Ethereal",
    "Ethereal Guard",
    "Kroot Master Shaper",
    "Sub-Commander"
  ],
  "Troops": [
    "Breacher Team",
    "Kroot Carnivores",
    "Strike Team",
    "Support Turrets"
  ],
  "Elites": [
    "Crisis Battlesuits",
    "Crisis Honor Guard",
    "Ghostkeel Battlesuits",
    "Kroot Farstalkers",
    "Kroot Lone-Spear",
    "Kroot Shaper",
    "Stealth Battlesuits"
  ],
  "Fast Attack": [
    "Firesight Marksman",
    "Great Knarloc",
    "Hazard Battlesuits",
    "Kroot Hounds",
    "Kroot Trackers",
    "Kroot Vultures",
    "Krootox Rampagers",
    "Pathfinder Team",
    "Piranha",
    "R'varna Battlesuit",
    "Remora Stealth Drones",
    "Tetras",
    "Vespid Stingwings",
    "Y'vahra Battlesuit"
  ],
  "Heavy Support": [
    "Broadside Battlesuits",
    "Hammerhead Gunship",
    "Krootox Riders",
    "Riptide Battlesuit",
    "Sky Ray Gunship"
  ],
  "Dedicated Transport": [
    "Devilfish"
  ],
  "Fortifications": [
    "Tidewall Droneport",
    "Tidewall Gunrig",
    "Tidewall Shieldline"
  ],
  "Flyers": [
    "Barracuda Air Superiority Fighter",
    "Razorshark Strike Fighter",
    "Sun Shark Bomber"
  ],
  "Lords of War": [
    "Stormsurge"
  ]
};

export const faction = "Tau Empire";
