/**
 * eldar - unit index.
 *
 * Each unit is a PURE JSON file next to this one, so the codex tooling can rewrite it from the
 * sheets without touching any TypeScript. This is the only .ts in the folder: it imports them
 * and exports `faction`, `slot_to_units` and `units` exactly as the old per-slot indexes did.
 *
 * Generated by scripts/convert_units_to_json.cjs. To add a unit, add its .json and one line here.
 */

import type { Unit } from '../../../../src/types/data';

import hq_autarch from './hq/autarch.json';
import hq_avatar_of_khaine from './hq/avatar_of_khaine.json';
import hq_farseer from './hq/farseer.json';
import hq_spiritseer from './hq/spiritseer.json';
import hq_wraithseer from './hq/wraithseer.json';
import hq_yncarne from './hq/yncarne.json';
import troops_corsair_voidreavers from './troops/corsair_voidreavers.json';
import troops_guardian_defenders from './troops/guardian_defenders.json';
import troops_rangers from './troops/rangers.json';
import troops_storm_guardians from './troops/storm_guardians.json';
import troops_wasps from './troops/wasps.json';
import elites_corsair_voidscarred from './elites/corsair_voidscarred.json';
import elites_dire_avengers from './elites/dire_avengers.json';
import elites_fire_dragons from './elites/fire_dragons.json';
import elites_howling_banshees from './elites/howling_banshees.json';
import elites_shadow_spectres from './elites/shadow_spectres.json';
import elites_striking_scorpions from './elites/striking_scorpions.json';
import elites_warlocks from './elites/warlocks.json';
import elites_wraithblades from './elites/wraithblades.json';
import elites_wraithguard from './elites/wraithguard.json';
import elites_wraithlord from './elites/wraithlord.json';
import fast_attack_hornets from './fast_attack/hornets.json';
import fast_attack_shining_spears from './fast_attack/shining_spears.json';
import fast_attack_shroud_runners from './fast_attack/shroud_runners.json';
import fast_attack_swooping_hawks from './fast_attack/swooping_hawks.json';
import fast_attack_vypers from './fast_attack/vypers.json';
import fast_attack_warp_spiders from './fast_attack/warp_spiders.json';
import fast_attack_windriders from './fast_attack/windriders.json';
import heavy_support_dark_reapers from './heavy_support/dark_reapers.json';
import heavy_support_falcon from './heavy_support/falcon.json';
import heavy_support_fire_prism from './heavy_support/fire_prism.json';
import heavy_support_night_spinner from './heavy_support/night_spinner.json';
import heavy_support_support_weapons from './heavy_support/support_weapons.json';
import heavy_support_war_walkers from './heavy_support/war_walkers.json';
import dedicated_transport_wave_serpent from './dedicated_transport/wave_serpent.json';
import flyers_crimson_hunter from './flyers/crimson_hunter.json';
import flyers_nightwing from './flyers/nightwing.json';
import flyers_phoenix from './flyers/phoenix.json';
import lords_of_war_lynx from './lords_of_war/lynx.json';
import lords_of_war_vampire from './lords_of_war/vampire.json';
import lords_of_war_warp_hunter from './lords_of_war/warp_hunter.json';
import lords_of_war_wraithknight from './lords_of_war/wraithknight.json';

export const faction = "Eldar";

export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Autarch",
    "Avatar of Khaine",
    "Farseer",
    "Spiritseer",
    "Wraithseer",
    "Yncarne"
  ],
  "Troops": [
    "Voidreavers",
    "Guardian Defenders",
    "Rangers",
    "Storm Guardians",
    "Wasps"
  ],
  "Elites": [
    "Voidscarred",
    "Dire Avengers",
    "Fire Dragons",
    "Howling Banshees",
    "Shadow Spectres",
    "Striking Scorpions",
    "Warlocks",
    "Wraithblades",
    "Wraithguard",
    "Wraithlord"
  ],
  "Fast Attack": [
    "Hornets",
    "Shining Spears",
    "Shroud Runners",
    "Swooping Hawks",
    "Vypers",
    "Warp Spiders",
    "Windriders"
  ],
  "Heavy Support": [
    "Dark Reapers",
    "Falcon",
    "Fire Prism",
    "Night Spinner",
    "Support Weapons",
    "War Walkers"
  ],
  "Dedicated Transport": [
    "Wave Serpent"
  ],
  "Fortifications": [],
  "Lords of War": [
    "Lynx",
    "Vampire",
    "Warp Hunter",
    "Wraithknight"
  ],
  "Flyers": [
    "Crimson Hunter",
    "Nightwing",
    "Phoenix"
  ]
};

/** All units keyed by name. */
export const units: Record<string, Unit> = {
  "Autarch": hq_autarch as Unit,
  "Avatar of Khaine": hq_avatar_of_khaine as Unit,
  "Farseer": hq_farseer as Unit,
  "Spiritseer": hq_spiritseer as Unit,
  "Wraithseer": hq_wraithseer as Unit,
  "Yncarne": hq_yncarne as Unit,
  "Voidreavers": troops_corsair_voidreavers as Unit,
  "Guardian Defenders": troops_guardian_defenders as Unit,
  "Rangers": troops_rangers as Unit,
  "Storm Guardians": troops_storm_guardians as Unit,
  "Wasps": troops_wasps as Unit,
  "Voidscarred": elites_corsair_voidscarred as Unit,
  "Dire Avengers": elites_dire_avengers as Unit,
  "Fire Dragons": elites_fire_dragons as Unit,
  "Howling Banshees": elites_howling_banshees as Unit,
  "Shadow Spectres": elites_shadow_spectres as Unit,
  "Striking Scorpions": elites_striking_scorpions as Unit,
  "Warlocks": elites_warlocks as Unit,
  "Wraithblades": elites_wraithblades as Unit,
  "Wraithguard": elites_wraithguard as Unit,
  "Wraithlord": elites_wraithlord as Unit,
  "Hornets": fast_attack_hornets as Unit,
  "Shining Spears": fast_attack_shining_spears as Unit,
  "Shroud Runners": fast_attack_shroud_runners as Unit,
  "Swooping Hawks": fast_attack_swooping_hawks as Unit,
  "Vypers": fast_attack_vypers as Unit,
  "Warp Spiders": fast_attack_warp_spiders as Unit,
  "Windriders": fast_attack_windriders as Unit,
  "Dark Reapers": heavy_support_dark_reapers as Unit,
  "Falcon": heavy_support_falcon as Unit,
  "Fire Prism": heavy_support_fire_prism as Unit,
  "Night Spinner": heavy_support_night_spinner as Unit,
  "Support Weapons": heavy_support_support_weapons as Unit,
  "War Walkers": heavy_support_war_walkers as Unit,
  "Wave Serpent": dedicated_transport_wave_serpent as Unit,
  "Crimson Hunter": flyers_crimson_hunter as Unit,
  "Nightwing": flyers_nightwing as Unit,
  "Phoenix": flyers_phoenix as Unit,
  "Lynx": lords_of_war_lynx as Unit,
  "Vampire": lords_of_war_vampire as Unit,
  "Warp Hunter": lords_of_war_warp_hunter as Unit,
  "Wraithknight": lords_of_war_wraithknight as Unit,
};
