/**
 * Eldar — unit index
 * Auto-generated by _migrate_units_to_ts.cjs
 * Each unit lives in its own file under units/<slot>/<name>.ts
 * Add SOURCE comments and engine status notes when auditing each unit.
 */

import * as dedicatedTransport from './dedicated_transport/index';
import * as elites from './elites/index';
import * as fastAttack from './fast_attack/index';
import * as flyers from './flyers/index';
import * as heavySupport from './heavy_support/index';
import * as hq from './hq/index';
import * as lordsOfWar from './lords_of_war/index';
import * as troops from './troops/index';

/** All units keyed by name — drop-in replacement for units.json "units" field. */
export const units: Record<string, import('../../../../src/types/data').Unit> = {
  "Autarch": hq.autarch,
  "Avatar of Khaine": hq.avatarOfKhaine,
  "Farseer": hq.farseer,
  "Spiritseer": hq.spiritseer,
  "Wraithseer": hq.wraithseer,
  "Yncarne": hq.yncarne,
  "Corsair Voidreavers": troops.corsairVoidreavers,
  "Guardian Defenders": troops.guardianDefenders,
  "Rangers": troops.rangers,
  "Storm Guardians": troops.stormGuardians,
  "Wasps": troops.wasps,
  "Corsair Voidscarred": elites.corsairVoidscarred,
  "Dire Avengers": elites.direAvengers,
  "Fire Dragons": elites.fireDragons,
  "Howling Banshees": elites.howlingBanshees,
  "Shadow Spectres": elites.shadowSpectres,
  "Striking Scorpions": elites.strikingScorpions,
  "Warlocks": elites.warlocks,
  "Wraithblades": elites.wraithblades,
  "Wraithguard": elites.wraithguard,
  "Wraithlord": elites.wraithlord,
  "Hornets": fastAttack.hornets,
  "Shining Spears": fastAttack.shiningSpears,
  "Shroud Runners": fastAttack.shroudRunners,
  "Swooping Hawks": fastAttack.swoopingHawks,
  "Vypers": fastAttack.vypers,
  "Warp Spiders": fastAttack.warpSpiders,
  "Windriders": fastAttack.windriders,
  "Dark Reapers": heavySupport.darkReapers,
  "Falcon": heavySupport.falcon,
  "Fire Prism": heavySupport.firePrism,
  "Night Spinner": heavySupport.nightSpinner,
  "Support Weapons": heavySupport.supportWeapons,
  "War Walkers": heavySupport.warWalkers,
  "Wave Serpent": dedicatedTransport.waveSerpent,
  "Crimson Hunter": flyers.crimsonHunter,
  "Nightwing": flyers.nightwing,
  "Phoenix": flyers.phoenix,
  "Lynx": lordsOfWar.lynx,
  "Vampire": lordsOfWar.vampire,
  "Warp Hunter": lordsOfWar.warpHunter,
  "Wraithknight": lordsOfWar.wraithknight,
};

/** Slot → unit names map — same as units.json "slot_to_units" field. */
export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Autarch",
    "Avatar of Khaine",
    "Farseer",
    "Spiritseer",
    "Wraithseer",
    "Yncarne"
  ],
  "Troops": [
    "Corsair Voidreavers",
    "Guardian Defenders",
    "Rangers",
    "Storm Guardians",
    "Wasps"
  ],
  "Elites": [
    "Corsair Voidscarred",
    "Dire Avengers",
    "Fire Dragons",
    "Howling Banshees",
    "Shadow Spectres",
    "Striking Scorpions",
    "Warlocks",
    "Wraithblades",
    "Wraithguard",
    "Wraithlord"
  ],
  "Fast Attack": [
    "Hornets",
    "Shining Spears",
    "Shroud Runners",
    "Swooping Hawks",
    "Vypers",
    "Warp Spiders",
    "Windriders"
  ],
  "Heavy Support": [
    "Dark Reapers",
    "Falcon",
    "Fire Prism",
    "Night Spinner",
    "Support Weapons",
    "War Walkers"
  ],
  "Dedicated Transport": [
    "Wave Serpent"
  ],
  "Fortifications": [],
  "Lords of War": [
    "Lynx",
    "Vampire",
    "Warp Hunter",
    "Wraithknight"
  ],
  "Flyers": [
    "Crimson Hunter",
    "Nightwing",
    "Phoenix"
  ]
};

export const faction = "Eldar";
