/**
 * harlequins - unit index.
 *
 * Each unit is a PURE JSON file next to this one, so the codex tooling can rewrite it from the
 * sheets without touching any TypeScript. This is the only .ts in the folder: it imports them
 * and exports `faction`, `slot_to_units` and `units` exactly as the old per-slot indexes did.
 *
 * Generated by scripts/convert_units_to_json.cjs. To add a unit, add its .json and one line here.
 */

import type { Unit } from '../../../../src/types/data';

import hq_great_harlequin from './hq/great_harlequin.json';
import troops_troupe from './troops/troupe.json';
import elites_death_jester from './elites/death_jester.json';
import elites_shadowseer from './elites/shadowseer.json';
import elites_solitaire from './elites/solitaire.json';
import fast_attack_skyweavers from './fast_attack/skyweavers.json';
import heavy_support_harlequin_wraithlord from './heavy_support/harlequin_wraithlord.json';
import heavy_support_voidweaver from './heavy_support/voidweaver.json';
import dedicated_transport_starweaver from './dedicated_transport/starweaver.json';

export const faction = "Harlequins";

export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Great Harlequin"
  ],
  "Troops": [
    "Troupe"
  ],
  "Elites": [
    "Death Jester",
    "Shadowseer",
    "Solitaire"
  ],
  "Fast Attack": [
    "Skyweavers"
  ],
  "Heavy Support": [
    "Harlequin Wraithlord",
    "Voidweaver"
  ],
  "Dedicated Transport": [
    "Starweaver"
  ],
  "Fortifications": [],
  "Flyers": []
};

/** All units keyed by name. */
export const units: Record<string, Unit> = {
  "Great Harlequin": hq_great_harlequin as Unit,
  "Troupe": troops_troupe as Unit,
  "Death Jester": elites_death_jester as Unit,
  "Shadowseer": elites_shadowseer as Unit,
  "Solitaire": elites_solitaire as Unit,
  "Skyweavers": fast_attack_skyweavers as Unit,
  "Harlequin Wraithlord": heavy_support_harlequin_wraithlord as Unit,
  "Voidweaver": heavy_support_voidweaver as Unit,
  "Starweaver": dedicated_transport_starweaver as Unit,
};
