/**
 * Harlequins — unit index
 * Auto-generated by _migrate_units_to_ts.cjs
 * Each unit lives in its own file under units/<slot>/<name>.ts
 * Add SOURCE comments and engine status notes when auditing each unit.
 */

import * as dedicatedTransport from './dedicated_transport/index';
import * as elites from './elites/index';
import * as fastAttack from './fast_attack/index';
import * as heavySupport from './heavy_support/index';
import * as hq from './hq/index';
import * as troops from './troops/index';

/** All units keyed by name — drop-in replacement for units.json "units" field. */
export const units: Record<string, import('../../../../src/types/data').Unit> = {
  "Great Harlequin": hq.greatHarlequin,
  "Troupe": troops.troupe,
  "Death Jester": elites.deathJester,
  "Shadowseer": elites.shadowseer,
  "Solitaire": elites.solitaire,
  "Skyweavers": fastAttack.skyweavers,
  "Harlequin Wraithlord": heavySupport.harlequinWraithlord,
  "Voidweaver": heavySupport.voidweaver,
  "Starweaver": dedicatedTransport.starweaver,
};

/** Slot → unit names map — same as units.json "slot_to_units" field. */
export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Great Harlequin"
  ],
  "Troops": [
    "Troupe"
  ],
  "Elites": [
    "Death Jester",
    "Shadowseer",
    "Solitaire"
  ],
  "Fast Attack": [
    "Skyweavers"
  ],
  "Heavy Support": [
    "Harlequin Wraithlord",
    "Voidweaver"
  ],
  "Dedicated Transport": [
    "Starweaver"
  ],
  "Fortifications": [],
  "Flyers": []
};

export const faction = "Harlequins";
