/**
 * legio_titanicus - unit index.
 *
 * Each unit is a PURE JSON file next to this one, so the codex tooling can rewrite it from the
 * sheets without touching any TypeScript. This is the only .ts in the folder: it imports them
 * and exports `faction`, `slot_to_units` and `units` exactly as the regular factions do.
 * Everything that is not a unit (armory, daemonkin, ...) is in ../supplement.json.
 *
 * Generated by scripts/convert_supplement_to_folders.cjs. To add a unit, add its .json and one line here.
 */

import type { Unit } from '../../../../src/types/data';

import hq_secutarii_axiarch from './hq/secutarii_axiarch.json';
import troops_secutarii_hoplites from './troops/secutarii_hoplites.json';
import troops_secutarii_peltasts from './troops/secutarii_peltasts.json';
import troops_tech_thralls from './troops/tech-thralls.json';
import dedicated_transport_macrocarid_explorator from './dedicated_transport/macrocarid_explorator.json';
import dedicated_transport_triaros_armored_conveyor from './dedicated_transport/triaros_armored_conveyor.json';
import troops_thallax_cohort from './troops/thallax_cohort.json';

export const faction = "Horus Heresy Forces of the Machine God";

export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Secutarii Axiarch"
  ],
  "Troops": [
    "Secutarii Hoplites",
    "Secutarii Peltasts",
    "Tech-thralls",
    "Thallax Cohort"
  ],
  "Elites": [],
  "Fast Attack": [],
  "Heavy Support": [],
  "Dedicated Transport": [
    "Macrocarid Explorator",
    "Triaros Armored Conveyor"
  ],
  "Fortifications": [],
  "Flyers": []
};

/** All units keyed by name. */
export const units: Record<string, Unit> = {
  "Secutarii Axiarch": hq_secutarii_axiarch as Unit,
  "Secutarii Hoplites": troops_secutarii_hoplites as Unit,
  "Secutarii Peltasts": troops_secutarii_peltasts as Unit,
  "Tech-thralls": troops_tech_thralls as Unit,
  "Macrocarid Explorator": dedicated_transport_macrocarid_explorator as Unit,
  "Triaros Armored Conveyor": dedicated_transport_triaros_armored_conveyor as Unit,
  "Thallax Cohort": troops_thallax_cohort as Unit,
};
