/**
 * chaos_space_marines - unit index.
 *
 * Each unit is a PURE JSON file next to this one, so the codex tooling can rewrite it from the
 * sheets without touching any TypeScript. This is the only .ts in the folder: it imports them
 * and exports `faction`, `slot_to_units` and `units` exactly as the old per-slot indexes did.
 *
 * Generated by scripts/convert_units_to_json.cjs. To add a unit, add its .json and one line here.
 */

import type { Unit } from '../../../../src/types/data';

import hq_adept_of_possession from './hq/adept_of_possession.json';
import hq_chaos_lieutenant from './hq/chaos_lieutenant.json';
import hq_chaos_sorcerer from './hq/chaos_sorcerer.json';
import hq_dark_apostle from './hq/dark_apostle.json';
import hq_daemon_prince from './hq/daemon_prince.json';
import hq_infernal_acolyte from './hq/infernal_acolyte.json';
import hq_lord_discordant from './hq/lord_discordant.json';
import hq_warpsmith from './hq/warpsmith.json';
import troops_accursed_cultists from './troops/accursed_cultists.json';
import troops_chaos_space_marines from './troops/chaos_space_marines.json';
import troops_cultists from './troops/cultists.json';
import troops_jakhals from './troops/jakhals.json';
import troops_mutants from './troops/mutants.json';
import troops_poxwalkers from './troops/poxwalkers.json';
import troops_traitor_guard from './troops/traitor_guard.json';
import troops_tzaangors from './troops/tzaangors.json';
import elites_big_mutants from './elites/big_mutants.json';
import elites_blightlord_terminators from './elites/blightlord_terminators.json';
import elites_chaos_terminators from './elites/chaos_terminators.json';
import elites_chosen from './elites/chosen.json';
import elites_cultist_firebrand from './elites/cultist_firebrand.json';
import elites_dark_commune from './elites/dark_commune.json';
import elites_deathshroud_terminators from './elites/deathshroud_terminators.json';
import elites_eightbound from './elites/eightbound.json';
import elites_foetid_virion from './elites/foetid_virion.json';
import elites_flawless_blades from './elites/flawless_blades.json';
import elites_helbrute from './elites/helbrute.json';
import elites_khorne_berzerkers from './elites/khorne_berzerkers.json';
import elites_legionnaires from './elites/legionnaires.json';
import elites_master_of_execution from './elites/master_of_execution.json';
import elites_mutilator from './elites/mutilator.json';
import elites_noise_marines from './elites/noise_marines.json';
import elites_plague_marines from './elites/plague_marines.json';
import elites_possessed from './elites/possessed.json';
import elites_red_butcher_terminators from './elites/red_butcher_terminators.json';
import elites_rubric_marines from './elites/rubric_marines.json';
import elites_scarab_occult_terminators from './elites/scarab_occult_terminators.json';
import elites_sekhetar_robots from './elites/sekhetar_robots.json';
import elites_slaughterbound from './elites/slaughterbound.json';
import elites_tzaangor_shaman from './elites/tzaangor_shaman.json';
import elites_war_dog from './elites/war_dog.json';
import fast_attack_chaos_bikers from './fast_attack/chaos_bikers.json';
import fast_attack_chaos_spawn from './fast_attack/chaos_spawn.json';
import fast_attack_foetid_bloat_drone from './fast_attack/foetid_bloat-drone.json';
import fast_attack_greater_blight_drone from './fast_attack/greater_blight_drone.json';
import fast_attack_juggernaut_hellriders from './fast_attack/juggernaut_hellriders.json';
import fast_attack_myphitic_blight_hauler from './fast_attack/myphitic_blight-hauler.json';
import fast_attack_raptors from './fast_attack/raptors.json';
import fast_attack_tzaangor_enlightened from './fast_attack/tzaangor_enlightened.json';
import fast_attack_venomcrawler from './fast_attack/venomcrawler.json';
import fast_attack_warptalons from './fast_attack/warptalons.json';
import heavy_support_blood_slaughterer from './heavy_support/blood_slaughterer.json';
import heavy_support_chaos_land_raider from './heavy_support/chaos_land_raider.json';
import heavy_support_chaos_predator from './heavy_support/chaos_predator.json';
import heavy_support_chaos_vindicator from './heavy_support/chaos_vindicator.json';
import heavy_support_chaos_decimator from './heavy_support/chaos_decimator.json';
import heavy_support_defiler from './heavy_support/defiler.json';
import heavy_support_forgefiend from './heavy_support/forgefiend.json';
import heavy_support_havocs from './heavy_support/havocs.json';
import heavy_support_maulerfiend from './heavy_support/maulerfiend.json';
import heavy_support_obliterator from './heavy_support/obliterator.json';
import heavy_support_plagueburst_crawler from './heavy_support/plagueburst_crawler.json';
import dedicated_transport_chaos_rhino from './dedicated_transport/chaos_rhino.json';
import dedicated_transport_dreadclaw_drop_pod from './dedicated_transport/dreadclaw_drop_pod.json';
import fortifications_miasmic_malignifier from './fortifications/miasmic_malignifier.json';
import fortifications_noctilith_crown from './fortifications/noctilith_crown.json';
import flyers_heldrake from './flyers/heldrake.json';
import lords_of_war_lord_of_skulls from './lords_of_war/lord_of_skulls.json';
import lords_of_war_knight_desecrator from './lords_of_war/knight_desecrator.json';
import lords_of_war_knight_rampager from './lords_of_war/knight_rampager.json';
import lords_of_war_chaos_spartan from './lords_of_war/chaos_spartan.json';
import lords_of_war_chaos_fellblade from './lords_of_war/chaos_fellblade.json';
import lords_of_war_chaos_warhound from './lords_of_war/chaos_warhound.json';

export const faction = "Chaos Space Marines";

export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Adept of Possession",
    "Chaos Lieutenant",
    "Chaos Sorcerer",
    "Dark Apostle",
    "Daemon Prince",
    "Infernal Acolyte",
    "Lord Discordant",
    "Warpsmith"
  ],
  "Troops": [
    "Accursed Cultists",
    "Chaos Space Marines",
    "Cultists",
    "Jakhals",
    "Mutants",
    "Poxwalkers",
    "Traitor Guard",
    "Tzaangors"
  ],
  "Elites": [
    "Big Mutants",
    "Blightlord Terminators",
    "Chaos Terminators",
    "Chosen",
    "Cultist Firebrand",
    "Dark Commune",
    "Deathshroud Terminators",
    "Eightbound",
    "Foetid Virion",
    "Flawless Blades",
    "Helbrute",
    "Khorne Berzerkers",
    "Legionnaires",
    "Master of Execution",
    "Mutilator",
    "Noise Marines",
    "Plague Marines",
    "Possessed",
    "Red Butcher Terminators",
    "Rubric Marines",
    "Scarab Occult Terminators",
    "Sekhetar Robots",
    "Slaughterbound",
    "Tzaangor Shaman",
    "War Dog"
  ],
  "Fast Attack": [
    "Greater Blight Drone",
    "Chaos Bikers",
    "Chaos Spawn",
    "Foetid Bloat-Drone",
    "Juggernaut Hellriders",
    "Myphitic Blight-Hauler",
    "Raptors",
    "Tzaangor Enlightened",
    "Venomcrawler",
    "Warptalons"
  ],
  "Heavy Support": [
    "Blood Slaughterer",
    "Chaos Land Raider",
    "Chaos Predator",
    "Chaos Vindicator",
    "Chaos Decimator",
    "Defiler",
    "Forgefiend",
    "Havocs",
    "Maulerfiend",
    "Obliterator",
    "Plagueburst Crawler"
  ],
  "Dedicated Transport": [
    "Chaos Rhino",
    "Dreadclaw Drop Pod"
  ],
  "Fortifications": [
    "Miasmic Malignifier",
    "Noctilith Crown"
  ],
  "Flyers": [
    "Heldrake"
  ],
  "Lords of War": [
    "Lord of Skulls",
    "Knight Desecrator",
    "Knight Rampager",
    "Chaos Spartan",
    "Chaos Fellblade",
    "Chaos Warhound"
  ]
};

/** All units keyed by name. */
export const units: Record<string, Unit> = {
  "Adept of Possession": hq_adept_of_possession as Unit,
  "Chaos Lieutenant": hq_chaos_lieutenant as Unit,
  "Chaos Sorcerer": hq_chaos_sorcerer as Unit,
  "Dark Apostle": hq_dark_apostle as Unit,
  "Daemon Prince": hq_daemon_prince as Unit,
  "Infernal Acolyte": hq_infernal_acolyte as Unit,
  "Lord Discordant": hq_lord_discordant as Unit,
  "Warpsmith": hq_warpsmith as Unit,
  "Accursed Cultists": troops_accursed_cultists as Unit,
  "Chaos Space Marines": troops_chaos_space_marines as Unit,
  "Cultists": troops_cultists as Unit,
  "Jakhals": troops_jakhals as Unit,
  "Mutants": troops_mutants as Unit,
  "Poxwalkers": troops_poxwalkers as Unit,
  "Traitor Guard": troops_traitor_guard as Unit,
  "Tzaangors": troops_tzaangors as Unit,
  "Big Mutants": elites_big_mutants as Unit,
  "Blightlord Terminators": elites_blightlord_terminators as Unit,
  "Chaos Terminators": elites_chaos_terminators as Unit,
  "Chosen": elites_chosen as Unit,
  "Cultist Firebrand": elites_cultist_firebrand as Unit,
  "Dark Commune": elites_dark_commune as Unit,
  "Deathshroud Terminators": elites_deathshroud_terminators as Unit,
  "Eightbound": elites_eightbound as Unit,
  "Foetid Virion": elites_foetid_virion as Unit,
  "Flawless Blades": elites_flawless_blades as Unit,
  "Helbrute": elites_helbrute as Unit,
  "Khorne Berzerkers": elites_khorne_berzerkers as Unit,
  "Legionnaires": elites_legionnaires as Unit,
  "Master of Execution": elites_master_of_execution as Unit,
  "Mutilator": elites_mutilator as Unit,
  "Noise Marines": elites_noise_marines as Unit,
  "Plague Marines": elites_plague_marines as Unit,
  "Possessed": elites_possessed as Unit,
  "Red Butcher Terminators": elites_red_butcher_terminators as Unit,
  "Rubric Marines": elites_rubric_marines as Unit,
  "Scarab Occult Terminators": elites_scarab_occult_terminators as Unit,
  "Sekhetar Robots": elites_sekhetar_robots as Unit,
  "Slaughterbound": elites_slaughterbound as Unit,
  "Tzaangor Shaman": elites_tzaangor_shaman as Unit,
  "War Dog": elites_war_dog as Unit,
  "Chaos Bikers": fast_attack_chaos_bikers as Unit,
  "Chaos Spawn": fast_attack_chaos_spawn as Unit,
  "Foetid Bloat-Drone": fast_attack_foetid_bloat_drone as Unit,
  "Greater Blight Drone": fast_attack_greater_blight_drone as Unit,
  "Juggernaut Hellriders": fast_attack_juggernaut_hellriders as Unit,
  "Myphitic Blight-Hauler": fast_attack_myphitic_blight_hauler as Unit,
  "Raptors": fast_attack_raptors as Unit,
  "Tzaangor Enlightened": fast_attack_tzaangor_enlightened as Unit,
  "Venomcrawler": fast_attack_venomcrawler as Unit,
  "Warptalons": fast_attack_warptalons as Unit,
  "Blood Slaughterer": heavy_support_blood_slaughterer as Unit,
  "Chaos Land Raider": heavy_support_chaos_land_raider as Unit,
  "Chaos Predator": heavy_support_chaos_predator as Unit,
  "Chaos Vindicator": heavy_support_chaos_vindicator as Unit,
  "Chaos Decimator": heavy_support_chaos_decimator as Unit,
  "Defiler": heavy_support_defiler as Unit,
  "Forgefiend": heavy_support_forgefiend as Unit,
  "Havocs": heavy_support_havocs as Unit,
  "Maulerfiend": heavy_support_maulerfiend as Unit,
  "Obliterator": heavy_support_obliterator as Unit,
  "Plagueburst Crawler": heavy_support_plagueburst_crawler as Unit,
  "Chaos Rhino": dedicated_transport_chaos_rhino as Unit,
  "Dreadclaw Drop Pod": dedicated_transport_dreadclaw_drop_pod as Unit,
  "Miasmic Malignifier": fortifications_miasmic_malignifier as Unit,
  "Noctilith Crown": fortifications_noctilith_crown as Unit,
  "Heldrake": flyers_heldrake as Unit,
  "Lord of Skulls": lords_of_war_lord_of_skulls as Unit,
  "Knight Desecrator": lords_of_war_knight_desecrator as Unit,
  "Knight Rampager": lords_of_war_knight_rampager as Unit,
  "Chaos Spartan": lords_of_war_chaos_spartan as Unit,
  "Chaos Fellblade": lords_of_war_chaos_fellblade as Unit,
  "Chaos Warhound": lords_of_war_chaos_warhound as Unit,
};
