/**
 * Chaos Space Marines — unit index
 * Auto-generated by _migrate_units_to_ts.cjs
 * Each unit lives in its own file under units/<slot>/<name>.ts
 * Add SOURCE comments and engine status notes when auditing each unit.
 */

import * as dedicatedTransport from './dedicated_transport/index';
import * as elites from './elites/index';
import * as fastAttack from './fast_attack/index';
import * as flyers from './flyers/index';
import * as fortifications from './fortifications/index';
import * as heavySupport from './heavy_support/index';
import * as hq from './hq/index';
import * as lordsOfWar from './lords_of_war/index';
import * as troops from './troops/index';

/** All units keyed by name — drop-in replacement for units.json "units" field. */
export const units: Record<string, import('../../../../src/types/data').Unit> = {
  "Adept of Possession": hq.adeptOfPossession,
  "Chaos Lieutenant": hq.chaosLieutenant,
  "Chaos Sorcerer": hq.chaosSorcerer,
  "Dark Apostle": hq.darkApostle,
  "Daemon Prince": hq.daemonPrince,
  "Infernal Acolyte": hq.infernalAcolyte,
  "Lord Discordant": hq.lordDiscordant,
  "Warpsmith": hq.warpsmith,
  "Accursed Cultists": troops.accursedCultists,
  "Chaos Space Marines": troops.chaosSpaceMarines,
  "Cultists": troops.cultists,
  "Jakhals": troops.jakhals,
  "Mutants": troops.mutants,
  "Poxwalkers": troops.poxwalkers,
  "Traitor Guard": troops.traitorGuard,
  "Tzaangors": troops.tzaangors,
  "Big Mutants": elites.bigMutants,
  "Blightlord Terminators": elites.blightlordTerminators,
  "Chaos Terminators": elites.chaosTerminators,
  "Chosen": elites.chosen,
  "Cultist Firebrand": elites.cultistFirebrand,
  "Dark Commune": elites.darkCommune,
  "Deathshroud Terminators": elites.deathshroudTerminators,
  "Eightbound": elites.eightbound,
  "Exalted Plague Champion": elites.exaltedPlagueChampion,
  "Flawless Blades": elites.flawlessBlades,
  "Helbrute": elites.helbrute,
  "Khorne Berzerkers": elites.khorneBerzerkers,
  "Legionnaires": elites.legionnaires,
  "Master of Execution": elites.masterOfExecution,
  "Noise Marines": elites.noiseMarines,
  "Plague Marines": elites.plagueMarines,
  "Possessed": elites.possessed,
  "Red Butcher Terminators": elites.redButcherTerminators,
  "Rubric Marines": elites.rubricMarines,
  "Scarab Occult Terminators": elites.scarabOccultTerminators,
  "Sekhetar Robots": elites.sekhetarRobots,
  "Tzaangor Shaman": elites.tzaangorShaman,
  "War Dog": elites.warDog,
  "Chaos Bikers": fastAttack.chaosBikers,
  "Chaos Spawn": fastAttack.chaosSpawn,
  "Foetid Bloat-Drone": fastAttack.foetidBloatDrone,
  "Juggernaut Hellriders": fastAttack.juggernautHellriders,
  "Myphitic Blight-Hauler": fastAttack.myphiticBlightHauler,
  "Raptors": fastAttack.raptors,
  "Tzaangor Enlightened": fastAttack.tzaangorEnlightened,
  "Venomcrawler": fastAttack.venomcrawler,
  "Warptalons": fastAttack.warptalons,
  "Chaos Land Raider": heavySupport.chaosLandRaider,
  "Chaos Predator": heavySupport.chaosPredator,
  "Chaos Vindicator": heavySupport.chaosVindicator,
  "Defiler": heavySupport.defiler,
  "Forgefiend": heavySupport.forgefiend,
  "Havocs": heavySupport.havocs,
  "Maulerfiend": heavySupport.maulerfiend,
  "Obliterator": heavySupport.obliterator,
  "Plagueburst Crawler": heavySupport.plagueburstCrawler,
  "Chaos Rhino": dedicatedTransport.chaosRhino,
  "Dreadclaw Drop Pod": dedicatedTransport.dreadclawDropPod,
  "Miasmic Malignifier": fortifications.miasmicMalignifier,
  "Noctilith Crown": fortifications.noctilithCrown,
  "Heldrake": flyers.heldrake,
  "Lord of Skulls": lordsOfWar.lordOfSkulls,
  "Knight Desecrator": lordsOfWar.knightDesecrator,
  "Knight Rampager": lordsOfWar.knightRampager,
  "Chaos Spartan": lordsOfWar.chaosSpartan,
  "Chaos Fellblade": lordsOfWar.chaosFellblade,
  "Chaos Warhound": lordsOfWar.chaosWarhound,
};

/** Slot → unit names map — same as units.json "slot_to_units" field. */
export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Adept of Possession",
    "Chaos Lieutenant",
    "Chaos Sorcerer",
    "Dark Apostle",
    "Daemon Prince",
    "Infernal Acolyte",
    "Lord Discordant",
    "Warpsmith"
  ],
  "Troops": [
    "Accursed Cultists",
    "Chaos Space Marines",
    "Cultists",
    "Jakhals",
    "Mutants",
    "Poxwalkers",
    "Traitor Guard",
    "Tzaangors"
  ],
  "Elites": [
    "Big Mutants",
    "Blightlord Terminators",
    "Chaos Terminators",
    "Chosen",
    "Cultist Firebrand",
    "Dark Commune",
    "Deathshroud Terminators",
    "Eightbound",
    "Exalted Plague Champion",
    "Flawless Blades",
    "Helbrute",
    "Khorne Berzerkers",
    "Legionnaires",
    "Master of Execution",
    "Noise Marines",
    "Plague Marines",
    "Possessed",
    "Red Butcher Terminators",
    "Rubric Marines",
    "Scarab Occult Terminators",
    "Sekhetar Robots",
    "Tzaangor Shaman",
    "War Dog"
  ],
  "Fast Attack": [
    "Chaos Bikers",
    "Chaos Spawn",
    "Foetid Bloat-Drone",
    "Juggernaut Hellriders",
    "Myphitic Blight-Hauler",
    "Raptors",
    "Tzaangor Enlightened",
    "Venomcrawler",
    "Warptalons"
  ],
  "Heavy Support": [
    "Chaos Land Raider",
    "Chaos Predator",
    "Chaos Vindicator",
    "Defiler",
    "Forgefiend",
    "Havocs",
    "Maulerfiend",
    "Obliterator",
    "Plagueburst Crawler"
  ],
  "Dedicated Transport": [
    "Chaos Rhino",
    "Dreadclaw Drop Pod"
  ],
  "Fortifications": [
    "Miasmic Malignifier",
    "Noctilith Crown"
  ],
  "Flyers": [
    "Heldrake"
  ],
  "Lords of War": [
    "Lord of Skulls",
    "Knight Desecrator",
    "Knight Rampager",
    "Chaos Spartan",
    "Chaos Fellblade",
    "Chaos Warhound"
  ]
};

export const faction = "Chaos Space Marines";
