/**
 * adeptus_mechanicus - unit index.
 *
 * Each unit is a PURE JSON file next to this one, so the codex tooling can rewrite it from the
 * sheets without touching any TypeScript. This is the only .ts in the folder: it imports them
 * and exports `faction`, `slot_to_units` and `units` exactly as the old per-slot indexes did.
 *
 * Generated by scripts/convert_units_to_json.cjs. To add a unit, add its .json and one line here.
 */

import type { Unit } from '../../../../src/types/data';

import hq_magos from './hq/magos.json';
import hq_skitarii_marshal from './hq/skitarii_marshal.json';
import troops_skitarii_rangers from './troops/skitarii_rangers.json';
import troops_skitarii_vanguard from './troops/skitarii_vanguard.json';
import elites_corpuscarii_electro_priests from './elites/corpuscarii_electro-priests.json';
import elites_fulgurite_electro_priests from './elites/fulgurite_electro-priests.json';
import elites_kataphron_breachers from './elites/kataphron_breachers.json';
import elites_kataphron_destroyers from './elites/kataphron_destroyers.json';
import elites_servitors from './elites/servitors.json';
import elites_sicaran_infiltrators from './elites/sicaran_infiltrators.json';
import elites_sicaran_ruststalkers from './elites/sicaran_ruststalkers.json';
import elites_sydonian_skatros from './elites/sydonian_skatros.json';
import elites_tech_priest from './elites/tech-priest.json';
import fast_attack_pteraxii_skystalkers from './fast_attack/pteraxii_skystalkers.json';
import fast_attack_pteraxii_sterylizors from './fast_attack/pteraxii_sterylizors.json';
import fast_attack_serberys_raiders from './fast_attack/serberys_raiders.json';
import fast_attack_serberys_sulphurhounds from './fast_attack/serberys_sulphurhounds.json';
import fast_attack_sydonian_dragoons from './fast_attack/sydonian_dragoons.json';
import heavy_support_ironstrider_ballistarii from './heavy_support/ironstrider_ballistarii.json';
import heavy_support_kastelan_robots from './heavy_support/kastelan_robots.json';
import heavy_support_onager_dunecrawler from './heavy_support/onager_dunecrawler.json';
import heavy_support_skorpius_disintegrator from './heavy_support/skorpius_disintegrator.json';
import dedicated_transport_skorpius_dunerider from './dedicated_transport/skorpius_dunerider.json';
import dedicated_transport_termite from './dedicated_transport/termite.json';
import flyers_archaeopter from './flyers/archaeopter.json';

export const faction = "Adeptus Mechanicus";

export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Magos",
    "Skitarii Marshal"
  ],
  "Troops": [
    "Skitarii Rangers",
    "Skitarii Vanguard",
  ],
  "Elites": [
    "Corpuscarii Electro-Priests",
    "Fulgurite Electro-Priests",
    "Kataphron Breachers",
    "Kataphron Destroyers",
    "Servitors",
    "Sicaran Infiltrators",
    "Sicaran Ruststalkers",
    "Sydonian Skatros",
    "Tech-Priest"
  ],
  "Fast Attack": [
    "Pteraxii Skystalkers",
    "Pteraxii Sterylizors",
    "Serberys Raiders",
    "Serberys Sulphurhounds",
    "Sydonian Dragoons"
  ],
  "Heavy Support": [
    "Ironstrider Ballistarii",
    "Kastelan Robots",
    "Onager Dunecrawler",
    "Skorpius Disintegrator"
  ],
  "Dedicated Transport": [
    "Skorpius Dunerider",
    "Termite"
  ],
  "Fortifications": [],
  "Flyers": [
    "Archaeopter"
  ]
};

/** All units keyed by name. */
export const units: Record<string, Unit> = {
  "Magos": hq_magos as Unit,
  "Skitarii Marshal": hq_skitarii_marshal as Unit,
  "Skitarii Rangers": troops_skitarii_rangers as Unit,
  "Skitarii Vanguard": troops_skitarii_vanguard as Unit,
  "Corpuscarii Electro-Priests": elites_corpuscarii_electro_priests as Unit,
  "Fulgurite Electro-Priests": elites_fulgurite_electro_priests as Unit,
  "Kataphron Breachers": elites_kataphron_breachers as Unit,
  "Kataphron Destroyers": elites_kataphron_destroyers as Unit,
  "Servitors": elites_servitors as Unit,
  "Sicaran Infiltrators": elites_sicaran_infiltrators as Unit,
  "Sicaran Ruststalkers": elites_sicaran_ruststalkers as Unit,
  "Sydonian Skatros": elites_sydonian_skatros as Unit,
  "Tech-Priest": elites_tech_priest as Unit,
  "Pteraxii Skystalkers": fast_attack_pteraxii_skystalkers as Unit,
  "Pteraxii Sterylizors": fast_attack_pteraxii_sterylizors as Unit,
  "Serberys Raiders": fast_attack_serberys_raiders as Unit,
  "Serberys Sulphurhounds": fast_attack_serberys_sulphurhounds as Unit,
  "Sydonian Dragoons": fast_attack_sydonian_dragoons as Unit,
  "Ironstrider Ballistarii": heavy_support_ironstrider_ballistarii as Unit,
  "Kastelan Robots": heavy_support_kastelan_robots as Unit,
  "Onager Dunecrawler": heavy_support_onager_dunecrawler as Unit,
  "Skorpius Disintegrator": heavy_support_skorpius_disintegrator as Unit,
  "Skorpius Dunerider": dedicated_transport_skorpius_dunerider as Unit,
  "Termite": dedicated_transport_termite as Unit,
  "Archaeopter": flyers_archaeopter as Unit,
};
