/**
 * Adeptus Mechanicus — unit index
 * Auto-generated by _migrate_units_to_ts.cjs
 * Each unit lives in its own file under units/<slot>/<name>.ts
 * Add SOURCE comments and engine status notes when auditing each unit.
 */

import * as dedicatedTransport from './dedicated_transport/index';
import * as elites from './elites/index';
import * as fastAttack from './fast_attack/index';
import * as flyers from './flyers/index';
import * as heavySupport from './heavy_support/index';
import * as hq from './hq/index';
import * as troops from './troops/index';

/** All units keyed by name — drop-in replacement for units.json "units" field. */
export const units: Record<string, import('../../../../src/types/data').Unit> = {
  "Magos": hq.magos,
  "Skitarii Marshal": hq.skitariiMarshal,
  "Skitarii Rangers": troops.skitariiRangers,
  "Skitarii Vanguard": troops.skitariiVanguard,
  "Tech Thralls": troops.techThralls,
  "Corpuscarii Electro-Priests": elites.corpuscariiElectroPriests,
  "Fulgurite Electro-Priests": elites.fulguriteElectroPriests,
  "Kataphron Breachers": elites.kataphronBreachers,
  "Kataphron Destroyers": elites.kataphronDestroyers,
  "Secutarii Hoplites": elites.secutariiHoplites,
  "Secutarii Peltasts": elites.secutariiPeltasts,
  "Servitors": elites.servitors,
  "Sicaran Infiltrators": elites.sicaranInfiltrators,
  "Sicaran Ruststalkers": elites.sicaranRuststalkers,
  "Sydonian Skatros": elites.sydonianSkatros,
  "Tech-Priest": elites.techPriest,
  "Pteraxii Skystalkers": fastAttack.pteraxiiSkystalkers,
  "Pteraxii Sterylizors": fastAttack.pteraxiiSterylizors,
  "Serberys Raiders": fastAttack.serberysRaiders,
  "Serberys Sulphurhounds": fastAttack.serberysSulphurhounds,
  "Sydonian Dragoons": fastAttack.sydonianDragoons,
  "Ironstrider Ballistarii": heavySupport.ironstriderBallistarii,
  "Kastelan Robots": heavySupport.kastelanRobots,
  "Macrocarid Explorator": heavySupport.macrocaridExplorator,
  "Onager Dunecrawler": heavySupport.onagerDunecrawler,
  "Skorpius Disintegrator": heavySupport.skorpiusDisintegrator,
  "Skorpius Dunerider": dedicatedTransport.skorpiusDunerider,
  "Termite": dedicatedTransport.termite,
  "Archaeopter": flyers.archaeopter,
};

/** Slot → unit names map — same as units.json "slot_to_units" field. */
export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Magos",
    "Skitarii Marshal"
  ],
  "Troops": [
    "Skitarii Rangers",
    "Skitarii Vanguard",
    "Tech Thralls"
  ],
  "Elites": [
    "Corpuscarii Electro-Priests",
    "Fulgurite Electro-Priests",
    "Kataphron Breachers",
    "Kataphron Destroyers",
    "Secutarii Hoplites",
    "Secutarii Peltasts",
    "Servitors",
    "Sicaran Infiltrators",
    "Sicaran Ruststalkers",
    "Sydonian Skatros",
    "Tech-Priest"
  ],
  "Fast Attack": [
    "Pteraxii Skystalkers",
    "Pteraxii Sterylizors",
    "Serberys Raiders",
    "Serberys Sulphurhounds",
    "Sydonian Dragoons"
  ],
  "Heavy Support": [
    "Ironstrider Ballistarii",
    "Kastelan Robots",
    "Macrocarid Explorator",
    "Onager Dunecrawler",
    "Skorpius Disintegrator"
  ],
  "Dedicated Transport": [
    "Skorpius Dunerider",
    "Termite"
  ],
  "Fortifications": [],
  "Flyers": [
    "Archaeopter"
  ]
};

export const faction = "Adeptus Mechanicus";
