/**
 * grey_knights - unit index.
 *
 * Each unit is a PURE JSON file next to this one, so the codex tooling can rewrite it from the
 * sheets without touching any TypeScript. This is the only .ts in the folder: it imports them
 * and exports `faction`, `slot_to_units` and `units` exactly as the old per-slot indexes did.
 *
 * Generated by scripts/convert_units_to_json.cjs. To add a unit, add its .json and one line here.
 */

import type { Unit } from '../../../../src/types/data';

import hq_brotherhood_champion from './hq/brotherhood_champion.json';
import hq_captain from './hq/captain.json';
import hq_captain_in_nemesis_armor from './hq/captain_in_nemesis_armor.json';
import hq_chaplain from './hq/chaplain.json';
import hq_librarian from './hq/librarian.json';
import troops_strike_squad from './troops/strike_squad.json';
import troops_terminator_squad from './troops/terminator_squad.json';
import elites_ancient from './elites/ancient.json';
import elites_apothecary from './elites/apothecary.json';
import elites_dreadnought from './elites/dreadnought.json';
import elites_ghost_terminator_squad from './elites/ghost_terminator_squad.json';
import elites_paladin_squad from './elites/paladin_squad.json';
import elites_purifier_squad from './elites/purifier_squad.json';
import fast_attack_interceptor_squad from './fast_attack/interceptor_squad.json';
import heavy_support_land_raider from './heavy_support/land_raider.json';
import heavy_support_land_raider_crusader from './heavy_support/land_raider_crusader.json';
import heavy_support_land_raider_redeemer from './heavy_support/land_raider_redeemer.json';
import heavy_support_nemesis_dreadknight from './heavy_support/nemesis_dreadknight.json';
import heavy_support_purgator_squad from './heavy_support/purgator_squad.json';
import dedicated_transport_razorback from './dedicated_transport/razorback.json';
import dedicated_transport_rhino from './dedicated_transport/rhino.json';
import flyers_stormraven_gunship from './flyers/stormraven_gunship.json';

export const faction = "Grey Knights";

export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Brotherhood Champion",
    "Captain",
    "Captain in Nemesis Armor",
    "Chaplain",
    "Librarian"
  ],
  "Troops": [
    "Strike Squad",
    "Terminator Squad"
  ],
  "Elites": [
    "Ancient",
    "Apothecary",
    "Dreadnought",
    "Ghost Terminator Squad",
    "Paladin Squad",
    "Purifier Squad"
  ],
  "Fast Attack": [
    "Interceptor Squad"
  ],
  "Heavy Support": [
    "Land Raider",
    "Land Raider Crusader",
    "Land Raider Redeemer",
    "Nemesis Dreadknight",
    "Purgator Squad"
  ],
  "Dedicated Transport": [
    "Razorback",
    "Rhino"
  ],
  "Fortifications": [],
  "Flyers": [
    "Stormraven Gunship"
  ]
};

/** All units keyed by name. */
export const units: Record<string, Unit> = {
  "Brotherhood Champion": hq_brotherhood_champion as Unit,
  "Captain": hq_captain as Unit,
  "Captain in Nemesis Armor": hq_captain_in_nemesis_armor as Unit,
  "Chaplain": hq_chaplain as Unit,
  "Librarian": hq_librarian as Unit,
  "Strike Squad": troops_strike_squad as Unit,
  "Terminator Squad": troops_terminator_squad as Unit,
  "Ancient": elites_ancient as Unit,
  "Apothecary": elites_apothecary as Unit,
  "Dreadnought": elites_dreadnought as Unit,
  "Ghost Terminator Squad": elites_ghost_terminator_squad as Unit,
  "Paladin Squad": elites_paladin_squad as Unit,
  "Purifier Squad": elites_purifier_squad as Unit,
  "Interceptor Squad": fast_attack_interceptor_squad as Unit,
  "Land Raider": heavy_support_land_raider as Unit,
  "Land Raider Crusader": heavy_support_land_raider_crusader as Unit,
  "Land Raider Redeemer": heavy_support_land_raider_redeemer as Unit,
  "Nemesis Dreadknight": heavy_support_nemesis_dreadknight as Unit,
  "Purgator Squad": heavy_support_purgator_squad as Unit,
  "Razorback": dedicated_transport_razorback as Unit,
  "Rhino": dedicated_transport_rhino as Unit,
  "Stormraven Gunship": flyers_stormraven_gunship as Unit,
};
