/**
 * Grey Knights — unit index
 * Auto-generated by _migrate_units_to_ts.cjs
 * Each unit lives in its own file under units/<slot>/<name>.ts
 * Add SOURCE comments and engine status notes when auditing each unit.
 */

import * as dedicatedTransport from './dedicated_transport/index';
import * as elites from './elites/index';
import * as fastAttack from './fast_attack/index';
import * as flyers from './flyers/index';
import * as heavySupport from './heavy_support/index';
import * as hq from './hq/index';
import * as troops from './troops/index';

/** All units keyed by name — drop-in replacement for units.json "units" field. */
export const units: Record<string, import('../../../../src/types/data').Unit> = {
  "Brotherhood Champion": hq.brotherhoodChampion,
  "Captain": hq.captain,
  "Captain in Nemesis Armor": hq.captainInNemesisArmor,
  "Chaplain": hq.chaplain,
  "Librarian": hq.librarian,
  "Strike Squad": troops.strikeSquad,
  "Terminator Squad": troops.terminatorSquad,
  "Ancient": elites.ancient,
  "Apothecary": elites.apothecary,
  "Dreadnought": elites.dreadnought,
  "Ghost Terminator Squad": elites.ghostTerminatorSquad,
  "Paladin Squad": elites.paladinSquad,
  "Purifier Squad": elites.purifierSquad,
  "Interceptor Squad": fastAttack.interceptorSquad,
  "Land Raider": heavySupport.landRaider,
  "Land Raider Crusader": heavySupport.landRaiderCrusader,
  "Land Raider Redeemer": heavySupport.landRaiderRedeemer,
  "Nemesis Dreadknight": heavySupport.nemesisDreadknight,
  "Purgator Squad": heavySupport.purgatorSquad,
  "Razorback": dedicatedTransport.razorback,
  "Rhino": dedicatedTransport.rhino,
  "Stormraven Gunship": flyers.stormravenGunship,
};

/** Slot → unit names map — same as units.json "slot_to_units" field. */
export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Brotherhood Champion",
    "Captain",
    "Captain in Nemesis Armor",
    "Chaplain",
    "Librarian"
  ],
  "Troops": [
    "Strike Squad",
    "Terminator Squad"
  ],
  "Elites": [
    "Ancient",
    "Apothecary",
    "Dreadnought",
    "Ghost Terminator Squad",
    "Paladin Squad",
    "Purifier Squad"
  ],
  "Fast Attack": [
    "Interceptor Squad"
  ],
  "Heavy Support": [
    "Land Raider",
    "Land Raider Crusader",
    "Land Raider Redeemer",
    "Nemesis Dreadknight",
    "Purgator Squad"
  ],
  "Dedicated Transport": [
    "Razorback",
    "Rhino"
  ],
  "Fortifications": [],
  "Flyers": [
    "Stormraven Gunship"
  ]
};

export const faction = "Grey Knights";
