/**
 * space_marines - unit index.
 *
 * Each unit is a PURE JSON file next to this one, so the codex tooling can rewrite it from the
 * sheets without touching any TypeScript. This is the only .ts in the folder: it imports them
 * and exports `faction`, `slot_to_units` and `units` exactly as the old per-slot indexes did.
 *
 * Generated by scripts/convert_units_to_json.cjs. To add a unit, add its .json and one line here.
 */

import type { Unit } from '../../../../src/types/data';

import hq_captain_dreadnought from './hq/captain_dreadnought.json';
import hq_chaplain from './hq/chaplain.json';
import hq_chaplain_dreadnought from './hq/chaplain_dreadnought.json';
import hq_emperors_champion from './hq/emperors_champion.json';
import hq_librarian from './hq/librarian.json';
import hq_librarian_dreadnought from './hq/librarian_dreadnought.json';
import hq_lieutenant from './hq/lieutenant.json';
import troops_assault_intercessor_squad from './troops/assault_intercessor_squad.json';
import troops_blood_claws from './troops/blood_claws.json';
import troops_grey_hunters from './troops/grey_hunters.json';
import troops_heavy_intercessor_squad from './troops/heavy_intercessor_squad.json';
import troops_indomitus_crusader_squad from './troops/indomitus_crusader_squad.json';
import troops_infiltrator_squad from './troops/infiltrator_squad.json';
import troops_intercessor_squad from './troops/intercessor_squad.json';
import troops_scout_squad from './troops/scout_squad.json';
import troops_tactical_squad from './troops/tactical_squad.json';
import elites_aggressor_squad from './elites/aggressor_squad.json';
import elites_ancient from './elites/ancient.json';
import elites_armiger from './elites/armiger.json';
import elites_apothecary from './elites/apothecary.json';
import elites_company_champion from './elites/company_champion.json';
import elites_death_company from './elites/death_company.json';
import elites_deathwing_knights from './elites/deathwing_knights.json';
import elites_dreadnought from './elites/dreadnought.json';
import elites_honor_guard from './elites/honor_guard.json';
import elites_invictor_battlesuit from './elites/invictor_battlesuit.json';
import elites_ironclad_dreadnought from './elites/ironclad_dreadnought.json';
import elites_judicar from './elites/judicar.json';
import elites_kill_team_veterans from './elites/kill_team_veterans.json';
import elites_redemptor_dreadnought from './elites/redemptor_dreadnought.json';
import elites_techmarine from './elites/techmarine.json';
import elites_terminator_squad from './elites/terminator_squad.json';
import elites_wolf_scout_squad from './elites/wolf_scout_squad.json';
import elites_reiver_marines from './elites/reiver_marines.json';
import fast_attack_assault_squad from './fast_attack/assault_squad.json';
import fast_attack_bike_squad from './fast_attack/bike_squad.json';
import fast_attack_inceptor_squad from './fast_attack/inceptor_squad.json';
import fast_attack_infernus_squad from './fast_attack/infernus_squad.json';
import fast_attack_invader_quad from './fast_attack/invader_quad.json';
import fast_attack_land_speeder from './fast_attack/land_speeder.json';
import fast_attack_outrider_bikes from './fast_attack/outrider_bikes.json';
import fast_attack_ravenwing_black_knights from './fast_attack/ravenwing_black_knights.json';
import fast_attack_razorback_rikarius from './fast_attack/razorback_rikarius.json';
import fast_attack_storm_speeder from './fast_attack/storm_speeder.json';
import fast_attack_suppressor_squad from './fast_attack/suppressor_squad.json';
import fast_attack_wolf_companions from './fast_attack/wolf_companions.json';
import heavy_support_centurion_devastator_squad from './heavy_support/centurion_devastator_squad.json';
import heavy_support_desolation_squad from './heavy_support/desolation_squad.json';
import heavy_support_devastator_squad from './heavy_support/devastator_squad.json';
import heavy_support_eliminator_squad from './heavy_support/eliminator_squad.json';
import heavy_support_eradicator_squad from './heavy_support/eradicator_squad.json';
import heavy_support_firestrike_servo_turret from './heavy_support/firestrike_servo_turret.json';
import heavy_support_gladiator from './heavy_support/gladiator.json';
import heavy_support_hellblaster_squad from './heavy_support/hellblaster_squad.json';
import heavy_support_land_raider from './heavy_support/land_raider.json';
import heavy_support_land_raider_ares from './heavy_support/land_raider_ares.json';
import heavy_support_land_raider_crusader from './heavy_support/land_raider_crusader.json';
import heavy_support_land_raider_redeemer from './heavy_support/land_raider_redeemer.json';
import heavy_support_predator from './heavy_support/predator.json';
import heavy_support_repulsor from './heavy_support/repulsor.json';
import heavy_support_repulsor_executioner from './heavy_support/repulsor_executioner.json';
import heavy_support_thunderfire_cannon from './heavy_support/thunderfire_cannon.json';
import heavy_support_vindicator from './heavy_support/vindicator.json';
import heavy_support_whirlwind from './heavy_support/whirlwind.json';
import dedicated_transport_drop_pod from './dedicated_transport/drop_pod.json';
import dedicated_transport_impulsor from './dedicated_transport/impulsor.json';
import dedicated_transport_land_speeder_storm from './dedicated_transport/land_speeder_storm.json';
import dedicated_transport_razorback from './dedicated_transport/razorback.json';
import dedicated_transport_rhino from './dedicated_transport/rhino.json';
import fortifications_hammerfall_bunker from './fortifications/hammerfall_bunker.json';
import flyers_fire_raptor from './flyers/fire_raptor.json';
import flyers_nephilim_jetfighter from './flyers/nephilim_jetfighter.json';
import flyers_stormhawk_interceptor from './flyers/stormhawk_interceptor.json';
import flyers_stormraven_gunship from './flyers/stormraven_gunship.json';
import flyers_stormtalon_gunship from './flyers/stormtalon_gunship.json';
import lords_of_war_fellblade from './lords_of_war/fellblade.json';
import lords_of_war_spartan from './lords_of_war/spartan.json';
import lords_of_war_knight_castellan from './lords_of_war/knight_castellan.json';
import lords_of_war_knight_paladin from './lords_of_war/knight_paladin.json';
import lords_of_war_warhound from './lords_of_war/warhound.json';

export const faction = "Space Marines";

export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Captain Dreadnought",
    "Chaplain",
    "Chaplain Dreadnought",
    "Emperor's Champion",
    "Librarian",
    "Librarian Dreadnought",
    "Lieutenant"
  ],
  "Troops": [
    "Assault Intercessor Squad",
    "Blood Claws",
    "Grey Hunters",
    "Heavy Intercessor Squad",
    "Indomitus Crusader Squad",
    "Infiltrator Squad",
    "Intercessor Squad",
    "Scout Squad",
    "Tactical Squad"
  ],
  "Elites": [
    "Aggressor Squad",
    "Ancient",
    "Armiger",
    "Apothecary",
    "Company Champion",
    "Death Company",
    "Deathwing Knights",
    "Dreadnought",
    "Honor Guard",
    "Invictor Battlesuit",
    "Ironclad Dreadnought",
    "Judicar",
    "Kill Team Veterans",
    "Redemptor Dreadnought",
    "Reiver Marines",
    "Techmarine",
    "Terminator Squad",
    "Wolf Scout Squad"
  ],
  "Fast Attack": [
    "Assault Squad",
    "Bike Squad",
    "Inceptor Squad",
    "Infernus Squad",
    "Invader-Quad",
    "Land Speeder",
    "Outrider Bikes",
    "Ravenwing Black Knights",
    "Razorback Rikarius",
    "Storm Speeder",
    "Suppressor Squad",
    "Wolf Companions"
  ],
  "Heavy Support": [
    "Centurion Devastator Squad",
    "Desolation Squad",
    "Devastator Squad",
    "Eliminator Squad",
    "Eradicator Squad",
    "Firestrike Servo-turret",
    "Gladiator",
    "Hellblaster Squad",
    "Land Raider",
    "Land Raider Ares",
    "Land Raider Crusader",
    "Land Raider Redeemer",
    "Predator",
    "Repulsor",
    "Repulsor Executioner",
    "Thunderfire Cannon",
    "Vindicator",
    "Whirlwind"
  ],
  "Dedicated Transport": [
    "Drop Pod",
    "Impulsor",
    "Land Speeder Storm",
    "Razorback",
    "Rhino"
  ],
  "Fortifications": [
    "Hammerfall Bunker"
  ],
  "Flyers": [
    "Fire Raptor Gunship",
    "Nephilim Jetfighter",
    "Stormhawk Interceptor",
    "Stormraven Gunship",
    "Stormtalon Gunship"
  ],
  "Lords of War": [
    "Fellblade",
    "Spartan",
    "Knight Castellan",
    "Knight Paladin",
    "Warhound"
  ]
};

/** All units keyed by name. */
export const units: Record<string, Unit> = {
  "Captain Dreadnought": hq_captain_dreadnought as Unit,
  "Chaplain": hq_chaplain as Unit,
  "Chaplain Dreadnought": hq_chaplain_dreadnought as Unit,
  "Emperor's Champion": hq_emperors_champion as Unit,
  "Librarian": hq_librarian as Unit,
  "Librarian Dreadnought": hq_librarian_dreadnought as Unit,
  "Lieutenant": hq_lieutenant as Unit,
  "Assault Intercessor Squad": troops_assault_intercessor_squad as Unit,
  "Blood Claws": troops_blood_claws as Unit,
  "Grey Hunters": troops_grey_hunters as Unit,
  "Heavy Intercessor Squad": troops_heavy_intercessor_squad as Unit,
  "Indomitus Crusader Squad": troops_indomitus_crusader_squad as Unit,
  "Infiltrator Squad": troops_infiltrator_squad as Unit,
  "Intercessor Squad": troops_intercessor_squad as Unit,
  "Scout Squad": troops_scout_squad as Unit,
  "Tactical Squad": troops_tactical_squad as Unit,
  "Aggressor Squad": elites_aggressor_squad as Unit,
  "Ancient": elites_ancient as Unit,
  "Armiger": elites_armiger as Unit,
  "Apothecary": elites_apothecary as Unit,
  "Company Champion": elites_company_champion as Unit,
  "Death Company": elites_death_company as Unit,
  "Deathwing Knights": elites_deathwing_knights as Unit,
  "Dreadnought": elites_dreadnought as Unit,
  "Honor Guard": elites_honor_guard as Unit,
  "Invictor Battlesuit": elites_invictor_battlesuit as Unit,
  "Ironclad Dreadnought": elites_ironclad_dreadnought as Unit,
  "Judicar": elites_judicar as Unit,
  "Kill Team Veterans": elites_kill_team_veterans as Unit,
  "Redemptor Dreadnought": elites_redemptor_dreadnought as Unit,
  "Techmarine": elites_techmarine as Unit,
  "Terminator Squad": elites_terminator_squad as Unit,
  "Wolf Scout Squad": elites_wolf_scout_squad as Unit,
  "Reiver Marines": elites_reiver_marines as Unit,
  "Assault Squad": fast_attack_assault_squad as Unit,
  "Bike Squad": fast_attack_bike_squad as Unit,
  "Inceptor Squad": fast_attack_inceptor_squad as Unit,
  "Infernus Squad": fast_attack_infernus_squad as Unit,
  "Invader-Quad": fast_attack_invader_quad as Unit,
  "Land Speeder": fast_attack_land_speeder as Unit,
  "Outrider Bikes": fast_attack_outrider_bikes as Unit,
  "Ravenwing Black Knights": fast_attack_ravenwing_black_knights as Unit,
  "Razorback Rikarius": fast_attack_razorback_rikarius as Unit,
  "Storm Speeder": fast_attack_storm_speeder as Unit,
  "Suppressor Squad": fast_attack_suppressor_squad as Unit,
  "Wolf Companions": fast_attack_wolf_companions as Unit,
  "Centurion Devastator Squad": heavy_support_centurion_devastator_squad as Unit,
  "Desolation Squad": heavy_support_desolation_squad as Unit,
  "Devastator Squad": heavy_support_devastator_squad as Unit,
  "Eliminator Squad": heavy_support_eliminator_squad as Unit,
  "Eradicator Squad": heavy_support_eradicator_squad as Unit,
  "Firestrike Servo-turret": heavy_support_firestrike_servo_turret as Unit,
  "Gladiator": heavy_support_gladiator as Unit,
  "Hellblaster Squad": heavy_support_hellblaster_squad as Unit,
  "Land Raider": heavy_support_land_raider as Unit,
  "Land Raider Ares": heavy_support_land_raider_ares as Unit,
  "Land Raider Crusader": heavy_support_land_raider_crusader as Unit,
  "Land Raider Redeemer": heavy_support_land_raider_redeemer as Unit,
  "Predator": heavy_support_predator as Unit,
  "Repulsor": heavy_support_repulsor as Unit,
  "Repulsor Executioner": heavy_support_repulsor_executioner as Unit,
  "Thunderfire Cannon": heavy_support_thunderfire_cannon as Unit,
  "Vindicator": heavy_support_vindicator as Unit,
  "Whirlwind": heavy_support_whirlwind as Unit,
  "Drop Pod": dedicated_transport_drop_pod as Unit,
  "Impulsor": dedicated_transport_impulsor as Unit,
  "Land Speeder Storm": dedicated_transport_land_speeder_storm as Unit,
  "Razorback": dedicated_transport_razorback as Unit,
  "Rhino": dedicated_transport_rhino as Unit,
  "Hammerfall Bunker": fortifications_hammerfall_bunker as Unit,
  "Fire Raptor Gunship": flyers_fire_raptor as Unit,
  "Nephilim Jetfighter": flyers_nephilim_jetfighter as Unit,
  "Stormhawk Interceptor": flyers_stormhawk_interceptor as Unit,
  "Stormraven Gunship": flyers_stormraven_gunship as Unit,
  "Stormtalon Gunship": flyers_stormtalon_gunship as Unit,
  "Fellblade": lords_of_war_fellblade as Unit,
  "Spartan": lords_of_war_spartan as Unit,
  "Knight Castellan": lords_of_war_knight_castellan as Unit,
  "Knight Paladin": lords_of_war_knight_paladin as Unit,
  "Warhound": lords_of_war_warhound as Unit,
};
