/**
 * Space Marines — unit index
 * Auto-generated by _migrate_units_to_ts.cjs
 * Each unit lives in its own file under units/<slot>/<name>.ts
 * Add SOURCE comments and engine status notes when auditing each unit.
 */

import * as dedicatedTransport from './dedicated_transport/index';
import * as elites from './elites/index';
import * as fastAttack from './fast_attack/index';
import * as flyers from './flyers/index';
import * as fortifications from './fortifications/index';
import * as heavySupport from './heavy_support/index';
import * as hq from './hq/index';
import * as lordsOfWar from './lords_of_war/index';
import * as troops from './troops/index';

/** All units keyed by name — drop-in replacement for units.json "units" field. */
export const units: Record<string, import('../../../../src/types/data').Unit> = {
  "Captain Dreadnought": hq.captainDreadnought,
  "Chaplain": hq.chaplain,
  "Chaplain Dreadnought": hq.chaplainDreadnought,
  "Emperor's Champion": hq.emperorsChampion,
  "Librarian": hq.librarian,
  "Librarian Dreadnought": hq.librarianDreadnought,
  "Lieutenant": hq.lieutenant,
  "Assault Intercessor Squad": troops.assaultIntercessorSquad,
  "Blood Claws": troops.bloodClaws,
  "Grey Hunters": troops.greyHunters,
  "Heavy Intercessor Squad": troops.heavyIntercessorSquad,
  "Indomitus Crusader Squad": troops.indomitusCrusaderSquad,
  "Infiltrator Squad": troops.infiltratorSquad,
  "Intercessor Squad": troops.intercessorSquad,
  "Scout Squad": troops.scoutSquad,
  "Tactical Squad": troops.tacticalSquad,
  "Aggressor Squad": elites.aggressorSquad,
  "Ancient": elites.ancient,
  "Armiger": elites.armiger,
  "Apothecary": elites.apothecary,
  "Company Champion": elites.companyChampion,
  "Death Company": elites.deathCompany,
  "Deathwing Knights": elites.deathwingKnights,
  "Dreadnought": elites.dreadnought,
  "Honor Guard": elites.honorGuard,
  "Invictor Battlesuit": elites.invictorBattlesuit,
  "Ironclad Dreadnought": elites.ironcladDreadnought,
  "Judicar": elites.judicar,
  "Kill Team Veterans": elites.killTeamVeterans,
  "Redemptor Dreadnought": elites.redemptorDreadnought,
  "Techmarine": elites.techmarine,
  "Terminator Squad": elites.terminatorSquad,
  "Wolf Scout Squad": elites.wolfScoutSquad,
  "Reiver Marines": elites.reiverMarines,
  "Assault Squad": fastAttack.assaultSquad,
  "Bike Squad": fastAttack.bikeSquad,
  "Inceptor Squad": fastAttack.inceptorSquad,
  "Infernus Squad": fastAttack.infernusSquad,
  "Invader-Quad": fastAttack.invaderQuad,
  "Land Speeder": fastAttack.landSpeeder,
  "Outrider Bikes": fastAttack.outriderBikes,
  "Ravenwing Black Knights": fastAttack.ravenwingBlackKnights,
  "Razorback Rikarius": fastAttack.razorbackRikarius,
  "Storm Speeder": fastAttack.stormSpeeder,
  "Suppressor Squad": fastAttack.suppressorSquad,
  "Wolf Companions": fastAttack.wolfCompanions,
  "Centurion Devastator Squad": heavySupport.centurionDevastatorSquad,
  "Desolation Squad": heavySupport.desolationSquad,
  "Devastator Squad": heavySupport.devastatorSquad,
  "Eliminator Squad": heavySupport.eliminatorSquad,
  "Eradicator Squad": heavySupport.eradicatorSquad,
  "Firestrike Servo-turret": heavySupport.firestrikeServoTurret,
  "Gladiator": heavySupport.gladiator,
  "Hellblaster Squad": heavySupport.hellblasterSquad,
  "Land Raider": heavySupport.landRaider,
  "Land Raider Ares": heavySupport.landRaiderAres,
  "Land Raider Crusader": heavySupport.landRaiderCrusader,
  "Land Raider Redeemer": heavySupport.landRaiderRedeemer,
  "Predator": heavySupport.predator,
  "Repulsor": heavySupport.repulsor,
  "Repulsor Executioner": heavySupport.repulsorExecutioner,
  "Thunderfire Cannon": heavySupport.thunderfireCannon,
  "Vindicator": heavySupport.vindicator,
  "Whirlwind": heavySupport.whirlwind,
  "Drop Pod": dedicatedTransport.dropPod,
  "Impulsor": dedicatedTransport.impulsor,
  "Land Speeder Storm": dedicatedTransport.landSpeederStorm,
  "Razorback": dedicatedTransport.razorback,
  "Rhino": dedicatedTransport.rhino,
  "Hammerfall Bunker": fortifications.hammerfallBunker,
  "Fire Raptor": flyers.fireRaptor,
  "Nephilim Jetfighter": flyers.nephilimJetfighter,
  "Stormhawk Interceptor": flyers.stormhawkInterceptor,
  "Stormraven Gunship": flyers.stormravenGunship,
  "Stormtalon Gunship": flyers.stormtalonGunship,
  "Fellblade": lordsOfWar.fellblade,
  "Spartan": lordsOfWar.spartan,
  "Knight Castellan": lordsOfWar.knightCastellan,
  "Knight Paladin": lordsOfWar.knightPaladin,
  "Warhound": lordsOfWar.warhound,
};

/** Slot → unit names map — same as units.json "slot_to_units" field. */
export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Captain Dreadnought",
    "Chaplain",
    "Chaplain Dreadnought",
    "Emperor's Champion",
    "Librarian",
    "Librarian Dreadnought",
    "Lieutenant"
  ],
  "Troops": [
    "Assault Intercessor Squad",
    "Blood Claws",
    "Grey Hunters",
    "Heavy Intercessor Squad",
    "Indomitus Crusader Squad",
    "Infiltrator Squad",
    "Intercessor Squad",
    "Scout Squad",
    "Tactical Squad"
  ],
  "Elites": [
    "Aggressor Squad",
    "Ancient",
    "Armiger",
    "Apothecary",
    "Company Champion",
    "Death Company",
    "Deathwing Knights",
    "Dreadnought",
    "Honor Guard",
    "Invictor Battlesuit",
    "Ironclad Dreadnought",
    "Judicar",
    "Kill Team Veterans",
    "Redemptor Dreadnought",
    "Reiver Marines",
    "Techmarine",
    "Terminator Squad",
    "Wolf Scout Squad"
  ],
  "Fast Attack": [
    "Assault Squad",
    "Bike Squad",
    "Inceptor Squad",
    "Infernus Squad",
    "Invader-Quad",
    "Land Speeder",
    "Outrider Bikes",
    "Ravenwing Black Knights",
    "Razorback Rikarius",
    "Storm Speeder",
    "Suppressor Squad",
    "Wolf Companions"
  ],
  "Heavy Support": [
    "Centurion Devastator Squad",
    "Desolation Squad",
    "Devastator Squad",
    "Eliminator Squad",
    "Eradicator Squad",
    "Firestrike Servo-turret",
    "Gladiator",
    "Hellblaster Squad",
    "Land Raider",
    "Land Raider Ares",
    "Land Raider Crusader",
    "Land Raider Redeemer",
    "Predator",
    "Repulsor",
    "Repulsor Executioner",
    "Thunderfire Cannon",
    "Vindicator",
    "Whirlwind"
  ],
  "Dedicated Transport": [
    "Drop Pod",
    "Impulsor",
    "Land Speeder Storm",
    "Razorback",
    "Rhino"
  ],
  "Fortifications": [
    "Hammerfall Bunker"
  ],
  "Flyers": [
    "Fire Raptor",
    "Nephilim Jetfighter",
    "Stormhawk Interceptor",
    "Stormraven Gunship",
    "Stormtalon Gunship"
  ],
  "Lords of War": [
    "Fellblade",
    "Spartan",
    "Knight Castellan",
    "Knight Paladin",
    "Warhound"
  ]
};

export const faction = "Space Marines";
