/**
 * orks - unit index.
 *
 * Each unit is a PURE JSON file next to this one, so the codex tooling can rewrite it from the
 * sheets without touching any TypeScript. This is the only .ts in the folder: it imports them
 * and exports `faction`, `slot_to_units` and `units` exactly as the old per-slot indexes did.
 *
 * Generated by scripts/convert_units_to_json.cjs. To add a unit, add its .json and one line here.
 */

import type { Unit } from '../../../../src/types/data';

import hq_big_mek from './hq/big_mek.json';
import hq_boss from './hq/boss.json';
import hq_dok from './hq/dok.json';
import hq_weirdboy from './hq/weirdboy.json';
import troops_beast_snagga_boyz from './troops/beast_snagga_boyz.json';
import troops_boyz from './troops/boyz.json';
import troops_gretchins from './troops/gretchins.json';
import troops_skarboyz from './troops/skarboyz.json';
import troops_snotlings from './troops/snotlings.json';
import elites_burna_boyz from './elites/burna_boyz.json';
import elites_cybork_slashaz from './elites/cybork_slashaz.json';
import elites_kommandos from './elites/kommandos.json';
import elites_mekboy from './elites/mekboy.json';
import elites_mekboy_junka from './elites/mekboy_junka.json';
import elites_nobz from './elites/nobz.json';
import elites_painboy from './elites/painboy.json';
import elites_tankbustas from './elites/tankbustas.json';
import fast_attack_deffkoptaz from './fast_attack/deffkoptaz.json';
import fast_attack_grot_tanks from './fast_attack/grot_tanks.json';
import fast_attack_squighog_boyz from './fast_attack/squighog_boyz.json';
import fast_attack_stormboyz from './fast_attack/stormboyz.json';
import fast_attack_warbikers from './fast_attack/warbikers.json';
import fast_attack_warbuggy from './fast_attack/warbuggy.json';
import fast_attack_warkopta from './fast_attack/warkopta.json';
import lords_of_war_battle_fortress from './lords_of_war/battle_fortress.json';
import lords_of_war_orkanaut from './lords_of_war/orkanaut.json';
import lords_of_war_stompa from './lords_of_war/stompa.json';
import heavy_support_battlewagon from './heavy_support/battlewagon.json';
import heavy_support_deff_dreads from './heavy_support/deff_dreads.json';
import heavy_support_flash_gits from './heavy_support/flash_gits.json';
import heavy_support_hunta_rig from './heavy_support/hunta_rig.json';
import heavy_support_killa_kans from './heavy_support/killa_kans.json';
import heavy_support_killa_rig from './heavy_support/killa_rig.json';
import heavy_support_lootas from './heavy_support/lootas.json';
import heavy_support_mek_gunz from './heavy_support/mek_gunz.json';
import heavy_support_wagon from './heavy_support/wagon.json';
import dedicated_transport_kan from './dedicated_transport/kan.json';
import dedicated_transport_looted_valkyrie from './dedicated_transport/looted_valkyrie.json';
import dedicated_transport_squiggoth from './dedicated_transport/squiggoth.json';
import dedicated_transport_trukk from './dedicated_transport/trukk.json';
import fortifications_biged_bossbunka from './fortifications/biged_bossbunka.json';
import flyers_fighta_bommer from './flyers/fighta_bommer.json';
import flyers_wazbom_blastajet from './flyers/wazbom_blastajet.json';

export const faction = "Orks";

export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Big Mek",
    "Boss",
    "Dok",
    "Weirdboy"
  ],
  "Troops": [
    "Beast Snagga Boyz",
    "Boyz",
    "Gretchins",
    "Skarboyz",
    "Snotlings"
  ],
  "Elites": [
    "Burna Boyz",
    "Cybork Slashas",
    "Kommandos",
    "Mekboyz",
    "Mekboy Junka",
    "Nobz",
    "Painboyz",
    "Tankbustas"
  ],
  "Fast Attack": [
    "Deffkoptas",
    "Grot Tanks",
    "Squighog Boyz",
    "Stormboyz",
    "Warbikers",
    "Warbuggy",
    "Warkopta"
  ],
  "Heavy Support": [
    "Battlewagon",
    "Deff Dreads",
    "Flash Gitz",
    "Hunta Rig",
    "Killa Kans",
    "Kill Rig",
    "Lootas",
    "Mek Gunz",
    "Wagon"
  ],
  "Dedicated Transport": [
    "Kan",
    "Looted Valkyrie",
    "Squiggoth",
    "Trukk"
  ],
  "Fortifications": [
    "Big'ed Bossbunka"
  ],
  "Flyers": [
    "Fighta-Bommer",
    "Wazbom Blastajet"
  ],
  "Lords of War": [
    "Battle Fortress",
    "Orkanaut",
    "Stompa"
  ]
};

/** All units keyed by name. */
export const units: Record<string, Unit> = {
  "Big Mek": hq_big_mek as Unit,
  "Boss": hq_boss as Unit,
  "Dok": hq_dok as Unit,
  "Weirdboy": hq_weirdboy as Unit,
  "Beast Snagga Boyz": troops_beast_snagga_boyz as Unit,
  "Boyz": troops_boyz as Unit,
  "Gretchins": troops_gretchins as Unit,
  "Skarboyz": troops_skarboyz as Unit,
  "Snotlings": troops_snotlings as Unit,
  "Burna Boyz": elites_burna_boyz as Unit,
  "Cybork Slashas": elites_cybork_slashaz as Unit,
  "Kommandos": elites_kommandos as Unit,
  "Mekboyz": elites_mekboy as Unit,
  "Mekboy Junka": elites_mekboy_junka as Unit,
  "Nobz": elites_nobz as Unit,
  "Painboyz": elites_painboy as Unit,
  "Tankbustas": elites_tankbustas as Unit,
  "Deffkoptas": fast_attack_deffkoptaz as Unit,
  "Grot Tanks": fast_attack_grot_tanks as Unit,
  "Squighog Boyz": fast_attack_squighog_boyz as Unit,
  "Stormboyz": fast_attack_stormboyz as Unit,
  "Warbikers": fast_attack_warbikers as Unit,
  "Warbuggy": fast_attack_warbuggy as Unit,
  "Warkopta": fast_attack_warkopta as Unit,
  "Battle Fortress": lords_of_war_battle_fortress as Unit,
  "Orkanaut": lords_of_war_orkanaut as Unit,
  "Stompa": lords_of_war_stompa as Unit,
  "Battlewagon": heavy_support_battlewagon as Unit,
  "Deff Dreads": heavy_support_deff_dreads as Unit,
  "Flash Gitz": heavy_support_flash_gits as Unit,
  "Hunta Rig": heavy_support_hunta_rig as Unit,
  "Killa Kans": heavy_support_killa_kans as Unit,
  "Kill Rig": heavy_support_killa_rig as Unit,
  "Lootas": heavy_support_lootas as Unit,
  "Mek Gunz": heavy_support_mek_gunz as Unit,
  "Wagon": heavy_support_wagon as Unit,
  "Kan": dedicated_transport_kan as Unit,
  "Looted Valkyrie": dedicated_transport_looted_valkyrie as Unit,
  "Squiggoth": dedicated_transport_squiggoth as Unit,
  "Trukk": dedicated_transport_trukk as Unit,
  "Big'ed Bossbunka": fortifications_biged_bossbunka as Unit,
  "Fighta-Bommer": flyers_fighta_bommer as Unit,
  "Wazbom Blastajet": flyers_wazbom_blastajet as Unit,
};
