/**
 * Orks — unit index
 * Auto-generated by _migrate_units_to_ts.cjs
 * Each unit lives in its own file under units/<slot>/<name>.ts
 * Add SOURCE comments and engine status notes when auditing each unit.
 */

import * as dedicatedTransport from './dedicated_transport/index';
import * as elites from './elites/index';
import * as fastAttack from './fast_attack/index';
import * as flyers from './flyers/index';
import * as fortifications from './fortifications/index';
import * as heavySupport from './heavy_support/index';
import * as hq from './hq/index';
import * as lordsOfWar from './lords_of_war/index';
import * as troops from './troops/index';

/** All units keyed by name — drop-in replacement for units.json "units" field. */
export const units: Record<string, import('../../../../src/types/data').Unit> = {
  "Big Mek": hq.bigMek,
  "Boss": hq.boss,
  "Dok": hq.dok,
  "Weirdboy": hq.weirdboy,
  "Beast Snagga Boyz": troops.beastSnaggaBoyz,
  "Boyz": troops.boyz,
  "Gretchins": troops.gretchins,
  "Skarboyz": troops.skarboyz,
  "Snotlings": troops.snotlings,
  "Burna Boyz": elites.burnaBoyz,
  "Cybork Slashaz": elites.cyborkSlashaz,
  "Kommandos": elites.kommandos,
  "Mekboy": elites.mekboy,
  "Mekboy Junka": elites.mekboyJunka,
  "Nobz": elites.nobz,
  "Painboy": elites.painboy,
  "Tankbustas": elites.tankbustas,
  "Deffkoptaz": fastAttack.deffkoptaz,
  "Grot Tanks": fastAttack.grotTanks,
  "Squighog Boyz": fastAttack.squighogBoyz,
  "Stormboyz": fastAttack.stormboyz,
  "Warbikers": fastAttack.warbikers,
  "Warbuggy": fastAttack.warbuggy,
  "Warkopta": fastAttack.warkopta,
  "Battle Fortress": lordsOfWar.battleFortress,
  "Orkanaut": lordsOfWar.orkanaut,
  "Stompa": lordsOfWar.stompa,
  "Battlewagon": heavySupport.battlewagon,
  "Deff Dreads": heavySupport.deffDreads,
  "Flash Gits": heavySupport.flashGits,
  "Hunta Rig": heavySupport.huntaRig,
  "Killa Kans": heavySupport.killaKans,
  "Killa Rig": heavySupport.killaRig,
  "Lootas": heavySupport.lootas,
  "Mek Gunz": heavySupport.mekGunz,
  "Wagon": heavySupport.wagon,
  "Kan": dedicatedTransport.kan,
  "Looted Valkyrie": dedicatedTransport.lootedValkyrie,
  "Squiggoth": dedicatedTransport.squiggoth,
  "Trukk": dedicatedTransport.trukk,
  "Big'ed Bossbunka": fortifications.bigedBossbunka,
  "Fighta-Bommer": flyers.fightaBommer,
  "Wazbom Blastajet": flyers.wazbomBlastajet,
};

/** Slot → unit names map — same as units.json "slot_to_units" field. */
export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Big Mek",
    "Boss",
    "Dok",
    "Weirdboy"
  ],
  "Troops": [
    "Beast Snagga Boyz",
    "Boyz",
    "Gretchins",
    "Skarboyz",
    "Snotlings"
  ],
  "Elites": [
    "Burna Boyz",
    "Cybork Slashaz",
    "Kommandos",
    "Mekboy",
    "Mekboy Junka",
    "Nobz",
    "Painboy",
    "Tankbustas"
  ],
  "Fast Attack": [
    "Deffkoptaz",
    "Grot Tanks",
    "Squighog Boyz",
    "Stormboyz",
    "Warbikers",
    "Warbuggy",
    "Warkopta"
  ],
  "Heavy Support": [
    "Battle Fortress",
    "Battlewagon",
    "Deff Dreads",
    "Flash Gits",
    "Hunta Rig",
    "Killa Kans",
    "Killa Rig",
    "Lootas",
    "Mek Gunz",
    "Wagon"
  ],
  "Dedicated Transport": [
    "Kan",
    "Looted Valkyrie",
    "Squiggoth",
    "Trukk"
  ],
  "Fortifications": [
    "Big'ed Bossbunka"
  ],
  "Flyers": [
    "Fighta-Bommer",
    "Wazbom Blastajet"
  ],
  "Lords of War": [
    "Battle Fortress",
    "Orkanaut",
    "Stompa"
  ]
};

export const faction = "Orks";
