/**
 * Inquisition — unit index
 * Auto-generated by _migrate_units_to_ts.cjs; extended 2026-06-17 with 17 new Elites
 * + Sanctioned Bombardement (Heavy Support) from updated Inquisition.ods.
 * Each unit lives in its own file under units/<slot>/<name>.ts
 */

import * as dedicatedTransport from './dedicated_transport/index';
import * as elites from './elites/index';
import * as heavySupport from './heavy_support/index';
import * as hq from './hq/index';
import * as troops from './troops/index';

/** All units keyed by name — drop-in replacement for units.json "units" field. */
export const units: Record<string, import('../../../../src/types/data').Unit> = {
  "Inquisitor": hq.inquisitor,
  "Arbites": troops.arbites,
  "Henchman Warband": troops.henchmanWarband,
  "Stormtroopers": troops.stormtroopers,
  "Deathcult Assassins": elites.deathcultAssassins,
  "Acolytes": elites.acolytes,
  "Alien World Scouts": elites.alienWorldScouts,
  "Archaeotech Researchers": elites.archaeotechResearchers,
  "Arco-flagellants": elites.arcoFlagellants,
  "Chirurgeons": elites.chirurgeons,
  "Crusaders": elites.crusaders,
  "Daemonhosts": elites.daemonhosts,
  "Eldar Outcast": elites.eldarOutcast,
  "Exorcists": elites.exorcists,
  "Jokaero Weaponsmiths": elites.jokaeroWeaponsmiths,
  "Missionaries": elites.missionaries,
  "Mystics": elites.mystics,
  "Penitents": elites.penitents,
  "Psykers": elites.psykers,
  "Sages": elites.sages,
  "Servitors": elites.servitors,
  "Xenologists": elites.xenologists,
  "Land Raider Prometheus": heavySupport.landRaiderPrometheus,
  "Land Raider": heavySupport.landRaider,
  "Sanctioned Bombardement": heavySupport.sanctionedBombardement,
  "Corvus Blackstar": dedicatedTransport.corvusBlackstar,
  "Chimera": dedicatedTransport.chimera,
  "Repressor": dedicatedTransport.repressor,
  "Rhino": dedicatedTransport.rhino,
  "Taurox": dedicatedTransport.taurox,
  "Valkyrie": dedicatedTransport.valkyrie,
};

/** Slot → unit names map — same as units.json "slot_to_units" field. */
export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Inquisitor"
  ],
  "Troops": [
    "Arbites",
    "Henchman Warband",
    "Stormtroopers"
  ],
  "Elites": [
    "Deathcult Assassins",
    "Acolytes",
    "Alien World Scouts",
    "Archaeotech Researchers",
    "Arco-flagellants",
    "Chirurgeons",
    "Crusaders",
    "Daemonhosts",
    "Eldar Outcast",
    "Exorcists",
    "Jokaero Weaponsmiths",
    "Missionaries",
    "Mystics",
    "Penitents",
    "Psykers",
    "Sages",
    "Servitors",
    "Xenologists"
  ],
  "Fast Attack": [],
  "Heavy Support": [
    "Land Raider Prometheus",
    "Land Raider",
    "Sanctioned Bombardement"
  ],
  "Dedicated Transport": [
    "Corvus Blackstar",
    "Chimera",
    "Repressor",
    "Rhino",
    "Taurox",
    "Valkyrie"
  ],
  "Fortifications": [],
  "Flyers": []
};

export const faction = "Inquisition";
