/**
 * Inquisition — unit index
 * Auto-generated by _migrate_units_to_ts.cjs
 * Each unit lives in its own file under units/<slot>/<name>.ts
 * Add SOURCE comments and engine status notes when auditing each unit.
 */

import * as dedicatedTransport from './dedicated_transport/index';
import * as elites from './elites/index';
import * as heavySupport from './heavy_support/index';
import * as hq from './hq/index';
import * as troops from './troops/index';

/** All units keyed by name — drop-in replacement for units.json "units" field. */
export const units: Record<string, import('../../../../src/types/data').Unit> = {
  "Inquisitor": hq.inquisitor,
  "Arbites": troops.arbites,
  "Ordo Hereticus Warband": troops.ordoHereticusWarband,
  "Ordo Malleus Warband": troops.ordoMalleusWarband,
  "Ordo Xenos Warband": troops.ordoXenosWarband,
  "Stormtroopers": troops.stormtroopers,
  "Deathcult Assassins": elites.deathcultAssassins,
  "Land Raider Prometheus": heavySupport.landRaiderPrometheus,
  "Corvus Blackstar": dedicatedTransport.corvusBlackstar,
  "Chimera": dedicatedTransport.chimera,
  "Rhino": dedicatedTransport.rhino,
  "Taurox": dedicatedTransport.taurox,
  "Valkyrie": dedicatedTransport.valkyrie,
};

/** Slot → unit names map — same as units.json "slot_to_units" field. */
export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Inquisitor"
  ],
  "Troops": [
    "Arbites",
    "Ordo Hereticus Warband",
    "Ordo Malleus Warband",
    "Ordo Xenos Warband",
    "Stormtroopers"
  ],
  "Elites": [
    "Deathcult Assassins"
  ],
  "Fast Attack": [],
  "Heavy Support": [
    "Land Raider Prometheus"
  ],
  "Dedicated Transport": [
    "Corvus Blackstar",
    "Chimera",
    "Rhino",
    "Taurox",
    "Valkyrie"
  ],
  "Fortifications": [],
  "Flyers": []
};

export const faction = "Inquisition";
