/**
 * Adeptus Custodes — unit index
 * Auto-generated by _migrate_units_to_ts.cjs
 * Each unit lives in its own file under units/<slot>/<name>.ts
 * Add SOURCE comments and engine status notes when auditing each unit.
 */

import * as dedicatedTransport from './dedicated_transport/index';
import * as elites from './elites/index';
import * as fastAttack from './fast_attack/index';
import * as heavySupport from './heavy_support/index';
import * as hq from './hq/index';
import * as troops from './troops/index';

/** All units keyed by name — drop-in replacement for units.json "units" field. */
export const units: Record<string, import('../../../../src/types/data').Unit> = {
  "Blade Champion": hq.bladeChampion,
  "Knight-Centura": hq.knightCentura,
  "Shield-Captain": hq.shieldCaptain,
  "Shield-Captain on Jetbike": hq.shieldCaptainOnJetbike,
  "Custodian Guard": troops.custodianGuard,
  "Sagittarum Custodians": troops.sagittarumCustodians,
  "Sisters of Silence": troops.sistersOfSilence,
  "Allarus Custodians": elites.allarusCustodians,
  "Aquilon Custodians": elites.aquilonCustodians,
  "Galatus Contemptor Dreadnought": elites.galatusContemptorDreadnought,
  "Custodian Wardens": elites.custodianWardens,
  "Venerable Contemptor Dreadnought": elites.venerableContemptorDreadnought,
  "Vertus Praetor": elites.vertusPraetor,
  "Jetbike Custodians": fastAttack.jetbikeCustodians,
  "Caladius Grav-Tank": heavySupport.caladiusGravTank,
  "Telemon Heavy Dreadnought": heavySupport.telemonHeavyDreadnought,
  "Venerable Land Raider": heavySupport.venerableLandRaider,
  "Rhino": dedicatedTransport.rhino,
  "Coronus Grav-carrier": dedicatedTransport.coronusGravCarrier,
};

/** Slot → unit names map — same as units.json "slot_to_units" field. */
export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Blade Champion",
    "Knight-Centura",
    "Shield-Captain",
    "Shield-Captain on Jetbike"
  ],
  "Troops": [
    "Custodian Guard",
    "Sagittarum Custodians",
    "Sisters of Silence"
  ],
  "Elites": [
    "Allarus Custodians",
    "Aquilon Custodians",
    "Galatus Contemptor Dreadnought",
    "Custodian Wardens",
    "Venerable Contemptor Dreadnought",
    "Vertus Praetor"
  ],
  "Fast Attack": [
    "Jetbike Custodians"
  ],
  "Heavy Support": [
    "Caladius Grav-Tank",
    "Telemon Heavy Dreadnought",
    "Venerable Land Raider"
  ],
  "Dedicated Transport": [
    "Rhino",
    "Coronus Grav-carrier"
  ],
  "Fortifications": [],
  "Flyers": []
};

export const faction = "Adeptus Custodes";
