/**
 * adeptus_custodes - unit index.
 *
 * Each unit is a PURE JSON file next to this one, so the codex tooling can rewrite it from the
 * sheets without touching any TypeScript. This is the only .ts in the folder: it imports them
 * and exports `faction`, `slot_to_units` and `units` exactly as the old per-slot indexes did.
 *
 * Generated by scripts/convert_units_to_json.cjs. To add a unit, add its .json and one line here.
 */

import type { Unit } from '../../../../src/types/data';

import hq_blade_champion from './hq/blade_champion.json';
import hq_knight_centura from './hq/knight_centura.json';
import hq_shield_captain from './hq/shield_captain.json';
import hq_shield_captain_on_jetbike from './hq/shield_captain_on_jetbike.json';
import troops_custodian_guard from './troops/custodian_guard.json';
import troops_sagittarum_custodians from './troops/sagittarum_custodians.json';
import troops_sisters_of_silence from './troops/sisters_of_silence.json';
import elites_allarus_custodians from './elites/allarus_custodians.json';
import elites_aquilon_custodians from './elites/aquilon_custodians.json';
import elites_galatus_contemptor_dreadnought from './elites/galatus_contemptor_dreadnought.json';
import elites_custodian_wardens from './elites/custodian_wardens.json';
import elites_venerable_contemptor_dreadnought from './elites/venerable_contemptor_dreadnought.json';
import fast_attack_vertus_praetors from './fast_attack/vertus_praetors.json';
import fast_attack_venatari_custodians from './fast_attack/venatari_custodians.json';
import heavy_support_caladius_grav_tank from './heavy_support/caladius_grav_tank.json';
import heavy_support_telemon_heavy_dreadnought from './heavy_support/telemon_heavy_dreadnought.json';
import heavy_support_venerable_land_raider from './heavy_support/venerable_land_raider.json';
import dedicated_transport_null_maiden_rhino from './dedicated_transport/null_maiden_rhino.json';
import dedicated_transport_coronus_grav_carrier from './dedicated_transport/coronus_grav_carrier.json';

export const faction = "Adeptus Custodes";

export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Blade Champion",
    "Knight-Centura",
    "Shield-Captain",
    "Shield-Captain on Jetbike"
  ],
  "Troops": [
    "Custodian Guard",
    "Sagittarum Custodians",
    "Sisters of Silence"
  ],
  "Elites": [
    "Allarus Custodians",
    "Aquilon Custodians",
    "Galatus Contemptor Dreadnought",
    "Custodian Wardens",
    "Venerable Contemptor Dreadnought",
  ],
  "Fast Attack": [
    "Vertus Praetors",
    "Venatari Custodians"
  ],
  "Heavy Support": [
    "Caladius Grav-Tank",
    "Telemon Heavy Dreadnought",
    "Venerable Land Raider"
  ],
  "Dedicated Transport": [
    "Null-Maiden Rhino",
    "Coronus Grav-carrier"
  ],
  "Fortifications": [],
  "Flyers": []
};

/** All units keyed by name. */
export const units: Record<string, Unit> = {
  "Blade Champion": hq_blade_champion as Unit,
  "Knight-Centura": hq_knight_centura as Unit,
  "Shield-Captain": hq_shield_captain as Unit,
  "Shield-Captain on Jetbike": hq_shield_captain_on_jetbike as Unit,
  "Custodian Guard": troops_custodian_guard as Unit,
  "Sagittarum Custodians": troops_sagittarum_custodians as Unit,
  "Sisters of Silence": troops_sisters_of_silence as Unit,
  "Allarus Custodians": elites_allarus_custodians as Unit,
  "Aquilon Custodians": elites_aquilon_custodians as Unit,
  "Galatus Contemptor Dreadnought": elites_galatus_contemptor_dreadnought as Unit,
  "Custodian Wardens": elites_custodian_wardens as Unit,
  "Venerable Contemptor Dreadnought": elites_venerable_contemptor_dreadnought as Unit,
  "Vertus Praetors": fast_attack_vertus_praetors as Unit,
  "Venatari Custodians": fast_attack_venatari_custodians as Unit,
  "Caladius Grav-Tank": heavy_support_caladius_grav_tank as Unit,
  "Telemon Heavy Dreadnought": heavy_support_telemon_heavy_dreadnought as Unit,
  "Venerable Land Raider": heavy_support_venerable_land_raider as Unit,
  "Null-Maiden Rhino": dedicated_transport_null_maiden_rhino as Unit,
  "Coronus Grav-carrier": dedicated_transport_coronus_grav_carrier as Unit,
};
