/**
 * codex_adeptus_sororitas/special-abilities — category 4 of 5 (Special ability).
 *
 * Migrated from `rules-model/adeptus_sororitas.md` §4-§5 (grounded in the `.ods` canon).
 *
 * Anti-duplication: the 3 archetypes / 7 legacies / 12 traits stay canonical in `archetypes.json`
 * (cross-check 3/7/12 exact); the 6 Order Militant armories live under `armory/`. The Witch
 * hunters (Inquisition + Assassins) access is already SHIPPED ([[project_inquisition_audit]]). The
 * Holy Trinity legacy is already fixed ([[project_features_v021]]). This file documents the
 * army-rule MECHANICS + customisation structure.
 */

export interface SororitasSpecialAbilityEntry {
  name: string;
  category: 'army-rule' | 'cast-system' | 'archetype' | 'legacy' | 'trait';
  text: string;
}

// Source: rules-model/adeptus_sororitas.md §4 (army rules) + §5 (archetypes/legacies/traits).
export const SORORITAS_SPECIAL_ABILITIES: SororitasSpecialAbilityEntry[] = [
  // --- §4 army rules ---
  {
    name: 'Acts of Faith (signature mechanic)',
    category: 'army-rule',
    text: 'Verbatim (Index): "The unit may perform an Act of Faith. Each unit can use as many Acts ' +
      'of Faith per battle round as the army has Faith points, but can only benefit from one effect ' +
      'at a time. Attached character models gain the same benefit, if they have this rule..." A ' +
      'Faith-point economy (acts on the "Acts of Faith" sheet). Faith generated by Pious units + ' +
      'the Anointment equipment + The Blood of Martyrs trait; refunded by The Emperor\'s Judgement ' +
      'trait; the Simulacrum Imperialis equipment lets a unit benefit from 2 Acts at once.',
  },
  {
    name: 'Pious',
    category: 'army-rule',
    text: 'Verbatim (Index): "The unit generates the specified number of Faith Points for the army ' +
      'once during the first Rally phase and then again immediately when it is removed as a ' +
      'casualty." The primary Faith-point source feeding Acts of Faith.',
  },
  {
    name: 'Shield of Faith',
    category: 'army-rule',
    text: 'Verbatim (Index): "The model receives a 6+ invulnerability save." Army-wide baseline ' +
      'invuln on Sororitas models.',
  },
  {
    name: 'Witch hunters (Inquisition + Assassins access)',
    category: 'army-rule',
    text: 'Verbatim (Index): "The army has access to Inquisition units. Inquisitors must select ' +
      '\'Ordo Hereticus\' in the Armory. The army has access to assassins." Already SHIPPED via the ' +
      '`intrinsic_allies` mechanism + the universal Assassins-access system ([[project_inquisition_' +
      'audit]] — `ki-sororitas-inquisition-missing-01` fixed; Assassins Pass 5 unified scope). ' +
      'Documented here for completeness — no further engine change needed.',
  },

  // --- §4 litany system ---
  {
    name: 'Hymns of Battle (Preacher/Dogmata litanies)',
    category: 'cast-system',
    text: 'The Preacher/Dogmata prayer system (NOT psychic — Sororitas have no psykers). The ' +
      '"Blessing" equipment grants +1 Hymn known. Hymns on the "Hymns of Battle" sheet.',
  },

  // --- §5 Archetypes (3, all AOP-shuffle) ---
  {
    name: 'Archetypes (3 total)',
    category: 'archetype',
    text: 'Budget 0-1 Archetype. All AOP-shuffle (no cross-faction ally-matrix — Sororitas have ' +
      'none): Holy Vanguard (Dominions→Troops, must start embarked; only Dominions count to 25%), ' +
      'Penitent Crusade (Arco-flagellants/Repentia→Troops; 1 Penitent Engine per 10 Arco models; ' +
      'Battle Sisters/Novitiate→Elite), Shrine Wardens (Celestian Sacresants→Troops; Battle ' +
      'Sisters/Novitiate→Elite; no Arco/Repentia/Penitent Engines). Canonical in `archetypes.json`.',
  },

  // --- §5 Legacies (7) — 6 Orders Militant + the special Holy Trinity ---
  {
    name: 'Legacies (7 total — 6 Orders Militant + Holy Trinity)',
    category: 'legacy',
    text: 'Six grant one Order Militant\'s Armory each: Blind Faith→Valorous Heart / Cleansing ' +
      'Flames→Ebon Chalice / Faith Is Our Shield→Argent Shroud / Honour The Martyrs→Our Martyred ' +
      'Lady / Tear Them Down→Bloody Rose / The Emperor\'s Judgement→Sacred Rose. The 7th, THE HOLY ' +
      'TRINITY, is structurally special: grants a 3rd Trait slot AND forces three specific traits ' +
      '(Raging Fervour + Rites of Fire + Unshakeable Vengeance), all combined costing 10 pts per ' +
      'non-character unit. Already fixed — [[project_features_v021]]. Order armories under `armory/`.',
  },

  // --- §5 Traits (12) ---
  {
    name: 'Traits (12 total — army-wide, 3-column pricing)',
    category: 'trait',
    text: 'Budget 0-2 Traits (3 with Holy Trinity). 3-column NORMAL/CHARACTER/MC&V pricing (`*` = ' +
      'per Wound/Hull): Combined Conviction (→"must select a 2nd Legacy") / Deeds, not Words / ' +
      'Devout Fanaticism / Guided by the Emperor\'s Will / Holy Wrath / Raging Fervour / Rites of ' +
      'Fire / Shield of Aversion / The Blood of Martyrs (+1 Faith Point on death) / The Emperor\'s ' +
      'Judgement (5+ refunds a spent Faith Point) / Unbridled Valour / Unshakable Vengeance. The ' +
      'Faith-economy traits (Blood of Martyrs, Emperor\'s Judgement) feed the Acts of Faith engine. ' +
      'Canonical in `archetypes.json`.',
  },
];
