import type { ArchetypeRule } from './base';
import { BASE, cultArchetype, dropPodArchetype } from './base';

export const CSM_ARCHETYPES: Record<string, ArchetypeRule> = {
  'Blood for the Blood God!': cultArchetype('Khorne', 'Khorne Berzerkers'),
  'All is Dust': {
    ...cultArchetype('Tzeentch', 'Rubric Marines'),
    notes: [
      'All units must carry the Mark of Tzeentch.',
      'Rubric Marines count as Troops.',
      'Only units with locked Mark of Tzeentch count towards the 25% Troops requirement.',
      'Access to Chaos Daemons units with the Mark of Tzeentch.',
      'Legionnaires not allowed. No Legacies or Traits may be chosen.',
      'Vehicle combi weapons are automatically upgraded: Combi-bolter → Inferno combi-bolter (+2 pts), Combi-flamer → Inferno combi-warpflamer (+4 pts), Combi-melta → Inferno combi-melta (+1 pt).',
    ],
  },
  'Ambition for Perfection': cultArchetype('Slaanesh', 'Noise Marines'),
  'Plaguehost': {
    ...cultArchetype('Nurgle', 'Plague Marines'),
    notes: [
      'All units must carry the Mark of Nurgle.',
      'Plague Marines count as Troops.',
      'Only units with locked Mark of Nurgle count towards the 25% Troops requirement.',
      'Access to Chaos Daemons units with the Mark of Nurgle.',
      'Legionnaires not allowed. No Legacies or Traits may be chosen.',
      'Frag grenades on all models are exchanged for Blight grenades at no additional cost.',
      'Vehicle combi weapons are automatically upgraded: Combi-bolter +2 pts (gains Poison 4+), Combi-flamer → Combi-plague belcher +4 pts, Combi-melta +2 pts (gains Poison 4+ on bolter).',
    ],
  },
  'Host Raptorial': { ...BASE,
    troopsRemap: ['Raptors', 'Warptalons'], troopsCount: 'remap',
    notes: [
      'Raptors and Warptalons count as Troops.',
      'Only Raptor units count towards the 25% Troops requirement.',
      'At least half of Raptor models must start in reserves.',
    ],
  },
  'The Swift Blade': { ...BASE,
    troopsRemap: ['Chaos Bikers'],
    notes: [
      'Chaos Bikers count as Troops.',
      'Flanking units may deploy on turn 1.',
      'Units with M<12" and no transport option cannot be selected.',
    ],
  },
  'Sorcerer Circle': { ...BASE,
    hqOverride: [1, 4], hqAllowed: ['Chaos Sorcerer', 'Master of Sorcery'],
    notes: [
      '4 HQ slots (minimum 1, maximum 4).',
      'Only Chaos Sorcerer and Master of Sorcery as HQ.',
      'Chaos Sorcerers gain the "Command squad" ability.',
      'All models must deploy within 12" of each other.',
    ],
  },
  "Abaddon's Chosen": { ...BASE,
    hqOverride: [4, 5], noAnimosity: true,
    notes: [
      '5 HQ slots (minimum 4 must be filled).',
      'Each HQ must have a different Chaos Mark.',
      'Animosity of the Gods rule does not apply.',
    ],
  },
  'Legionnaire Warband': { ...BASE,
    troopsRemap: ['Legionnaires'], requireVetAbilities: true,
    notes: [
      'Legionnaires count as Troops.',
      'All units must have at least 1 veteran ability (Marks do not count).',
      'Units without access to veteran abilities cannot be selected.',
    ],
  },
  'Special Operations': { ...BASE,
    grantVetAbilities: ['Cultists'],
    notes: ['Cultists must choose 2 veteran abilities, one of which must be "Infiltrator".'],
  },
  'Daemonkin': { ...BASE,
    noLegacy: true, noTraits: true,
    alliedFaction: 'chaos_daemons', alliedMarkFilter: 'hq_mark',
    notes: [
      'Access to all Chaos Daemons units (filtered by HQ Mark).',
      'All units must carry the same Chaos Mark.',
      'At least 1 HQ from each Codex (CSM and Daemons).',
      'No Legacies or Traits may be chosen.',
    ],
  },
  'Dreadclaw Assault': dropPodArchetype('Dreadclaw Drop Pod'),
  'Legion': { ...BASE,
    troopsRemap: ['Legion Breacher Squad', 'Legion Tactical Squad', 'Legion Tactical Support Squad'],
    troopsCount: 'remap',
    alliedFaction: 'horus_heresy', alliedMarkFilter: 'all',
    notes: [
      'Access to all Horus Heresy Space Marines supplement units.',
      'Only HH supplement Troops (Breacher, Tactical, Tactical Support) count towards the 25%.',
    ],
  },
};
