/**
 * tyranids - unit index.
 *
 * Each unit is a PURE JSON file next to this one, so the codex tooling can rewrite it from the
 * sheets without touching any TypeScript. This is the only .ts in the folder: it imports them
 * and exports `faction`, `slot_to_units` and `units` exactly as the old per-slot indexes did.
 *
 * Generated by scripts/convert_units_to_json.cjs. To add a unit, add its .json and one line here.
 */

import type { Unit } from '../../../../src/types/data';

import hq_hive_tyrant from './hq/hive_tyrant.json';
import hq_malanthrope from './hq/malanthrope.json';
import hq_neurotyrant from './hq/neurotyrant.json';
import hq_tervigon from './hq/tervigon.json';
import hq_tyranid_prime from './hq/tyranid_prime.json';
import hq_tyrant_guard_brood from './hq/tyrant_guard_brood.json';
import troops_barbgaunt_brood from './troops/barbgaunt_brood.json';
import troops_genestealer_brood from './troops/genestealer_brood.json';
import troops_hormagaunt_brood from './troops/hormagaunt_brood.json';
import troops_neurogaunt_brood from './troops/neurogaunt_brood.json';
import troops_ripper_swarms from './troops/ripper_swarms.json';
import troops_termagant_brood from './troops/termagant_brood.json';
import troops_tyranid_warrior_brood from './troops/tyranid_warrior_brood.json';
import elites_deathleaper from './elites/deathleaper.json';
import elites_haruspex from './elites/haruspex.json';
import elites_hive_guard_brood from './elites/hive_guard_brood.json';
import elites_lictor_brood from './elites/lictor_brood.json';
import elites_maleceptor from './elites/maleceptor.json';
import elites_toxicrene from './elites/toxicrene.json';
import elites_venomthrope_brood from './elites/venomthrope_brood.json';
import elites_zoanthrope_brood from './elites/zoanthrope_brood.json';
import elites_von_ryans_leaper_brood from './elites/von_ryans_leaper_brood.json';
import fast_attack_gargoyle_brood from './fast_attack/gargoyle_brood.json';
import fast_attack_mawloc from './fast_attack/mawloc.json';
import fast_attack_mucolid_spore_cluster from './fast_attack/mucolid_spore_cluster.json';
import fast_attack_parasite_of_mortrex from './fast_attack/parasite_of_mortrex.json';
import fast_attack_psychophage from './fast_attack/psychophage.json';
import fast_attack_pyrovore_brood from './fast_attack/pyrovore_brood.json';
import fast_attack_ravener_alpha from './fast_attack/ravener_alpha.json';
import fast_attack_ravener_brood from './fast_attack/ravener_brood.json';
import fast_attack_spore_mine_cluster from './fast_attack/spore_mine_cluster.json';
import fast_attack_trygon from './fast_attack/trygon.json';
import heavy_support_biovore_brood from './heavy_support/biovore_brood.json';
import heavy_support_carnifex_brood from './heavy_support/carnifex_brood.json';
import heavy_support_dactylis from './heavy_support/dactylis.json';
import heavy_support_exocrine from './heavy_support/exocrine.json';
import heavy_support_norn from './heavy_support/norn.json';
import heavy_support_tyrannofex from './heavy_support/tyrannofex.json';
import dedicated_transport_tyrannocyte from './dedicated_transport/tyrannocyte.json';
import fortifications_sporecyst from './fortifications/sporecyst.json';
import flyers_harpy from './flyers/harpy.json';
import flyers_hive_crone from './flyers/hive_crone.json';

export const faction = "Tyranids";

export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Hive Tyrant",
    "Malanthrope",
    "Neurotyrant",
    "Tervigon",
    "Tyranid Prime",
    "Tyrant Guard Brood"
  ],
  "Troops": [
    "Barbgaunt Brood",
    "Genestealer Brood",
    "Hormagaunt Brood",
    "Neurogaunt Brood",
    "Ripper Swarms",
    "Termagant Brood",
    "Tyranid Warrior Brood"
  ],
  "Elites": [
    "Deathleaper",
    "Haruspex",
    "Hive Guard Brood",
    "Lictor Brood",
    "Maleceptor",
    "Toxicrene",
    "Venomthrope Brood",
    "Von Ryan's Leaper Brood",
    "Zoanthrope Brood"
  ],
  "Fast Attack": [
    "Gargoyle Brood",
    "Mawloc",
    "Mucolid Spore Cluster",
    "Parasite of Mortrex",
    "Psychophage",
    "Pyrovore Brood",
    "Ravener Alpha",
    "Ravener Brood",
    "Spore Mine Cluster",
    "Trygon"
  ],
  "Heavy Support": [
    "Biovore Brood",
    "Carnifex Brood",
    "Dactylis",
    "Exocrine",
    "Norn",
    "Tyrannofex"
  ],
  "Dedicated Transport": [
    "Tyrannocyte"
  ],
  "Fortifications": [
    "Sporecyst"
  ],
  "Flyers": [
    "Harpy",
    "Hive Crone"
  ]
};

/** All units keyed by name. */
export const units: Record<string, Unit> = {
  "Hive Tyrant": hq_hive_tyrant as Unit,
  "Malanthrope": hq_malanthrope as Unit,
  "Neurotyrant": hq_neurotyrant as Unit,
  "Tervigon": hq_tervigon as Unit,
  "Tyranid Prime": hq_tyranid_prime as Unit,
  "Tyrant Guard Brood": hq_tyrant_guard_brood as Unit,
  "Barbgaunt Brood": troops_barbgaunt_brood as Unit,
  "Genestealer Brood": troops_genestealer_brood as Unit,
  "Hormagaunt Brood": troops_hormagaunt_brood as Unit,
  "Neurogaunt Brood": troops_neurogaunt_brood as Unit,
  "Ripper Swarms": troops_ripper_swarms as Unit,
  "Termagant Brood": troops_termagant_brood as Unit,
  "Tyranid Warrior Brood": troops_tyranid_warrior_brood as Unit,
  "Deathleaper": elites_deathleaper as Unit,
  "Haruspex": elites_haruspex as Unit,
  "Hive Guard Brood": elites_hive_guard_brood as Unit,
  "Lictor Brood": elites_lictor_brood as Unit,
  "Maleceptor": elites_maleceptor as Unit,
  "Toxicrene": elites_toxicrene as Unit,
  "Venomthrope Brood": elites_venomthrope_brood as Unit,
  "Zoanthrope Brood": elites_zoanthrope_brood as Unit,
  "Von Ryan's Leaper Brood": elites_von_ryans_leaper_brood as Unit,
  "Gargoyle Brood": fast_attack_gargoyle_brood as Unit,
  "Mawloc": fast_attack_mawloc as Unit,
  "Mucolid Spore Cluster": fast_attack_mucolid_spore_cluster as Unit,
  "Parasite of Mortrex": fast_attack_parasite_of_mortrex as Unit,
  "Psychophage": fast_attack_psychophage as Unit,
  "Pyrovore Brood": fast_attack_pyrovore_brood as Unit,
  "Ravener Alpha": fast_attack_ravener_alpha as Unit,
  "Ravener Brood": fast_attack_ravener_brood as Unit,
  "Spore Mine Cluster": fast_attack_spore_mine_cluster as Unit,
  "Trygon": fast_attack_trygon as Unit,
  "Biovore Brood": heavy_support_biovore_brood as Unit,
  "Carnifex Brood": heavy_support_carnifex_brood as Unit,
  "Dactylis": heavy_support_dactylis as Unit,
  "Exocrine": heavy_support_exocrine as Unit,
  "Norn": heavy_support_norn as Unit,
  "Tyrannofex": heavy_support_tyrannofex as Unit,
  "Tyrannocyte": dedicated_transport_tyrannocyte as Unit,
  "Sporecyst": fortifications_sporecyst as Unit,
  "Harpy": flyers_harpy as Unit,
  "Hive Crone": flyers_hive_crone as Unit,
};
