/**
 * Tyranids — unit index
 * Auto-generated by _migrate_units_to_ts.cjs
 * Each unit lives in its own file under units/<slot>/<name>.ts
 * Add SOURCE comments and engine status notes when auditing each unit.
 */

import * as dedicatedTransport from './dedicated_transport/index';
import * as elites from './elites/index';
import * as fastAttack from './fast_attack/index';
import * as flyers from './flyers/index';
import * as fortifications from './fortifications/index';
import * as heavySupport from './heavy_support/index';
import * as hq from './hq/index';
import * as troops from './troops/index';

/** All units keyed by name — drop-in replacement for units.json "units" field. */
export const units: Record<string, import('../../../../src/types/data').Unit> = {
  "Hive Tyrant": hq.hiveTyrant,
  "Malanthrope": hq.malanthrope,
  "Neurotyrant": hq.neurotyrant,
  "Swarmlord": hq.swarmlord,
  "Tervigon": hq.tervigon,
  "Tyranid Prime": hq.tyranidPrime,
  "Tyrant Guard Brood": hq.tyrantGuardBrood,
  "Barbgaunt Brood": troops.barbgauntBrood,
  "Genestealer Brood": troops.genestealerBrood,
  "Hormagaunt Brood": troops.hormagauntBrood,
  "Neurogaunt Brood": troops.neurogauntBrood,
  "Ripper Swarms": troops.ripperSwarms,
  "Termagant Brood": troops.termagantBrood,
  "Tyranid Warrior Brood": troops.tyranidWarriorBrood,
  "Deathleaper": elites.deathleaper,
  "Haruspex": elites.haruspex,
  "Hive Guard Brood": elites.hiveGuardBrood,
  "Lictor Brood": elites.lictorBrood,
  "Maleceptor": elites.maleceptor,
  "Toxicrene": elites.toxicrene,
  "Venomthrope Brood": elites.venomthropeBrood,
  "Zoanthrope Brood": elites.zoanthropeBrood,
  "Von Ryan's Leaper Brood": elites.vonRyansLeaperBrood,
  "Gargoyle Brood": fastAttack.gargoyleBrood,
  "Mawloc": fastAttack.mawloc,
  "Mucolid Spore Cluster": fastAttack.mucolidSporeCluster,
  "Parasite of Mortrex": fastAttack.parasiteOfMortrex,
  "Psychophage": fastAttack.psychophage,
  "Pyrovore Brood": fastAttack.pyrovoreBrood,
  "Ravener Brood": fastAttack.ravenerBrood,
  "Spore Mine Cluster": fastAttack.sporeMineCluster,
  "Trygon": fastAttack.trygon,
  "Biovore Brood": heavySupport.biovoreBrood,
  "Carnifex Brood": heavySupport.carnifexBrood,
  "Exocrine": heavySupport.exocrine,
  "Norn": heavySupport.norn,
  "Tyrannofex": heavySupport.tyrannofex,
  "Tyrannocyte": dedicatedTransport.tyrannocyte,
  "Sporecyst": fortifications.sporecyst,
  "Harpy": flyers.harpy,
};

/** Slot → unit names map — same as units.json "slot_to_units" field. */
export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Hive Tyrant",
    "Malanthrope",
    "Neurotyrant",
    "Swarmlord",
    "Tervigon",
    "Tyranid Prime",
    "Tyrant Guard Brood"
  ],
  "Troops": [
    "Barbgaunt Brood",
    "Genestealer Brood",
    "Hormagaunt Brood",
    "Neurogaunt Brood",
    "Ripper Swarms",
    "Termagant Brood",
    "Tyranid Warrior Brood"
  ],
  "Elites": [
    "Deathleaper",
    "Haruspex",
    "Hive Guard Brood",
    "Lictor Brood",
    "Maleceptor",
    "Toxicrene",
    "Venomthrope Brood",
    "Von Ryan's Leaper Brood",
    "Zoanthrope Brood"
  ],
  "Fast Attack": [
    "Gargoyle Brood",
    "Mawloc",
    "Mucolid Spore Cluster",
    "Parasite of Mortrex",
    "Psychophage",
    "Pyrovore Brood",
    "Ravener Brood",
    "Spore Mine Cluster",
    "Trygon"
  ],
  "Heavy Support": [
    "Biovore Brood",
    "Carnifex Brood",
    "Exocrine",
    "Norn",
    "Tyrannofex"
  ],
  "Dedicated Transport": [
    "Tyrannocyte"
  ],
  "Fortifications": [
    "Sporecyst"
  ],
  "Flyers": [
    "Harpy"
  ]
};

export const faction = "Tyranids";
