/**
 * dark_eldar - unit index.
 *
 * Each unit is a PURE JSON file next to this one, so the codex tooling can rewrite it from the
 * sheets without touching any TypeScript. This is the only .ts in the folder: it imports them
 * and exports `faction`, `slot_to_units` and `units` exactly as the old per-slot indexes did.
 *
 * Generated by scripts/convert_units_to_json.cjs. To add a unit, add its .json and one line here.
 */

import type { Unit } from '../../../../src/types/data';

import hq_dracon from './hq/dracon.json';
import hq_haemonculus from './hq/haemonculus.json';
import hq_succubus from './hq/succubus.json';
import troops_kabalite_warriors from './troops/kabalite_warriors.json';
import troops_wracks from './troops/wracks.json';
import troops_wyches from './troops/wyches.json';
import elites_court_of_the_archon from './elites/court_of_the_archon.json';
import elites_grotesques from './elites/grotesques.json';
import elites_haemoxytes from './elites/haemoxytes.json';
import elites_hekatrix_bloodbrides from './elites/hekatrix_bloodbrides.json';
import elites_incubi from './elites/incubi.json';
import elites_kabalite_trueborn from './elites/kabalite_trueborn.json';
import elites_mandrakes from './elites/mandrakes.json';
import fast_attack_beastpack from './fast_attack/beastpack.json';
import fast_attack_hellions from './fast_attack/hellions.json';
import fast_attack_reavers from './fast_attack/reavers.json';
import fast_attack_scourges from './fast_attack/scourges.json';
import heavy_support_cronos from './heavy_support/cronos.json';
import heavy_support_ravager from './heavy_support/ravager.json';
import heavy_support_reaper from './heavy_support/reaper.json';
import heavy_support_talos from './heavy_support/talos.json';
import dedicated_transport_raider from './dedicated_transport/raider.json';
import dedicated_transport_venom from './dedicated_transport/venom.json';
import flyers_raven_fighter from './flyers/raven_fighter.json';
import flyers_razorwing_jetfighter from './flyers/razorwing_jetfighter.json';
import flyers_voidraven_bomber from './flyers/voidraven_bomber.json';

export const faction = "Dark Eldar";

export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Dracon",
    "Haemonculus",
    "Succubus"
  ],
  "Troops": [
    "Kabalite Warriors",
    "Wracks",
    "Wyches"
  ],
  "Elites": [
    "Court of the Archon",
    "Grotesques",
    "Haemoxytes",
    "Hekatrix Bloodbrides",
    "Incubi",
    "Kabalite Trueborn",
    "Mandrakes"
  ],
  "Fast Attack": [
    "Beastpack",
    "Hellions",
    "Reavers",
    "Scourges"
  ],
  "Heavy Support": [
    "Cronos",
    "Ravager",
    "Reaper",
    "Talos"
  ],
  "Dedicated Transport": [
    "Raider",
    "Venom"
  ],
  "Fortifications": [],
  "Flyers": [
    "Raven Fighter",
    "Razorwing Jetfighter",
    "Voidraven Bomber"
  ]
};

/** All units keyed by name. */
export const units: Record<string, Unit> = {
  "Dracon": hq_dracon as Unit,
  "Haemonculus": hq_haemonculus as Unit,
  "Succubus": hq_succubus as Unit,
  "Kabalite Warriors": troops_kabalite_warriors as Unit,
  "Wracks": troops_wracks as Unit,
  "Wyches": troops_wyches as Unit,
  "Court of the Archon": elites_court_of_the_archon as Unit,
  "Grotesques": elites_grotesques as Unit,
  "Haemoxytes": elites_haemoxytes as Unit,
  "Hekatrix Bloodbrides": elites_hekatrix_bloodbrides as Unit,
  "Incubi": elites_incubi as Unit,
  "Kabalite Trueborn": elites_kabalite_trueborn as Unit,
  "Mandrakes": elites_mandrakes as Unit,
  "Beastpack": fast_attack_beastpack as Unit,
  "Hellions": fast_attack_hellions as Unit,
  "Reavers": fast_attack_reavers as Unit,
  "Scourges": fast_attack_scourges as Unit,
  "Cronos": heavy_support_cronos as Unit,
  "Ravager": heavy_support_ravager as Unit,
  "Reaper": heavy_support_reaper as Unit,
  "Talos": heavy_support_talos as Unit,
  "Raider": dedicated_transport_raider as Unit,
  "Venom": dedicated_transport_venom as Unit,
  "Raven Fighter": flyers_raven_fighter as Unit,
  "Razorwing Jetfighter": flyers_razorwing_jetfighter as Unit,
  "Voidraven Bomber": flyers_voidraven_bomber as Unit,
};
