/**
 * Dark Eldar — unit index
 * Auto-generated by _migrate_units_to_ts.cjs
 * Each unit lives in its own file under units/<slot>/<name>.ts
 * Add SOURCE comments and engine status notes when auditing each unit.
 */

import * as dedicatedTransport from './dedicated_transport/index';
import * as elites from './elites/index';
import * as fastAttack from './fast_attack/index';
import * as flyers from './flyers/index';
import * as heavySupport from './heavy_support/index';
import * as hq from './hq/index';
import * as troops from './troops/index';

/** All units keyed by name — drop-in replacement for units.json "units" field. */
export const units: Record<string, import('../../../../src/types/data').Unit> = {
  "Dracon": hq.dracon,
  "Haemonculus": hq.haemonculus,
  "Succubus": hq.succubus,
  "Kabalite Warriors": troops.kabaliteWarriors,
  "Wracks": troops.wracks,
  "Wyches": troops.wyches,
  "Court of the Archon": elites.courtOfTheArchon,
  "Grotesques": elites.grotesques,
  "Haemoxytes": elites.haemoxytes,
  "Hekatrix Bloodbrides": elites.hekatrixBloodbrides,
  "Incubi": elites.incubi,
  "Kabalite Trueborn": elites.kabaliteTrueborn,
  "Mandrakes": elites.mandrakes,
  "Beastpack": fastAttack.beastpack,
  "Hellions": fastAttack.hellions,
  "Reavers": fastAttack.reavers,
  "Scourges": fastAttack.scourges,
  "Cronos": heavySupport.cronos,
  "Ravager": heavySupport.ravager,
  "Reaper": heavySupport.reaper,
  "Talos": heavySupport.talos,
  "Raider": dedicatedTransport.raider,
  "Venom": dedicatedTransport.venom,
  "Raven Fighter": flyers.ravenFighter,
  "Razorwing Jetfighter": flyers.razorwingJetfighter,
  "Voidraven Bomber": flyers.voidravenBomber,
};

/** Slot → unit names map — same as units.json "slot_to_units" field. */
export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Dracon",
    "Haemonculus",
    "Succubus"
  ],
  "Troops": [
    "Kabalite Warriors",
    "Wracks",
    "Wyches"
  ],
  "Elites": [
    "Court of the Archon",
    "Grotesques",
    "Haemoxytes",
    "Hekatrix Bloodbrides",
    "Incubi",
    "Kabalite Trueborn",
    "Mandrakes"
  ],
  "Fast Attack": [
    "Beastpack",
    "Hellions",
    "Reavers",
    "Scourges"
  ],
  "Heavy Support": [
    "Cronos",
    "Ravager",
    "Reaper",
    "Talos"
  ],
  "Dedicated Transport": [
    "Raider",
    "Venom"
  ],
  "Fortifications": [],
  "Flyers": [
    "Raven Fighter",
    "Razorwing Jetfighter",
    "Voidraven Bomber"
  ]
};

export const faction = "Dark Eldar";
