/**
 * Adeptus Sororitas — unit index
 * Auto-generated by _migrate_units_to_ts.cjs
 * Each unit lives in its own file under units/<slot>/<name>.ts
 * Add SOURCE comments and engine status notes when auditing each unit.
 */

import * as dedicatedTransport from './dedicated_transport/index';
import * as elites from './elites/index';
import * as fastAttack from './fast_attack/index';
import * as heavySupport from './heavy_support/index';
import * as hq from './hq/index';
import * as lordsOfWar from './lords_of_war/index';
import * as troops from './troops/index';

/** All units keyed by name — drop-in replacement for units.json "units" field. */
export const units: Record<string, import('../../../../src/types/data').Unit> = {
  "Canoness in Paragon Warsuit": hq.canonessInParagonWarsuit,
  "Geminae Superia": hq.geminaeSuperia,
  "Living Saint": hq.livingSaint,
  "Missionary": hq.missionary,
  "Palatine": hq.palatine,
  "Battle Sisters Squad": troops.battleSistersSquad,
  "Sisters Novitiate": troops.sistersNovitiate,
  "Arco-flagellants": elites.arcoFlagellants,
  "Celestian Insidiants": elites.celestianInsidiants,
  "Celestian Sacresants": elites.celestianSacresants,
  "Celestian Squad": elites.celestianSquad,
  "Crusaders": elites.crusaders,
  "Dogmata": elites.dogmata,
  "Hospitaller": elites.hospitaller,
  "Dialogus": elites.dialogus,
  "Imagifier": elites.imagifier,
  "Paragon Warsuits": elites.paragonWarsuits,
  "Preacher": elites.preacher,
  "Repentia Squad": elites.repentiaSquad,
  "Dominion Squad": fastAttack.dominionSquad,
  "Seraphim Squad": fastAttack.seraphimSquad,
  "Zephyrim Squad": fastAttack.zephyrimSquad,
  "Castigator": heavySupport.castigator,
  "Exorcist": heavySupport.exorcist,
  "Penitent Engines": heavySupport.penitentEngines,
  "Retributor Squad": heavySupport.retributorSquad,
  "Immolator": dedicatedTransport.immolator,
  "Rhino": dedicatedTransport.rhino,
  "Triumphant Procession": lordsOfWar.triumphantProcession,
};

/** Slot → unit names map — same as units.json "slot_to_units" field. */
export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Canoness in Paragon Warsuit",
    "Geminae Superia",
    "Living Saint",
    "Missionary",
    "Palatine"
  ],
  "Troops": [
    "Battle Sisters Squad",
    "Sisters Novitiate"
  ],
  "Elites": [
    "Arco-flagellants",
    "Celestian Insidiants",
    "Celestian Sacresants",
    "Celestian Squad",
    "Crusaders",
    "Dialogus",
    "Dogmata",
    "Hospitaller",
    "Imagifier",
    "Paragon Warsuits",
    "Preacher",
    "Repentia Squad"
  ],
  "Fast Attack": [
    "Dominion Squad",
    "Seraphim Squad",
    "Zephyrim Squad"
  ],
  "Heavy Support": [
    "Castigator",
    "Exorcist",
    "Penitent Engines",
    "Retributor Squad"
  ],
  "Dedicated Transport": [
    "Immolator",
    "Rhino"
  ],
  "Fortifications": [],
  "Flyers": [],
  "Lords of War": [
    "Triumphant Procession"
  ]
};

export const faction = "Adeptus Sororitas";
