/**
 * adeptus_sororitas - unit index.
 *
 * Each unit is a PURE JSON file next to this one, so the codex tooling can rewrite it from the
 * sheets without touching any TypeScript. This is the only .ts in the folder: it imports them
 * and exports `faction`, `slot_to_units` and `units` exactly as the old per-slot indexes did.
 *
 * Generated by scripts/convert_units_to_json.cjs. To add a unit, add its .json and one line here.
 */

import type { Unit } from '../../../../src/types/data';

import hq_canoness_in_paragon_warsuit from './hq/canoness_in_paragon_warsuit.json';
import hq_dogmata_on_throne_of_condemnation from './hq/dogmata_on_throne_of_condemnation.json';
import hq_geminae_superia from './hq/geminae_superia.json';
import hq_living_saint from './hq/living_saint.json';
import hq_missionary from './hq/missionary.json';
import hq_palatine from './hq/palatine.json';
import troops_battle_sisters_squad from './troops/battle_sisters_squad.json';
import troops_sisters_novitiate from './troops/sisters_novitiate.json';
import elites_arco_flagellants from './elites/arco_flagellants.json';
import elites_celestian_squad from './elites/celestian_squad.json';
import elites_crusaders from './elites/crusaders.json';
import elites_dogmata from './elites/dogmata.json';
import elites_hospitaller from './elites/hospitaller.json';
import elites_dialogus from './elites/dialogus.json';
import elites_imagifier from './elites/imagifier.json';
import elites_paragon_warsuits from './elites/paragon_warsuits.json';
import elites_preacher from './elites/preacher.json';
import elites_repentia_squad from './elites/repentia_squad.json';
import fast_attack_dominion_squad from './fast_attack/dominion_squad.json';
import fast_attack_seraphim_squad from './fast_attack/seraphim_squad.json';
import fast_attack_zephyrim_squad from './fast_attack/zephyrim_squad.json';
import heavy_support_castigator from './heavy_support/castigator.json';
import heavy_support_exorcist from './heavy_support/exorcist.json';
import heavy_support_penitent_engines from './heavy_support/penitent_engines.json';
import heavy_support_retributor_squad from './heavy_support/retributor_squad.json';
import dedicated_transport_immolator from './dedicated_transport/immolator.json';
import dedicated_transport_rhino from './dedicated_transport/rhino.json';
import lords_of_war_triumphant_procession from './lords_of_war/triumphant_procession.json';

export const faction = "Adeptus Sororitas";

export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Canoness in Paragon Warsuit",
    "Dogmata on Throne of Condemnation",
    "Geminae Superia",
    "Living Saint",
    "Missionary",
    "Palatine"
  ],
  "Troops": [
    "Battle Sisters Squad",
    "Sisters Novitiate"
  ],
  "Elites": [
    "Arco-flagellants",
    "Celestian Squad",
    "Crusaders",
    "Dialogus",
    "Dogmata",
    "Hospitaller",
    "Imagifier",
    "Paragon Warsuits",
    "Preacher",
    "Repentia Squad"
  ],
  "Fast Attack": [
    "Dominion Squad",
    "Seraphim Squad",
    "Zephyrim Squad"
  ],
  "Heavy Support": [
    "Castigator",
    "Exorcist",
    "Penitent Engines",
    "Retributor Squad"
  ],
  "Dedicated Transport": [
    "Immolator",
    "Rhino"
  ],
  "Fortifications": [],
  "Flyers": [],
  "Lords of War": [
    "Triumphant Procession"
  ]
};

/** All units keyed by name. */
export const units: Record<string, Unit> = {
  "Canoness in Paragon Warsuit": hq_canoness_in_paragon_warsuit as Unit,
  "Dogmata on Throne of Condemnation": hq_dogmata_on_throne_of_condemnation as Unit,
  "Geminae Superia": hq_geminae_superia as Unit,
  "Living Saint": hq_living_saint as Unit,
  "Missionary": hq_missionary as Unit,
  "Palatine": hq_palatine as Unit,
  "Battle Sisters Squad": troops_battle_sisters_squad as Unit,
  "Sisters Novitiate": troops_sisters_novitiate as Unit,
  "Arco-flagellants": elites_arco_flagellants as Unit,
  "Celestian Squad": elites_celestian_squad as Unit,
  "Crusaders": elites_crusaders as Unit,
  "Dogmata": elites_dogmata as Unit,
  "Hospitaller": elites_hospitaller as Unit,
  "Dialogus": elites_dialogus as Unit,
  "Imagifier": elites_imagifier as Unit,
  "Paragon Warsuits": elites_paragon_warsuits as Unit,
  "Preacher": elites_preacher as Unit,
  "Repentia Squad": elites_repentia_squad as Unit,
  "Dominion Squad": fast_attack_dominion_squad as Unit,
  "Seraphim Squad": fast_attack_seraphim_squad as Unit,
  "Zephyrim Squad": fast_attack_zephyrim_squad as Unit,
  "Castigator": heavy_support_castigator as Unit,
  "Exorcist": heavy_support_exorcist as Unit,
  "Penitent Engines": heavy_support_penitent_engines as Unit,
  "Retributor Squad": heavy_support_retributor_squad as Unit,
  "Immolator": dedicated_transport_immolator as Unit,
  "Rhino": dedicated_transport_rhino as Unit,
  "Triumphant Procession": lords_of_war_triumphant_procession as Unit,
};
