/**
 * chaos_daemons - unit index.
 *
 * Each unit is a PURE JSON file next to this one, so the codex tooling can rewrite it from the
 * sheets without touching any TypeScript. This is the only .ts in the folder: it imports them
 * and exports `faction`, `slot_to_units` and `units` exactly as the old per-slot indexes did.
 *
 * Generated by scripts/convert_units_to_json.cjs. To add a unit, add its .json and one line here.
 */

import type { Unit } from '../../../../src/types/data';

import hq_bloodmaster from './hq/bloodmaster.json';
import hq_bloodthirster from './hq/bloodthirster.json';
import hq_changecaster from './hq/changecaster.json';
import hq_contorted_epitome from './hq/contorted_epitome.json';
import hq_great_unclean_one from './hq/great_unclean_one.json';
import hq_infernal_enrapturess from './hq/infernal_enrapturess.json';
import hq_keeper_of_secrets from './hq/keeper_of_secrets.json';
import hq_lord_of_change from './hq/lord_of_change.json';
import hq_poxbringer from './hq/poxbringer.json';
import hq_sloppity_bilepiper from './hq/sloppity_bilepiper.json';
import hq_spoilpox_scrivener from './hq/spoilpox_scrivener.json';
import hq_tranceweaver from './hq/tranceweaver.json';
import troops_bloodletters from './troops/bloodletters.json';
import troops_blue_horrors from './troops/blue_horrors.json';
import troops_daemonettes from './troops/daemonettes.json';
import troops_nurglings from './troops/nurglings.json';
import troops_plaguebearers from './troops/plaguebearers.json';
import troops_pink_horrors from './troops/pink_horrors.json';
import elites_beasts_of_nurgle from './elites/beasts_of_nurgle.json';
import elites_bloodcrushers from './elites/bloodcrushers.json';
import elites_fiends from './elites/fiends.json';
import elites_flamers from './elites/flamers.json';
import troops_daemon_brutes from './troops/daemon_brutes.json';
import fast_attack_flesh_hounds from './fast_attack/flesh_hounds.json';
import fast_attack_furies from './fast_attack/furies.json';
import fast_attack_hellflayer from './fast_attack/hellflayer.json';
import fast_attack_plague_drones from './fast_attack/plague_drones.json';
import fast_attack_screamers from './fast_attack/screamers.json';
import fast_attack_seeker_chariot from './fast_attack/seeker_chariot.json';
import fast_attack_seekers from './fast_attack/seekers.json';
import fast_attack_slaughterbrute from './fast_attack/slaughterbrute.json';
import heavy_support_burning_chariot from './heavy_support/burning_chariot.json';
import heavy_support_daemon_prince from './heavy_support/daemon_prince.json';
import heavy_support_mutalith_vortex_beast from './heavy_support/mutalith_vortex_beast.json';
import heavy_support_skull_cannon from './heavy_support/skull_cannon.json';
import heavy_support_soul_grinder from './heavy_support/soul_grinder.json';
import fortifications_feculent_gnarlmaw from './fortifications/feculent_gnarlmaw.json';

export const faction = "Chaos Daemons";

export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Bloodmaster",
    "Bloodthirster",
    "Changecaster",
    "Contorted Epitome",
    "Great Unclean One",
    "Infernal Enrapturess",
    "Keeper of Secrets",
    "Lord of Change",
    "Poxbringer",
    "Sloppity Bilepiper",
    "Spoilpox Scrivener",
    "Tranceweaver"
  ],
  "Troops": [
    "Bloodletters",
    "Blue Horrors",
    "Daemon Brutes",
    "Daemonettes",
    "Nurglings",
    "Plaguebearers",
    "Pink Horrors"
  ],
  "Elites": [
    "Beasts of Nurgle",
    "Bloodcrushers",
    "Fiends",
    "Flamers"
  ],
  "Fast Attack": [
    "Flesh Hounds",
    "Furies",
    "Hellflayer",
    "Plague Drones",
    "Screamers",
    "Seeker Chariot",
    "Seekers",
    "Slaughterbrute"
  ],
  "Heavy Support": [
    "Burning Chariot",
    "Daemon prince",
    "Mutalith Vortex Beast",
    "Skull Cannon",
    "Soul Grinder"
  ],
  "Dedicated Transport": [],
  "Fortifications": [
    "Feculent Gnarlmaw"
  ],
  "Flyers": []
};

/** All units keyed by name. */
export const units: Record<string, Unit> = {
  "Bloodmaster": hq_bloodmaster as Unit,
  "Bloodthirster": hq_bloodthirster as Unit,
  "Changecaster": hq_changecaster as Unit,
  "Contorted Epitome": hq_contorted_epitome as Unit,
  "Great Unclean One": hq_great_unclean_one as Unit,
  "Infernal Enrapturess": hq_infernal_enrapturess as Unit,
  "Keeper of Secrets": hq_keeper_of_secrets as Unit,
  "Lord of Change": hq_lord_of_change as Unit,
  "Poxbringer": hq_poxbringer as Unit,
  "Sloppity Bilepiper": hq_sloppity_bilepiper as Unit,
  "Spoilpox Scrivener": hq_spoilpox_scrivener as Unit,
  "Tranceweaver": hq_tranceweaver as Unit,
  "Bloodletters": troops_bloodletters as Unit,
  "Blue Horrors": troops_blue_horrors as Unit,
  "Daemonettes": troops_daemonettes as Unit,
  "Nurglings": troops_nurglings as Unit,
  "Plaguebearers": troops_plaguebearers as Unit,
  "Pink Horrors": troops_pink_horrors as Unit,
  "Beasts of Nurgle": elites_beasts_of_nurgle as Unit,
  "Bloodcrushers": elites_bloodcrushers as Unit,
  "Fiends": elites_fiends as Unit,
  "Flamers": elites_flamers as Unit,
  "Daemon Brutes": troops_daemon_brutes as Unit,
  "Flesh Hounds": fast_attack_flesh_hounds as Unit,
  "Furies": fast_attack_furies as Unit,
  "Hellflayer": fast_attack_hellflayer as Unit,
  "Plague Drones": fast_attack_plague_drones as Unit,
  "Screamers": fast_attack_screamers as Unit,
  "Seeker Chariot": fast_attack_seeker_chariot as Unit,
  "Seekers": fast_attack_seekers as Unit,
  "Slaughterbrute": fast_attack_slaughterbrute as Unit,
  "Burning Chariot": heavy_support_burning_chariot as Unit,
  "Daemon prince": heavy_support_daemon_prince as Unit,
  "Mutalith Vortex Beast": heavy_support_mutalith_vortex_beast as Unit,
  "Skull Cannon": heavy_support_skull_cannon as Unit,
  "Soul Grinder": heavy_support_soul_grinder as Unit,
  "Feculent Gnarlmaw": fortifications_feculent_gnarlmaw as Unit,
};
