/**
 * Chaos Daemons — unit index
 * Auto-generated by _migrate_units_to_ts.cjs
 * Each unit lives in its own file under units/<slot>/<name>.ts
 * Add SOURCE comments and engine status notes when auditing each unit.
 */

import * as elites from './elites/index';
import * as fastAttack from './fast_attack/index';
import * as fortifications from './fortifications/index';
import * as heavySupport from './heavy_support/index';
import * as hq from './hq/index';
import * as troops from './troops/index';

/** All units keyed by name — drop-in replacement for units.json "units" field. */
export const units: Record<string, import('../../../../src/types/data').Unit> = {
  "Bloodmaster": hq.bloodmaster,
  "Bloodthirster": hq.bloodthirster,
  "Changecaster": hq.changecaster,
  "Contorted Epitome": hq.contortedEpitome,
  "Great Unclean One": hq.greatUncleanOne,
  "Infernal Enrapturess": hq.infernalEnrapturess,
  "Keeper of Secrets": hq.keeperOfSecrets,
  "Lord of Change": hq.lordOfChange,
  "Poxbringer": hq.poxbringer,
  "Sloppity Bilepiper": hq.sloppityBilepiper,
  "Spoilpox Scrivener": hq.spoilpoxScrivener,
  "Tranceweaver": hq.tranceweaver,
  "Bloodletters": troops.bloodletters,
  "Blue Horrors": troops.blueHorrors,
  "Daemonettes": troops.daemonettes,
  "Nurglings": troops.nurglings,
  "Plaguebearers": troops.plaguebearers,
  "Pink Horrors": troops.pinkHorrors,
  "Beasts of Nurgle": elites.beastsOfNurgle,
  "Bloodcrushers": elites.bloodcrushers,
  "Fiends": elites.fiends,
  "Flamers": elites.flamers,
  "Daemon Brutes": elites.daemonBrutes,
  "Flesh Hounds": fastAttack.fleshHounds,
  "Furies": fastAttack.furies,
  "Hellflayer": fastAttack.hellflayer,
  "Plague Drones": fastAttack.plagueDrones,
  "Screamers": fastAttack.screamers,
  "Seeker Chariot": fastAttack.seekerChariot,
  "Seekers": fastAttack.seekers,
  "Slaughterbrute": fastAttack.slaughterbrute,
  "Burning Chariot": heavySupport.burningChariot,
  "Daemon prince": heavySupport.daemonPrince,
  "Mutalith Vortex Beast": heavySupport.mutalithVortexBeast,
  "Skull Cannon": heavySupport.skullCannon,
  "Soul Grinder": heavySupport.soulGrinder,
  "Feculent Gnarlmaw": fortifications.feculentGnarlmaw,
};

/** Slot → unit names map — same as units.json "slot_to_units" field. */
export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Bloodmaster",
    "Bloodthirster",
    "Changecaster",
    "Contorted Epitome",
    "Great Unclean One",
    "Infernal Enrapturess",
    "Keeper of Secrets",
    "Lord of Change",
    "Poxbringer",
    "Sloppity Bilepiper",
    "Spoilpox Scrivener",
    "Tranceweaver"
  ],
  "Troops": [
    "Bloodletters",
    "Blue Horrors",
    "Daemonettes",
    "Nurglings",
    "Plaguebearers",
    "Pink Horrors"
  ],
  "Elites": [
    "Beasts of Nurgle",
    "Bloodcrushers",
    "Daemon Brutes",
    "Fiends",
    "Flamers"
  ],
  "Fast Attack": [
    "Flesh Hounds",
    "Furies",
    "Hellflayer",
    "Plague Drones",
    "Screamers",
    "Seeker Chariot",
    "Seekers",
    "Slaughterbrute"
  ],
  "Heavy Support": [
    "Burning Chariot",
    "Daemon prince",
    "Mutalith Vortex Beast",
    "Skull Cannon",
    "Soul Grinder"
  ],
  "Dedicated Transport": [],
  "Fortifications": [
    "Feculent Gnarlmaw"
  ],
  "Flyers": []
};

export const faction = "Chaos Daemons";
