/**
 * imperial_guard - unit index.
 *
 * Each unit is a PURE JSON file next to this one, so the codex tooling can rewrite it from the
 * sheets without touching any TypeScript. This is the only .ts in the folder: it imports them
 * and exports `faction`, `slot_to_units` and `units` exactly as the old per-slot indexes did.
 *
 * Generated by scripts/convert_units_to_json.cjs. To add a unit, add its .json and one line here.
 */

import type { Unit } from '../../../../src/types/data';

import hq_captain from './hq/captain.json';
import hq_leman_russ_tank_commander from './hq/leman_russ_tank_commander.json';
import hq_lord_commissar from './hq/lord_commissar.json';
import hq_primaris_psyker from './hq/primaris_psyker.json';
import hq_salamander_command from './hq/salamander_command.json';
import troops_conscript_infantry_platoon from './troops/conscript_infantry_platoon.json';
import troops_hive_gangers from './troops/hive_gangers.json';
import troops_infantry_squad from './troops/infantry_squad.json';
import troops_mechanised_infantry from './troops/mechanised_infantry.json';
import troops_penal_legion_squad from './troops/penal_legion_squad.json';
import troops_platoon_command_squad from './troops/platoon_command_squad.json';
import elites_ambassador from './elites/ambassador.json';
import elites_company_hero from './elites/company_hero.json';
import elites_scribe_historicus from './elites/scribe_historicus.json';
import elites_staff_officer from './elites/staff_officer.json';
import elites_astropath from './elites/astropath.json';
import elites_atlas_recovery_vehicle from './elites/atlas_recovery_vehicle.json';
import elites_bullgryns from './elites/bullgryns.json';
import elites_commissar from './elites/commissar.json';
import elites_company_command_squad from './elites/company_command_squad.json';
import elites_crusaders from './elites/crusaders.json';
import elites_engineseer from './elites/engineseer.json';
import elites_leman_russ_commissar from './elites/leman_russ_commissar.json';
import elites_master_of_ordnance from './elites/master_of_ordnance.json';
import elites_officer_of_the_fleet from './elites/officer_of_the_fleet.json';
import elites_ogryn_bodyguard from './elites/ogryn_bodyguard.json';
import elites_ogryn_brutes from './elites/ogryn_brutes.json';
import elites_ogryns from './elites/ogryns.json';
import elites_preacher from './elites/preacher.json';
import elites_ratlings from './elites/ratlings.json';
import elites_sanctioned_psykers from './elites/sanctioned_psykers.json';
import elites_special_weapon_squad from './elites/special_weapon_squad.json';
import elites_stormtrooper_command_squad from './elites/stormtrooper_command_squad.json';
import elites_stormtroopers from './elites/stormtroopers.json';
import elites_veterans from './elites/veterans.json';
import fast_attack_combat_engineers from './fast_attack/combat_engineers.json';
import fast_attack_hellhounds from './fast_attack/hellhounds.json';
import fast_attack_hippogriff_afv from './fast_attack/hippogriff_afv.json';
import fast_attack_rough_riders from './fast_attack/rough_riders.json';
import fast_attack_salamander_scout from './fast_attack/salamander_scout.json';
import fast_attack_sentinel from './fast_attack/sentinel.json';
import fast_attack_tauros from './fast_attack/tauros.json';
import fast_attack_armoured_sentinels from './fast_attack/armoured_sentinels.json';
import heavy_support_basilisk from './heavy_support/basilisk.json';
import heavy_support_carnodon from './heavy_support/carnodon.json';
import heavy_support_colossus_bombard from './heavy_support/colossus_bombard.json';
import heavy_support_deathstrike_missile_launcher from './heavy_support/deathstrike_missile_launcher.json';
import heavy_support_destroyer_tank_hunter from './heavy_support/destroyer_tank_hunter.json';
import heavy_support_field_ordnance_battery from './heavy_support/field_ordnance_battery.json';
import heavy_support_griffon from './heavy_support/griffon.json';
import heavy_support_heavy_ordnance_carriage from './heavy_support/heavy_ordnance_carriage.json';
import heavy_support_heavy_weapon_squad from './heavy_support/heavy_weapon_squad.json';
import heavy_support_hydra from './heavy_support/hydra.json';
import heavy_support_leman_russ from './heavy_support/leman_russ.json';
import heavy_support_malcador from './heavy_support/malcador.json';
import heavy_support_manticore from './heavy_support/manticore.json';
import heavy_support_medusa from './heavy_support/medusa.json';
import heavy_support_rogal_dorn from './heavy_support/rogal_dorn.json';
import heavy_support_wyvern from './heavy_support/wyvern.json';
import dedicated_transport_centaur_carrier from './dedicated_transport/centaur_carrier.json';
import dedicated_transport_centaur_rsv from './dedicated_transport/centaur_rsv.json';
import dedicated_transport_chimera from './dedicated_transport/chimera.json';
import dedicated_transport_vigilator_rsv from './dedicated_transport/vigilator_rsv.json';
import dedicated_transport_taurox from './dedicated_transport/taurox.json';
import dedicated_transport_trojan from './dedicated_transport/trojan.json';
import dedicated_transport_valkyrie from './dedicated_transport/valkyrie.json';
import flyers_vendetta from './flyers/vendetta.json';
import lords_of_war_baneblade from './lords_of_war/baneblade.json';
import lords_of_war_gorgon_heavy_transport from './lords_of_war/gorgon_heavy_transport.json';
import lords_of_war_stormlord from './lords_of_war/stormlord.json';

export const faction = "Imperial Guard";

export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Captain",
    "Leman Russ Tank Commander",
    "Lord Commissar",
    "Primaris Psyker",
    "Salamander Command"
  ],
  "Troops": [
    "Conscript Infantry Platoon",
    "Hive Gangers",
    "Infantry Squad",
    "Mechanised Infantry",
    "Penal Legion Squad",
    "Platoon Command Squad"
  ],
  "Elites": [
    "Staff Officer",
    "Scribe Historicus",
    "Company Hero",
    "Ambassador",
    "Astropath",
    "Atlas",
    "Bullgryns",
    "Commissar",
    "Company Command Squad",
    "Crusaders",
    "Engineseer",
    "Leman Russ Commissar",
    "Master of Ordnance",
    "Officer of the Fleet",
    "Ogryn Bodyguard",
    "Ogryn Brutes",
    "Ogryns",
    "Preacher",
    "Ratlings",
    "Sanctioned Psykers",
    "Special Weapon Squad",
    "Stormtrooper Command Squad",
    "Stormtroopers",
    "Veterans"
  ],
  "Fast Attack": [
    "Armoured Sentinel",
    "Combat Engineers",
    "Hellhounds",
    "Hippogriff AFV",
    "Rough Riders",
    "Salamander Scout",
    "Sentinel",
    "Tauros"
  ],
  "Heavy Support": [
    "Basilisk",
    "Carnodon",
    "Colossus Bombard",
    "Deathstrike Missile Launcher",
    "Destroyer Tank Hunter",
    "Field Ordnance Battery",
    "Griffon",
    "Heavy Ordnance Carriage",
    "Heavy Weapon Squad",
    "Hydra",
    "Leman Russ",
    "Malcador",
    "Manticore",
    "Medusa",
    "Rogal Dorn",
    "Wyvern"
  ],
  "Dedicated Transport": [
    "Centaur Carrier",
    "Centaur RSV",
    "Chimera",
    "Vigilator RSV",
    "Taurox",
    "Trojan",
    "Valkyrie"
  ],
  "Fortifications": [],
  "Flyers": [
    "Vendetta"
  ],
  "Lords of War": [
    "Baneblade",
    "Gorgon Heavy Transport",
    "Stormlord"
  ]
};

/** All units keyed by name. */
export const units: Record<string, Unit> = {
  "Captain": hq_captain as Unit,
  "Leman Russ Tank Commander": hq_leman_russ_tank_commander as Unit,
  "Lord Commissar": hq_lord_commissar as Unit,
  "Primaris Psyker": hq_primaris_psyker as Unit,
  "Salamander Command": hq_salamander_command as Unit,
  "Conscript Infantry Platoon": troops_conscript_infantry_platoon as Unit,
  "Hive Gangers": troops_hive_gangers as Unit,
  "Infantry Squad": troops_infantry_squad as Unit,
  "Mechanised Infantry": troops_mechanised_infantry as Unit,
  "Penal Legion Squad": troops_penal_legion_squad as Unit,
  "Platoon Command Squad": troops_platoon_command_squad as Unit,
  "Ambassador": elites_ambassador as Unit,
  "Company Hero": elites_company_hero as Unit,
  "Scribe Historicus": elites_scribe_historicus as Unit,
  "Staff Officer": elites_staff_officer as Unit,
  "Astropath": elites_astropath as Unit,
  "Atlas": elites_atlas_recovery_vehicle as Unit,
  "Bullgryns": elites_bullgryns as Unit,
  "Commissar": elites_commissar as Unit,
  "Company Command Squad": elites_company_command_squad as Unit,
  "Crusaders": elites_crusaders as Unit,
  "Engineseer": elites_engineseer as Unit,
  "Leman Russ Commissar": elites_leman_russ_commissar as Unit,
  "Master of Ordnance": elites_master_of_ordnance as Unit,
  "Officer of the Fleet": elites_officer_of_the_fleet as Unit,
  "Ogryn Bodyguard": elites_ogryn_bodyguard as Unit,
  "Ogryn Brutes": elites_ogryn_brutes as Unit,
  "Ogryns": elites_ogryns as Unit,
  "Preacher": elites_preacher as Unit,
  "Ratlings": elites_ratlings as Unit,
  "Sanctioned Psykers": elites_sanctioned_psykers as Unit,
  "Special Weapon Squad": elites_special_weapon_squad as Unit,
  "Stormtrooper Command Squad": elites_stormtrooper_command_squad as Unit,
  "Stormtroopers": elites_stormtroopers as Unit,
  "Veterans": elites_veterans as Unit,
  "Combat Engineers": fast_attack_combat_engineers as Unit,
  "Hellhounds": fast_attack_hellhounds as Unit,
  "Hippogriff AFV": fast_attack_hippogriff_afv as Unit,
  "Rough Riders": fast_attack_rough_riders as Unit,
  "Salamander Scout": fast_attack_salamander_scout as Unit,
  "Sentinel": fast_attack_sentinel as Unit,
  "Tauros": fast_attack_tauros as Unit,
  "Armoured Sentinel": fast_attack_armoured_sentinels as Unit,
  "Basilisk": heavy_support_basilisk as Unit,
  "Carnodon": heavy_support_carnodon as Unit,
  "Colossus Bombard": heavy_support_colossus_bombard as Unit,
  "Deathstrike Missile Launcher": heavy_support_deathstrike_missile_launcher as Unit,
  "Destroyer Tank Hunter": heavy_support_destroyer_tank_hunter as Unit,
  "Field Ordnance Battery": heavy_support_field_ordnance_battery as Unit,
  "Griffon": heavy_support_griffon as Unit,
  "Heavy Ordnance Carriage": heavy_support_heavy_ordnance_carriage as Unit,
  "Heavy Weapon Squad": heavy_support_heavy_weapon_squad as Unit,
  "Hydra": heavy_support_hydra as Unit,
  "Leman Russ": heavy_support_leman_russ as Unit,
  "Malcador": heavy_support_malcador as Unit,
  "Manticore": heavy_support_manticore as Unit,
  "Medusa": heavy_support_medusa as Unit,
  "Rogal Dorn": heavy_support_rogal_dorn as Unit,
  "Wyvern": heavy_support_wyvern as Unit,
  "Centaur Carrier": dedicated_transport_centaur_carrier as Unit,
  "Centaur RSV": dedicated_transport_centaur_rsv as Unit,
  "Chimera": dedicated_transport_chimera as Unit,
  "Vigilator RSV": dedicated_transport_vigilator_rsv as Unit,
  "Taurox": dedicated_transport_taurox as Unit,
  "Trojan": dedicated_transport_trojan as Unit,
  "Valkyrie": dedicated_transport_valkyrie as Unit,
  "Vendetta": flyers_vendetta as Unit,
  "Baneblade": lords_of_war_baneblade as Unit,
  "Gorgon Heavy Transport": lords_of_war_gorgon_heavy_transport as Unit,
  "Stormlord": lords_of_war_stormlord as Unit,
};
