/**
 * Imperial Guard — unit index
 * Auto-generated by _migrate_units_to_ts.cjs
 * Each unit lives in its own file under units/<slot>/<name>.ts
 * Add SOURCE comments and engine status notes when auditing each unit.
 */

import * as dedicatedTransport from './dedicated_transport/index';
import * as elites from './elites/index';
import * as fastAttack from './fast_attack/index';
import * as flyers from './flyers/index';
import * as heavySupport from './heavy_support/index';
import * as hq from './hq/index';
import * as lordsOfWar from './lords_of_war/index';
import * as troops from './troops/index';

/** All units keyed by name — drop-in replacement for units.json "units" field. */
export const units: Record<string, import('../../../../src/types/data').Unit> = {
  "Captain": hq.captain,
  "Leman Russ Tank Commander": hq.lemanRussTankCommander,
  "Lord Commissar": hq.lordCommissar,
  "Primaris Psyker": hq.primarisPsyker,
  "Salamander Command": hq.salamanderCommand,
  "Conscript Infantry Platoon": troops.conscriptInfantryPlatoon,
  "Hive Gangers": troops.hiveGangers,
  "Infantry Squad": troops.infantrySquad,
  "Mechanised Infantry": troops.mechanisedInfantry,
  "Penal Legion Squad": troops.penalLegionSquad,
  "Platoon Command Squad": troops.platoonCommandSquad,
  "Astropath": elites.astropath,
  "Atlas Recovery Vehicle": elites.atlasRecoveryVehicle,
  "Bullgryns": elites.bullgryns,
  "Commissar": elites.commissar,
  "Company Command Squad": elites.companyCommandSquad,
  "Crusaders": elites.crusaders,
  "Engineseer": elites.engineseer,
  "Leman Russ Commissar": elites.lemanRussCommissar,
  "Master of Ordnance": elites.masterOfOrdnance,
  "Officer of the Fleet": elites.officerOfTheFleet,
  "Ogryn Bodyguard": elites.ogrynBodyguard,
  "Ogryn Brutes": elites.ogrynBrutes,
  "Ogryns": elites.ogryns,
  "Preacher": elites.preacher,
  "Ratlings": elites.ratlings,
  "Sanctioned Psykers": elites.sanctionedPsykers,
  "Special Weapon Squad": elites.specialWeaponSquad,
  "Stormtrooper Command Squad": elites.stormtrooperCommandSquad,
  "Stormtroopers": elites.stormtroopers,
  "Veterans": elites.veterans,
  "Combat Engineers": fastAttack.combatEngineers,
  "Hellhounds": fastAttack.hellhounds,
  "Hippogriff AFV": fastAttack.hippogriffAfv,
  "Rough Riders": fastAttack.roughRiders,
  "Salamander Scout": fastAttack.salamanderScout,
  "Sentinel": fastAttack.sentinel,
  "Tauros": fastAttack.tauros,
  "Armoured Sentinels": fastAttack.armouredSentinels,
  "Basilisk": heavySupport.basilisk,
  "Carnodon": heavySupport.carnodon,
  "Colossus Bombard": heavySupport.colossusBombard,
  "Deathstrike Missile Launcher": heavySupport.deathstrikeMissileLauncher,
  "Destroyer Tank Hunter": heavySupport.destroyerTankHunter,
  "Field Ordnance Battery": heavySupport.fieldOrdnanceBattery,
  "Griffon": heavySupport.griffon,
  "Heavy Ordnance Carriage": heavySupport.heavyOrdnanceCarriage,
  "Heavy Weapon Squad": heavySupport.heavyWeaponSquad,
  "Hydra": heavySupport.hydra,
  "Leman Russ": heavySupport.lemanRuss,
  "Malcador": heavySupport.malcador,
  "Manticore": heavySupport.manticore,
  "Medusa": heavySupport.medusa,
  "Rogal Dorn": heavySupport.rogalDorn,
  "Wyvern": heavySupport.wyvern,
  "Centaur Carrier": dedicatedTransport.centaurCarrier,
  "Centaur RSV": dedicatedTransport.centaurRsv,
  "Chimera": dedicatedTransport.chimera,
  "Vigilator RSV": dedicatedTransport.vigilatorRsv,
  "Taurox": dedicatedTransport.taurox,
  "Trojan": dedicatedTransport.trojan,
  "Valkyrie": dedicatedTransport.valkyrie,
  "Vendetta": flyers.vendetta,
  "Baneblade": lordsOfWar.baneblade,
  "Gorgon Heavy Transport": lordsOfWar.gorgonHeavyTransport,
  "Stormlord": lordsOfWar.stormlord,
};

/** Slot → unit names map — same as units.json "slot_to_units" field. */
export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Captain",
    "Leman Russ Tank Commander",
    "Lord Commissar",
    "Primaris Psyker",
    "Salamander Command"
  ],
  "Troops": [
    "Conscript Infantry Platoon",
    "Hive Gangers",
    "Infantry Squad",
    "Mechanised Infantry",
    "Penal Legion Squad",
    "Platoon Command Squad"
  ],
  "Elites": [
    "Astropath",
    "Atlas Recovery Vehicle",
    "Bullgryns",
    "Commissar",
    "Company Command Squad",
    "Crusaders",
    "Engineseer",
    "Leman Russ Commissar",
    "Master of Ordnance",
    "Officer of the Fleet",
    "Ogryn Bodyguard",
    "Ogryn Brutes",
    "Ogryns",
    "Preacher",
    "Ratlings",
    "Sanctioned Psykers",
    "Special Weapon Squad",
    "Stormtrooper Command Squad",
    "Stormtroopers",
    "Veterans"
  ],
  "Fast Attack": [
    "Armoured Sentinels",
    "Combat Engineers",
    "Hellhounds",
    "Hippogriff AFV",
    "Rough Riders",
    "Salamander Scout",
    "Sentinel",
    "Tauros"
  ],
  "Heavy Support": [
    "Basilisk",
    "Carnodon",
    "Colossus Bombard",
    "Deathstrike Missile Launcher",
    "Destroyer Tank Hunter",
    "Field Ordnance Battery",
    "Griffon",
    "Heavy Ordnance Carriage",
    "Heavy Weapon Squad",
    "Hydra",
    "Leman Russ",
    "Malcador",
    "Manticore",
    "Medusa",
    "Rogal Dorn",
    "Wyvern"
  ],
  "Dedicated Transport": [
    "Centaur Carrier",
    "Centaur RSV",
    "Chimera",
    "Vigilator RSV",
    "Taurox",
    "Trojan",
    "Valkyrie"
  ],
  "Fortifications": [],
  "Flyers": [
    "Vendetta"
  ],
  "Lords of War": [
    "Baneblade",
    "Gorgon Heavy Transport",
    "Stormlord"
  ]
};

export const faction = "Imperial Guard";
