/**
 * Genestealer Cults — unit index
 * Auto-generated by _migrate_units_to_ts.cjs
 * Each unit lives in its own file under units/<slot>/<name>.ts
 * Add SOURCE comments and engine status notes when auditing each unit.
 */

import * as dedicatedTransport from './dedicated_transport/index';
import * as elites from './elites/index';
import * as fastAttack from './fast_attack/index';
import * as heavySupport from './heavy_support/index';
import * as hq from './hq/index';
import * as troops from './troops/index';

/** All units keyed by name — drop-in replacement for units.json "units" field. */
export const units: Record<string, import('../../../../src/types/data').Unit> = {
  "Acolyte Iconward": hq.acolyteIconward,
  "Magus": hq.magus,
  "Patriarch": hq.patriarch,
  "Primus": hq.primus,
  "Acolyte Hybrids": troops.acolyteHybrids,
  "Neophyte Hybrids": troops.neophyteHybrids,
  "Abberants": elites.abberants,
  "Abominant": elites.abominant,
  "Biophagus": elites.biophagus,
  "Clamavus": elites.clamavus,
  "Nexos": elites.nexos,
  "Purestrain Genestealers": elites.purestrainGenestealers,
  "Reductus Saboteur": elites.reductusSaboteur,
  "Sanctus": elites.sanctus,
  "Kelermorph": elites.kelermorph,
  "Locus": elites.locus,
  "Achilles Ridgerunners": fastAttack.achillesRidgerunners,
  "Atalan Jackals": fastAttack.atalanJackals,
  "Goliath Rockgrinder": heavySupport.goliathRockgrinder,
  "Goliath Truck": dedicatedTransport.goliathTruck,
};

/** Slot → unit names map — same as units.json "slot_to_units" field. */
export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Acolyte Iconward",
    "Magus",
    "Patriarch",
    "Primus"
  ],
  "Troops": [
    "Acolyte Hybrids",
    "Neophyte Hybrids"
  ],
  "Elites": [
    "Abberants",
    "Abominant",
    "Biophagus",
    "Clamavus",
    "Nexos",
    "Purestrain Genestealers",
    "Reductus Saboteur",
    "Sanctus",
    "Kelermorph",
    "Locus"
  ],
  "Fast Attack": [
    "Achilles Ridgerunners",
    "Atalan Jackals"
  ],
  "Heavy Support": [
    "Goliath Rockgrinder"
  ],
  "Dedicated Transport": [
    "Goliath Truck"
  ],
  "Fortifications": [],
  "Flyers": []
};

export const faction = "Genestealer Cults";
