/**
 * genestealer_cults - unit index.
 *
 * Each unit is a PURE JSON file next to this one, so the codex tooling can rewrite it from the
 * sheets without touching any TypeScript. This is the only .ts in the folder: it imports them
 * and exports `faction`, `slot_to_units` and `units` exactly as the old per-slot indexes did.
 *
 * Generated by scripts/convert_units_to_json.cjs. To add a unit, add its .json and one line here.
 */

import type { Unit } from '../../../../src/types/data';

import hq_acolyte_iconward from './hq/acolyte_iconward.json';
import hq_magus from './hq/magus.json';
import hq_patriarch from './hq/patriarch.json';
import hq_primus from './hq/primus.json';
import troops_acolyte_hybrids from './troops/acolyte_hybrids.json';
import troops_neophyte_hybrids from './troops/neophyte_hybrids.json';
import elites_abberants from './elites/abberants.json';
import elites_abominant from './elites/abominant.json';
import elites_biophagus from './elites/biophagus.json';
import elites_clamavus from './elites/clamavus.json';
import elites_nexos from './elites/nexos.json';
import elites_purestrain_genestealers from './elites/purestrain_genestealers.json';
import elites_reductus_saboteur from './elites/reductus_saboteur.json';
import elites_sanctus from './elites/sanctus.json';
import elites_kelermorph from './elites/kelermorph.json';
import elites_locus from './elites/locus.json';
import fast_attack_achilles_ridgerunners from './fast_attack/achilles_ridgerunners.json';
import fast_attack_atalan_jackals from './fast_attack/atalan_jackals.json';
import heavy_support_goliath_rockgrinder from './heavy_support/goliath_rockgrinder.json';
import dedicated_transport_goliath_truck from './dedicated_transport/goliath_truck.json';

export const faction = "Genestealer Cults";

export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Acolyte Iconward",
    "Magus",
    "Patriarch",
    "Primus"
  ],
  "Troops": [
    "Acolyte Hybrids",
    "Neophyte Hybrids"
  ],
  "Elites": [
    "Aberrants",
    "Abominant",
    "Biophagus",
    "Clamavus",
    "Nexos",
    "Purestrain Genestealers",
    "Reductus Saboteur",
    "Sanctus",
    "Kelermorph",
    "Locus"
  ],
  "Fast Attack": [
    "Achilles Ridgerunners",
    "Atalan Jackals"
  ],
  "Heavy Support": [
    "Goliath Rockgrinder"
  ],
  "Dedicated Transport": [
    "Goliath Truck"
  ],
  "Fortifications": [],
  "Flyers": []
};

/** All units keyed by name. */
export const units: Record<string, Unit> = {
  "Acolyte Iconward": hq_acolyte_iconward as Unit,
  "Magus": hq_magus as Unit,
  "Patriarch": hq_patriarch as Unit,
  "Primus": hq_primus as Unit,
  "Acolyte Hybrids": troops_acolyte_hybrids as Unit,
  "Neophyte Hybrids": troops_neophyte_hybrids as Unit,
  "Aberrants": elites_abberants as Unit,
  "Abominant": elites_abominant as Unit,
  "Biophagus": elites_biophagus as Unit,
  "Clamavus": elites_clamavus as Unit,
  "Nexos": elites_nexos as Unit,
  "Purestrain Genestealers": elites_purestrain_genestealers as Unit,
  "Reductus Saboteur": elites_reductus_saboteur as Unit,
  "Sanctus": elites_sanctus as Unit,
  "Kelermorph": elites_kelermorph as Unit,
  "Locus": elites_locus as Unit,
  "Achilles Ridgerunners": fast_attack_achilles_ridgerunners as Unit,
  "Atalan Jackals": fast_attack_atalan_jackals as Unit,
  "Goliath Rockgrinder": heavy_support_goliath_rockgrinder as Unit,
  "Goliath Truck": dedicated_transport_goliath_truck as Unit,
};
