/**
 * Convert a supplement from ONE json file (data/parsed/_supplements/<name>.json) into the same
 * per-faction folder layout the regular factions use, so Unwise's unit update can rewrite it:
 *
 *   data/parsed/<name>/units/<slot>/<unit>.json   one pure-JSON file per unit
 *   data/parsed/<name>/units/index.ts             faction, slot_to_units, units (same exports as every faction)
 *   data/parsed/<name>/supplement.json            everything that is NOT a unit (armory, daemonkin, ...)
 *
 * The unit file name is the sheet name the update script derives: lower case, spaces -> "_", no
 * apostrophes. Run:  node scripts/convert_supplement_to_folders.cjs horus_heresy [--write]
 */
const fs = require('fs');
const path = require('path');

const name = process.argv[2];
const write = process.argv.includes('--write');
if (!name) { console.error('usage: node scripts/convert_supplement_to_folders.cjs <name> [--write]'); process.exit(1); }

const src = path.join('data', 'parsed', '_supplements', `${name}.json`);
const data = JSON.parse(fs.readFileSync(src, 'utf8').replace(/^﻿/, ''));
const root = path.join('data', 'parsed', process.argv[3] || name);

const SLOT_DIR = {
  'HQ': 'hq', 'Troops': 'troops', 'Elites': 'elites', 'Fast Attack': 'fast_attack',
  'Heavy Support': 'heavy_support', 'Dedicated Transport': 'dedicated_transport',
  'Fortifications': 'fortifications', 'Flyers': 'flyers',
};
const fileOf = unitName => unitName.toLowerCase().replace(/'/g, '').replace(/ /g, '_');

const slotOf = {};
for (const [slot, names] of Object.entries(data.slot_to_units)) for (const n of names) slotOf[n] = slot;

const imports = [];
const unitLines = [];
for (const [unitName, unit] of Object.entries(data.units)) {
  const slot = slotOf[unitName] ?? unit.slot;
  const dir = SLOT_DIR[slot];
  if (!dir) throw new Error(`no slot for ${unitName}`);
  const file = fileOf(unitName);
  const ident = `${dir}_${file.replace(/[^a-z0-9_]/g, '_')}`;
  imports.push(`import ${ident} from './${dir}/${file}.json';`);
  unitLines.push(`  ${JSON.stringify(unitName)}: ${ident} as Unit,`);
  if (write) {
    fs.mkdirSync(path.join(root, 'units', dir), { recursive: true });
    fs.writeFileSync(path.join(root, 'units', dir, `${file}.json`), JSON.stringify(unit, null, 4) + '\n', 'utf8');
  }
  console.log(`${unitName}  ->  units/${dir}/${file}.json`);
}

const index = `/**
 * ${name} - unit index.
 *
 * Each unit is a PURE JSON file next to this one, so the codex tooling can rewrite it from the
 * sheets without touching any TypeScript. This is the only .ts in the folder: it imports them
 * and exports \`faction\`, \`slot_to_units\` and \`units\` exactly as the regular factions do.
 * Everything that is not a unit (armory, daemonkin, ...) is in ../supplement.json.
 *
 * Generated by scripts/convert_supplement_to_folders.cjs. To add a unit, add its .json and one line here.
 */

import type { Unit } from '../../../../src/types/data';

${imports.join('\n')}

export const faction = ${JSON.stringify(data.faction)};

export const slot_to_units: Record<string, string[]> = ${JSON.stringify(data.slot_to_units, null, 2)};

/** All units keyed by name. */
export const units: Record<string, Unit> = {
${unitLines.join('\n')}
};
`;

const rest = {};
for (const [k, v] of Object.entries(data)) if (!['faction', 'slot_to_units', 'units'].includes(k)) rest[k] = v;

if (write) {
  fs.writeFileSync(path.join(root, 'units', 'index.ts'), index, 'utf8');
  fs.writeFileSync(path.join(root, 'supplement.json'), JSON.stringify(rest, null, 2) + '\n', 'utf8');
  console.log('written to', root);
} else {
  console.log('dry run — pass --write');
}
