/**
 * Leagues of Votann — unit index
 * Auto-generated by _migrate_units_to_ts.cjs
 * Each unit lives in its own file under units/<slot>/<name>.ts
 * Add SOURCE comments and engine status notes when auditing each unit.
 */

import * as dedicatedTransport from './dedicated_transport/index';
import * as elites from './elites/index';
import * as fastAttack from './fast_attack/index';
import * as heavySupport from './heavy_support/index';
import * as hq from './hq/index';
import * as troops from './troops/index';

/** All units keyed by name — drop-in replacement for units.json "units" field. */
export const units: Record<string, import('../../../../src/types/data').Unit> = {
  "Brôkhyr Iron-master": hq.brKhyrIronMaster,
  "Grimnyr": hq.grimnyr,
  "Kâhl": hq.kHl,
  "Hearthkyn Warriors": troops.hearthkynWarriors,
  "Ironkin Steeljacks": troops.ironkinSteeljacks,
  "Arkanyst Evaluator": elites.arkanystEvaluator,
  "Cthonian Beserks": elites.cthonianBeserks,
  "Einhyr Champion": elites.einhyrChampion,
  "Einhyr Hearthguard": elites.einhyrHearthguard,
  "Hernkyn Yaegirs": elites.hernkynYaegirs,
  "Memnyr Strategist": elites.memnyrStrategist,
  "Hernkyn Pioneers": fastAttack.hernkynPioneers,
  "Kapricus Defender": fastAttack.kapricusDefender,
  "Brôkhyr Thunderkyn": heavySupport.brKhyrThunderkyn,
  "Cthonian Earthshakers": heavySupport.cthonianEarthshakers,
  "Hekaton Land Fortress": heavySupport.hekatonLandFortress,
  "Kapricus Carrier": dedicatedTransport.kapricusCarrier,
  "Sagitaur": dedicatedTransport.sagitaur,
};

/** Slot → unit names map — same as units.json "slot_to_units" field. */
export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Brôkhyr Iron-master",
    "Grimnyr",
    "Kâhl"
  ],
  "Troops": [
    "Hearthkyn Warriors",
    "Ironkin Steeljacks"
  ],
  "Elites": [
    "Arkanyst Evaluator",
    "Cthonian Beserks",
    "Einhyr Champion",
    "Einhyr Hearthguard",
    "Hernkyn Yaegirs",
    "Memnyr Strategist"
  ],
  "Fast Attack": [
    "Hernkyn Pioneers",
    "Kapricus Defender"
  ],
  "Heavy Support": [
    "Brôkhyr Thunderkyn",
    "Cthonian Earthshakers",
    "Hekaton Land Fortress"
  ],
  "Dedicated Transport": [
    "Kapricus Carrier",
    "Sagitaur"
  ],
  "Fortifications": [],
  "Flyers": []
};

export const faction = "Leagues of Votann";
