/**
 * leagues_of_votann - unit index.
 *
 * Each unit is a PURE JSON file next to this one, so the codex tooling can rewrite it from the
 * sheets without touching any TypeScript. This is the only .ts in the folder: it imports them
 * and exports `faction`, `slot_to_units` and `units` exactly as the old per-slot indexes did.
 *
 * Generated by scripts/convert_units_to_json.cjs. To add a unit, add its .json and one line here.
 */

import type { Unit } from '../../../../src/types/data';

import hq_br_khyr_iron_master from './hq/brôkhyr_iron-master.json';
import hq_grimnyr from './hq/grimnyr.json';
import hq_k_hl from './hq/kâhl.json';
import troops_hearthkyn_warriors from './troops/hearthkyn_warriors.json';
import troops_ironkin_steeljacks from './troops/ironkin_steeljacks.json';
import elites_arkanyst_evaluator from './elites/arkanyst_evaluator.json';
import elites_cthonian_beserks from './elites/cthonian_beserks.json';
import elites_einhyr_champion from './elites/einhyr_champion.json';
import elites_einhyr_hearthguard from './elites/einhyr_hearthguard.json';
import elites_hernkyn_yaegirs from './elites/hernkyn_yaegirs.json';
import elites_memnyr_strategist from './elites/memnyr_strategist.json';
import fast_attack_hearthkyn_skyriggers from './fast_attack/hearthkyn_skyriggers.json';
import fast_attack_hernkyn_pioneers from './fast_attack/hernkyn_pioneers.json';
import fast_attack_kapricus_defender from './fast_attack/kapricus_defender.json';
import heavy_support_br_khyr_thunderkyn from './heavy_support/brôkhyr_thunderkyn.json';
import heavy_support_cthonian_earthshakers from './heavy_support/cthonian_earthshakers.json';
import heavy_support_hekaton_land_fortress from './heavy_support/hekaton_land_fortress.json';
import dedicated_transport_kapricus_carrier from './dedicated_transport/kapricus_carrier.json';
import dedicated_transport_sagitaur from './dedicated_transport/sagitaur.json';

export const faction = "Leagues of Votann";

export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Brôkhyr Iron-master",
    "Grimnyr",
    "Kâhl"
  ],
  "Troops": [
    "Hearthkyn Warriors",
    "Ironkin Steeljacks"
  ],
  "Elites": [
    "Arkanyst Evaluator",
    "Cthonian Beserks",
    "Einhyr Champion",
    "Einhyr Hearthguard",
    "Hernkyn Yaegirs",
    "Memnyr Strategist"
  ],
  "Fast Attack": [
    "Hearthkyn Skyriggers",
    "Hernkyn Pioneers",
    "Kapricus Defender"
  ],
  "Heavy Support": [
    "Brôkhyr Thunderkyn",
    "Cthonian Earthshakers",
    "Hekaton Land Fortress"
  ],
  "Dedicated Transport": [
    "Kapricus Carrier",
    "Sagitaur"
  ],
  "Fortifications": [],
  "Flyers": []
};

/** All units keyed by name. */
export const units: Record<string, Unit> = {
  "Brôkhyr Iron-master": hq_br_khyr_iron_master as Unit,
  "Grimnyr": hq_grimnyr as Unit,
  "Kâhl": hq_k_hl as Unit,
  "Hearthkyn Warriors": troops_hearthkyn_warriors as Unit,
  "Ironkin Steeljacks": troops_ironkin_steeljacks as Unit,
  "Arkanyst Evaluator": elites_arkanyst_evaluator as Unit,
  "Cthonian Beserks": elites_cthonian_beserks as Unit,
  "Einhyr Champion": elites_einhyr_champion as Unit,
  "Einhyr Hearthguard": elites_einhyr_hearthguard as Unit,
  "Hernkyn Yaegirs": elites_hernkyn_yaegirs as Unit,
  "Memnyr Strategist": elites_memnyr_strategist as Unit,
  "Hearthkyn Skyriggers": fast_attack_hearthkyn_skyriggers as Unit,
  "Hernkyn Pioneers": fast_attack_hernkyn_pioneers as Unit,
  "Kapricus Defender": fast_attack_kapricus_defender as Unit,
  "Brôkhyr Thunderkyn": heavy_support_br_khyr_thunderkyn as Unit,
  "Cthonian Earthshakers": heavy_support_cthonian_earthshakers as Unit,
  "Hekaton Land Fortress": heavy_support_hekaton_land_fortress as Unit,
  "Kapricus Carrier": dedicated_transport_kapricus_carrier as Unit,
  "Sagitaur": dedicated_transport_sagitaur as Unit,
};
