/**
 * assassins - unit index.
 *
 * Each unit is a PURE JSON file next to this one, so the codex tooling can rewrite it from the
 * sheets without touching any TypeScript. This is the only .ts in the folder: it imports them
 * and exports `faction`, `slot_to_units` and `units` exactly as the old per-slot indexes did.
 *
 * Generated by scripts/convert_units_to_json.cjs. To add a unit, add its .json and one line here.
 */

import type { Unit } from '../../../../src/types/data';

import elites_callidus from './elites/callidus.json';
import elites_culexus from './elites/culexus.json';
import elites_eversor from './elites/eversor.json';
import elites_vindicare from './elites/vindicare.json';

export const faction = "Assassins";

export const slot_to_units: Record<string, string[]> = {
  "HQ": [],
  "Troops": [],
  "Elites": [
    "Callidus",
    "Culexus",
    "Eversor",
    "Vindicare"
  ],
  "Fast Attack": [],
  "Heavy Support": [],
  "Dedicated Transport": [],
  "Fortifications": [],
  "Flyers": []
};

/** All units keyed by name. */
export const units: Record<string, Unit> = {
  "Callidus": elites_callidus as Unit,
  "Culexus": elites_culexus as Unit,
  "Eversor": elites_eversor as Unit,
  "Vindicare": elites_vindicare as Unit,
};
