/**
 * Assassins — unit index
 * Auto-generated by _migrate_units_to_ts.cjs
 * Each unit lives in its own file under units/<slot>/<name>.ts
 * Add SOURCE comments and engine status notes when auditing each unit.
 */

import * as elites from './elites/index';

/** All units keyed by name — drop-in replacement for units.json "units" field. */
export const units: Record<string, import('../../../../src/types/data').Unit> = {
  "Callidus": elites.callidus,
  "Culexus": elites.culexus,
  "Eversor": elites.eversor,
  "Vindicare": elites.vindicare,
};

/** Slot → unit names map — same as units.json "slot_to_units" field. */
export const slot_to_units: Record<string, string[]> = {
  "HQ": [],
  "Troops": [],
  "Elites": [
    "Callidus",
    "Culexus",
    "Eversor",
    "Vindicare"
  ],
  "Fast Attack": [],
  "Heavy Support": [],
  "Dedicated Transport": [],
  "Fortifications": [],
  "Flyers": []
};

export const faction = "Assassins";
