/**
 * horus_heresy - unit index.
 *
 * Each unit is a PURE JSON file next to this one, so the codex tooling can rewrite it from the
 * sheets without touching any TypeScript. This is the only .ts in the folder: it imports them
 * and exports `faction`, `slot_to_units` and `units` exactly as the regular factions do.
 * Everything that is not a unit (armory, daemonkin, ...) is in ../supplement.json.
 *
 * Generated by scripts/convert_supplement_to_folders.cjs. To add a unit, add its .json and one line here.
 */

import type { Unit } from '../../../../src/types/data';

import troops_legion_breacher_squad from './troops/legion_breacher_squad.json';
import troops_legion_tactical_squad from './troops/legion_tactical_squad.json';
import troops_legion_tactical_support_squad from './troops/legion_tactical_support_squad.json';
import elites_legion_contemptor_dreadnought from './elites/legion_contemptor_dreadnought.json';
import elites_legion_terminator_cataphractii_squad from './elites/legion_terminator_cataphractii_squad.json';
import elites_palatine_blade_squad from './elites/palatine_blade_squad.json';
import fast_attack_legion_sky_hunter_squadron from './fast_attack/legion_sky-hunter_squadron.json';
import heavy_support_kakophoni_squad from './heavy_support/kakophoni_squad.json';
import heavy_support_kharybdis_assault_claw from './heavy_support/kharybdis_assault_claw.json';
import heavy_support_legion_heavy_support_squad from './heavy_support/legion_heavy_support_squad.json';
import heavy_support_legion_leviathan_dreadnought from './heavy_support/legion_leviathan_dreadnought.json';
import heavy_support_legion_sicaran_battle_tank from './heavy_support/legion_sicaran_battle_tank.json';
import elites_saturnine_terminator_squad from './elites/saturnine_terminator_squad.json';

export const faction = "Horus Heresy Legiones Astartes";

export const slot_to_units: Record<string, string[]> = {
  "HQ": [],
  "Troops": [
    "Legion Breacher Squad",
    "Legion Tactical Squad",
    "Legion Tactical Support Squad"
  ],
  "Elites": [
    "Legion Contemptor Dreadnought",
    "Legion Terminator Cataphractii Squad",
    "Palatine Blade Squad",
    "Saturnine Terminator Squad"
  ],
  "Fast Attack": [
    "Legion Sky-hunter Squadron"
  ],
  "Heavy Support": [
    "Kakophoni Squad",
    "Kharybdis Assault Claw",
    "Legion Heavy Support Squad",
    "Legion Leviathan Dreadnought",
    "Legion Sicaran Battle Tank"
  ],
  "Dedicated Transport": [],
  "Fortifications": [],
  "Flyers": []
};

/** All units keyed by name. */
export const units: Record<string, Unit> = {
  "Legion Breacher Squad": troops_legion_breacher_squad as Unit,
  "Legion Tactical Squad": troops_legion_tactical_squad as Unit,
  "Legion Tactical Support Squad": troops_legion_tactical_support_squad as Unit,
  "Legion Contemptor Dreadnought": elites_legion_contemptor_dreadnought as Unit,
  "Legion Terminator Cataphractii Squad": elites_legion_terminator_cataphractii_squad as Unit,
  "Palatine Blade Squad": elites_palatine_blade_squad as Unit,
  "Legion Sky-hunter Squadron": fast_attack_legion_sky_hunter_squadron as Unit,
  "Kakophoni Squad": heavy_support_kakophoni_squad as Unit,
  "Kharybdis Assault Claw": heavy_support_kharybdis_assault_claw as Unit,
  "Legion Heavy Support Squad": heavy_support_legion_heavy_support_squad as Unit,
  "Legion Leviathan Dreadnought": heavy_support_legion_leviathan_dreadnought as Unit,
  "Legion Sicaran Battle Tank": heavy_support_legion_sicaran_battle_tank as Unit,
  "Saturnine Terminator Squad": elites_saturnine_terminator_squad as Unit,
};
