/**
 * Necrons — unit index
 * Auto-generated by _migrate_units_to_ts.cjs
 * Each unit lives in its own file under units/<slot>/<name>.ts
 * Add SOURCE comments and engine status notes when auditing each unit.
 */

import * as dedicatedTransport from './dedicated_transport/index';
import * as elites from './elites/index';
import * as fastAttack from './fast_attack/index';
import * as flyers from './flyers/index';
import * as fortifications from './fortifications/index';
import * as heavySupport from './heavy_support/index';
import * as hq from './hq/index';
import * as lordsOfWar from './lords_of_war/index';
import * as troops from './troops/index';

/** All units keyed by name — drop-in replacement for units.json "units" field. */
export const units: Record<string, import('../../../../src/types/data').Unit> = {
  "Ancient Destructor Lord": hq.ancientDestructorLord,
  "Cryptek": hq.cryptek,
  "Lord": hq.lord,
  "Royal Warden": hq.royalWarden,
  "Skorpekh Lord": hq.skorpekhLord,
  "Flayed Ones": troops.flayedOnes,
  "Immortals": troops.immortals,
  "Warriors": troops.warriors,
  "C'tan Shard": elites.ctanShard,
  "C'tan Shard of the Deceiver": elites.ctanShardOfTheDeceiver,
  "C'tan Shard of the Dragon": elites.ctanShardOfTheDragon,
  "C'tan Shard of the Nightbringer": elites.ctanShardOfTheNightbringer,
  "Canoptek Reanimator": elites.canoptekReanimator,
  "Canoptek Spyders": elites.canoptekSpyders,
  "Cryptothralls": elites.cryptothralls,
  "Deathmarks": elites.deathmarks,
  "Hexmark Destroyer": elites.hexmarkDestroyer,
  "Lychguard": elites.lychguard,
  "Pariahs": elites.pariahs,
  "Plasmacyte": elites.plasmacyte,
  "Skorpekh Destroyers": elites.skorpekhDestroyers,
  "Triarch Stalker": elites.triarchStalker,
  "Canoptek Scarabs": fastAttack.canoptekScarabs,
  "Canoptek Wraiths": fastAttack.canoptekWraiths,
  "Ophydian Destroyers": fastAttack.ophydianDestroyers,
  "Tomb Blades": fastAttack.tombBlades,
  "Triarch Praetorians": fastAttack.triarchPraetorians,
  "Annihilation Barge": heavySupport.annihilationBarge,
  "Canoptek Doomstalker": heavySupport.canoptekDoomstalker,
  "Doomsday Ark": heavySupport.doomsdayArk,
  "Lokhust Destroyers": heavySupport.lokhustDestroyers,
  "Monolith": heavySupport.monolith,
  "Ghost Ark": dedicatedTransport.ghostArk,
  "Catacomb Command Barge": dedicatedTransport.catacombCommandBarge,
  "Convergence of Dominion": fortifications.convergenceOfDominion,
  "Doom Scythe": flyers.doomScythe,
  "Night Scythe": flyers.nightScythe,
  "Dynasty Phaeron": lordsOfWar.dynastyPhaeron,
  "Tesseract Vault": lordsOfWar.tesseractVault,
};

/** Slot → unit names map — same as units.json "slot_to_units" field. */
export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Ancient Destructor Lord",
    "Cryptek",
    "Lord",
    "Royal Warden",
    "Skorpekh Lord"
  ],
  "Troops": [
    "Flayed Ones",
    "Immortals",
    "Warriors"
  ],
  "Elites": [
    "C'tan Shard",
    "C'tan Shard of the Deceiver",
    "C'tan Shard of the Dragon",
    "C'tan Shard of the Nightbringer",
    "Canoptek Reanimator",
    "Canoptek Spyders",
    "Cryptothralls",
    "Deathmarks",
    "Hexmark Destroyer",
    "Lychguard",
    "Pariahs",
    "Plasmacyte",
    "Skorpekh Destroyers",
    "Triarch Stalker"
  ],
  "Fast Attack": [
    "Canoptek Scarabs",
    "Canoptek Wraiths",
    "Ophydian Destroyers",
    "Tomb Blades",
    "Triarch Praetorians"
  ],
  "Heavy Support": [
    "Annihilation Barge",
    "Canoptek Doomstalker",
    "Doomsday Ark",
    "Lokhust Destroyers",
    "Monolith"
  ],
  "Dedicated Transport": [
    "Ghost Ark",
    "Catacomb Command Barge"
  ],
  "Fortifications": [
    "Convergence of Dominion"
  ],
  "Flyers": [
    "Doom Scythe",
    "Night Scythe"
  ],
  "Lords of War": [
    "Dynasty Phaeron",
    "Tesseract Vault"
  ]
};

export const faction = "Necrons";
