/**
 * necrons - unit index.
 *
 * Each unit is a PURE JSON file next to this one, so the codex tooling can rewrite it from the
 * sheets without touching any TypeScript. This is the only .ts in the folder: it imports them
 * and exports `faction`, `slot_to_units` and `units` exactly as the old per-slot indexes did.
 *
 * Generated by scripts/convert_units_to_json.cjs. To add a unit, add its .json and one line here.
 */

import type { Unit } from '../../../../src/types/data';

import hq_ancient_destructor_lord from './hq/ancient_destructor_lord.json';
import hq_cryptek from './hq/cryptek.json';
import hq_lord from './hq/lord.json';
import hq_royal_warden from './hq/royal_warden.json';
import hq_skorpekh_lord from './hq/skorpekh_lord.json';
import troops_flayed_ones from './troops/flayed_ones.json';
import troops_immortals from './troops/immortals.json';
import troops_warriors from './troops/warriors.json';
import elites_ctan_shard from './elites/ctan_shard.json';
import elites_ctan_shard_of_the_deceiver from './elites/ctan_shard_of_the_deceiver.json';
import elites_ctan_shard_of_the_dragon from './elites/ctan_shard_of_the_dragon.json';
import elites_ctan_shard_of_the_nightbringer from './elites/ctan_shard_of_the_nightbringer.json';
import elites_canoptek_reanimator from './elites/canoptek_reanimator.json';
import elites_canoptek_spyders from './elites/canoptek_spyders.json';
import elites_cryptothralls from './elites/cryptothralls.json';
import elites_deathmarks from './elites/deathmarks.json';
import elites_hexmark_destroyer from './elites/hexmark_destroyer.json';
import elites_lychguard from './elites/lychguard.json';
import elites_pariahs from './elites/pariahs.json';
import elites_plasmacyte from './elites/plasmacyte.json';
import elites_skorpekh_destroyers from './elites/skorpekh_destroyers.json';
import elites_triarch_stalker from './elites/triarch_stalker.json';
import fast_attack_canoptek_scarabs from './fast_attack/canoptek_scarabs.json';
import fast_attack_canoptek_wraiths from './fast_attack/canoptek_wraiths.json';
import fast_attack_ophydian_destroyers from './fast_attack/ophydian_destroyers.json';
import fast_attack_tomb_blades from './fast_attack/tomb_blades.json';
import fast_attack_triarch_praetorians from './fast_attack/triarch_praetorians.json';
import heavy_support_annihilation_barge from './heavy_support/annihilation_barge.json';
import heavy_support_canoptek_doomstalker from './heavy_support/canoptek_doomstalker.json';
import heavy_support_canoptek_tomb_stalker from './heavy_support/canoptek_tomb_stalker.json';
import heavy_support_doomsday_ark from './heavy_support/doomsday_ark.json';
import heavy_support_lokhust_destroyers from './heavy_support/lokhust_destroyers.json';
import heavy_support_monolith from './heavy_support/monolith.json';
import dedicated_transport_ghost_ark from './dedicated_transport/ghost_ark.json';
import dedicated_transport_catacomb_command_barge from './dedicated_transport/catacomb_command_barge.json';
import fortifications_convergence_of_dominion from './fortifications/convergence_of_dominion.json';
import flyers_doom_scythe from './flyers/doom_scythe.json';
import flyers_night_scythe from './flyers/night_scythe.json';
import lords_of_war_dynasty_phaeron from './lords_of_war/dynasty_phaeron.json';
import lords_of_war_tesseract_vault from './lords_of_war/tesseract_vault.json';

export const faction = "Necrons";

export const slot_to_units: Record<string, string[]> = {
  "HQ": [
    "Ancient Destructor Lord",
    "Cryptek",
    "Lord",
    "Royal Warden",
    "Skorpekh Lord"
  ],
  "Troops": [
    "Flayed Ones",
    "Immortals",
    "Warriors"
  ],
  "Elites": [
    "C'tan Shard",
    "C'tan Shard of the Deceiver",
    "C'tan Shard of the Dragon",
    "C'tan Shard of the Nightbringer",
    "Canoptek Reanimator",
    "Canoptek Spyders",
    "Cryptothralls",
    "Deathmarks",
    "Hexmark Destroyer",
    "Lychguard",
    "Pariahs",
    "Plasmacyte",
    "Skorpekh Destroyers",
    "Triarch Stalker"
  ],
  "Fast Attack": [
    "Canoptek Scarabs",
    "Canoptek Wraiths",
    "Ophydian Destroyers",
    "Tomb Blades",
    "Triarch Praetorians"
  ],
  "Heavy Support": [
    "Canoptek Tomb Stalker",
    "Annihilation Barge",
    "Canoptek Doomstalker",
    "Doomsday Ark",
    "Lokhust Destroyers",
    "Monolith"
  ],
  "Dedicated Transport": [
    "Ghost Ark",
    "Catacomb Command Barge"
  ],
  "Fortifications": [
    "Convergence of Dominion"
  ],
  "Flyers": [
    "Doom Scythe",
    "Night Scythe"
  ],
  "Lords of War": [
    "Dynasty Phaeron",
    "Tesseract Vault"
  ]
};

/** All units keyed by name. */
export const units: Record<string, Unit> = {
  "Ancient Destructor Lord": hq_ancient_destructor_lord as Unit,
  "Cryptek": hq_cryptek as Unit,
  "Lord": hq_lord as Unit,
  "Royal Warden": hq_royal_warden as Unit,
  "Skorpekh Lord": hq_skorpekh_lord as Unit,
  "Flayed Ones": troops_flayed_ones as Unit,
  "Immortals": troops_immortals as Unit,
  "Warriors": troops_warriors as Unit,
  "C'tan Shard": elites_ctan_shard as Unit,
  "C'tan Shard of the Deceiver": elites_ctan_shard_of_the_deceiver as Unit,
  "C'tan Shard of the Dragon": elites_ctan_shard_of_the_dragon as Unit,
  "C'tan Shard of the Nightbringer": elites_ctan_shard_of_the_nightbringer as Unit,
  "Canoptek Reanimator": elites_canoptek_reanimator as Unit,
  "Canoptek Spyders": elites_canoptek_spyders as Unit,
  "Cryptothralls": elites_cryptothralls as Unit,
  "Deathmarks": elites_deathmarks as Unit,
  "Hexmark Destroyer": elites_hexmark_destroyer as Unit,
  "Lychguard": elites_lychguard as Unit,
  "Pariahs": elites_pariahs as Unit,
  "Plasmacyte": elites_plasmacyte as Unit,
  "Skorpekh Destroyers": elites_skorpekh_destroyers as Unit,
  "Triarch Stalker": elites_triarch_stalker as Unit,
  "Canoptek Scarabs": fast_attack_canoptek_scarabs as Unit,
  "Canoptek Wraiths": fast_attack_canoptek_wraiths as Unit,
  "Ophydian Destroyers": fast_attack_ophydian_destroyers as Unit,
  "Tomb Blades": fast_attack_tomb_blades as Unit,
  "Triarch Praetorians": fast_attack_triarch_praetorians as Unit,
  "Annihilation Barge": heavy_support_annihilation_barge as Unit,
  "Canoptek Doomstalker": heavy_support_canoptek_doomstalker as Unit,
  "Canoptek Tomb Stalker": heavy_support_canoptek_tomb_stalker as Unit,
  "Doomsday Ark": heavy_support_doomsday_ark as Unit,
  "Lokhust Destroyers": heavy_support_lokhust_destroyers as Unit,
  "Monolith": heavy_support_monolith as Unit,
  "Ghost Ark": dedicated_transport_ghost_ark as Unit,
  "Catacomb Command Barge": dedicated_transport_catacomb_command_barge as Unit,
  "Convergence of Dominion": fortifications_convergence_of_dominion as Unit,
  "Doom Scythe": flyers_doom_scythe as Unit,
  "Night Scythe": flyers_night_scythe as Unit,
  "Dynasty Phaeron": lords_of_war_dynasty_phaeron as Unit,
  "Tesseract Vault": lords_of_war_tesseract_vault as Unit,
};
